import type { IndustryId } from "@/lib/ai-core/templates/types";
import type { WebsiteIndustryIntelligence } from "@/lib/ai-core/industry-intelligence/types";

/**
 * AI Industry Website Intelligence — agency-grade blueprints per vertical.
 * Used by Website Builder: detect → strategy → template → design → content.
 */
export const WEBSITE_INDUSTRY_INTELLIGENCE: Record<
  IndustryId,
  WebsiteIndustryIntelligence
> = {
  tourism: {
    id: "tourism",
    label: "Tourism",
    description:
      "Travel and tourism brands with destinations, tours, packages, and booking.",
    keywords: [
      "tourism",
      "travel",
      "tour",
      "destination",
      "vacation",
      "holiday",
      "trip",
      "hotel",
      "resort",
      "adventure",
      "cruise",
      "travel agency",
    ],
    recommendedPages: [
      "Home",
      "Destinations",
      "Tours",
      "Packages",
      "About",
      "Testimonials",
      "Contact",
      "Booking",
    ],
    requiredSections: [
      "Hero destination",
      "Featured destinations",
      "Popular tours",
      "Travel packages",
      "Why travel with us",
      "Traveler stories",
      "Booking CTA",
      "Contact",
    ],
    ctaTypes: [
      "Book a trip",
      "Explore destinations",
      "View packages",
      "Request itinerary",
      "Contact a travel expert",
    ],
    contentStyle:
      "inspirational, wanderlust-driven, clear trip details and trust signals",
    designStyle: "Travel premium",
    designPreset: "luxury",
    layoutStyle: "travel-premium",
    industryPattern: "travel-tourism",
    imageRequirements: [
      "Cinematic destination hero landscapes",
      "Tour and experience lifestyle photography",
      "Package / itinerary mood images",
      "Happy traveler testimonials visuals",
      "Map or destination collage accents",
    ],
    requiredFeatures: [
      "destinations",
      "tours",
      "packages",
      "booking-cta",
      "testimonials",
      "itinerary-inquiry",
    ],
    preferredSmartTemplateId: "tourism-premium",
    preferredPremiumTemplateId: "tourism",
  },
  automotive: {
    id: "automotive",
    label: "Automotive",
    description:
      "Dealership and auto brand experiences with inventory and service CTAs.",
    keywords: [
      "automotive",
      "car",
      "dealer",
      "dealership",
      "vehicle",
      "auto",
      "motors",
      "garage",
      "ev",
      "showroom",
    ],
    recommendedPages: [
      "Home",
      "Inventory",
      "Models",
      "Services",
      "Finance",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero models",
      "Vehicle showcase",
      "Inventory",
      "Finance calculator",
      "Compare models",
      "Test drive calendar",
      "Branch locations",
      "Owner testimonials",
      "Contact",
    ],
    ctaTypes: [
      "Book a test drive",
      "View inventory",
      "Get finance offer",
      "Schedule service",
      "Contact sales",
    ],
    contentStyle: "bold, refined, performance-driven with clear offers",
    designStyle: "Automotive luxury showroom",
    designPreset: "luxury",
    layoutStyle: "vehicle-showroom",
    industryPattern: "auto-mobility",
    imageRequirements: [
      "Premium vehicle hero photography",
      "Showroom and inventory grid shots",
      "Service bay / lifestyle ownership imagery",
      "Detail close-ups of craftsmanship",
    ],
    requiredFeatures: [
      "inventory",
      "model-showcase",
      "finance-cta",
      "service-booking",
      "test-drive",
    ],
    preferredSmartTemplateId: "automotive-luxury",
    preferredPremiumTemplateId: "automotive",
  },
  "real-estate": {
    id: "real-estate",
    label: "Real Estate",
    description:
      "Property marketing with listings, neighborhoods, and inquiry flows.",
    keywords: [
      "real estate",
      "real-estate",
      "property",
      "homes",
      "realtor",
      "listings",
      "apartment",
      "housing",
      "broker",
      "mortgage",
    ],
    recommendedPages: [
      "Home",
      "Listings",
      "Neighborhoods",
      "Buying",
      "Selling",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero search",
      "Featured listings",
      "Neighborhoods",
      "Buying process",
      "Agent trust",
      "Testimonials",
      "Inquiry form",
      "Contact",
    ],
    ctaTypes: [
      "Browse listings",
      "Schedule a viewing",
      "Get a valuation",
      "Talk to an agent",
      "Contact us",
    ],
    contentStyle: "trustworthy, aspirational, neighborhood-aware",
    designStyle: "Property showcase corporate",
    designPreset: "corporate",
    layoutStyle: "property-showcase",
    industryPattern: "property-real-estate",
    imageRequirements: [
      "Luxury property exterior and interior heroes",
      "Featured listing photography",
      "Neighborhood lifestyle imagery",
      "Agent portrait / trust visuals",
    ],
    requiredFeatures: [
      "listings",
      "property-search",
      "inquiry-form",
      "neighborhoods",
      "agent-profiles",
    ],
    preferredSmartTemplateId: "real-estate",
    preferredPremiumTemplateId: "real-estate",
  },
  restaurant: {
    id: "restaurant",
    label: "Restaurant",
    description:
      "Hospitality sites with menus, reservations, ambiance, and location trust.",
    keywords: [
      "restaurant",
      "cafe",
      "coffee",
      "bistro",
      "dining",
      "menu",
      "food",
      "chef",
      "hospitality",
      "bar",
      "bakery",
    ],
    recommendedPages: [
      "Home",
      "Menu",
      "Reservations",
      "Private dining",
      "About",
      "Gallery",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Signature dishes",
      "Menu highlights",
      "Reservations",
      "Atmosphere",
      "Location",
      "Reviews",
      "Contact",
    ],
    ctaTypes: [
      "Reserve a table",
      "View menu",
      "Order online",
      "Book private dining",
      "Find us",
    ],
    contentStyle: "warm, appetizing, sensory and hospitality-led",
    designStyle: "Restaurant premium editorial",
    designPreset: "luxury",
    layoutStyle: "editorial-hero",
    industryPattern: "hospitality-dining",
    imageRequirements: [
      "Signature dish hero photography",
      "Dining room atmosphere shots",
      "Chef / kitchen craft imagery",
      "Menu and ingredient close-ups",
    ],
    requiredFeatures: [
      "menu",
      "reservations",
      "gallery",
      "location-map",
      "reviews",
    ],
    preferredSmartTemplateId: "restaurant-premium",
    preferredPremiumTemplateId: "restaurant",
  },
  saas: {
    id: "saas",
    label: "SaaS",
    description:
      "Software product marketing with features, pricing, and onboarding CTAs.",
    keywords: [
      "saas",
      "software",
      "platform",
      "subscription",
      "dashboard",
      "api",
      "b2b",
      "startup",
      "product",
      "cloud",
    ],
    recommendedPages: [
      "Home",
      "Features",
      "Pricing",
      "Solutions",
      "Docs",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Problem",
      "Solution",
      "Features",
      "How it works",
      "Pricing",
      "Testimonials",
      "CTA",
    ],
    ctaTypes: [
      "Start free trial",
      "Book a demo",
      "See pricing",
      "View features",
      "Talk to sales",
    ],
    contentStyle: "confident, product-led, benefit-first and crisp",
    designStyle: "SaaS modern product",
    designPreset: "tech",
    layoutStyle: "product-saas",
    industryPattern: "product-saas",
    imageRequirements: [
      "Product UI / dashboard hero mockups",
      "Feature illustration or screenshots",
      "Team collaboration lifestyle imagery",
      "Logo wall / social proof visuals",
    ],
    requiredFeatures: [
      "pricing",
      "feature-grid",
      "integrations",
      "auth-cta",
      "demo-request",
    ],
    preferredSmartTemplateId: "saas-startup",
    preferredPremiumTemplateId: "saas",
  },
  clinic: {
    id: "clinic",
    label: "Healthcare",
    description:
      "Medical and wellness sites with services, clinicians, and appointments.",
    keywords: [
      "clinic",
      "medical",
      "doctor",
      "healthcare",
      "health care",
      "dental",
      "wellness",
      "hospital",
      "patient",
      "appointment",
      "therapy",
    ],
    recommendedPages: [
      "Home",
      "Services",
      "Doctors",
      "Patients",
      "Insurance",
      "About",
      "Contact",
      "Booking",
    ],
    requiredSections: [
      "Hero",
      "Care services",
      "Doctors",
      "Why patients choose us",
      "Appointments",
      "Insurance",
      "Patient stories",
      "Contact",
    ],
    ctaTypes: [
      "Book appointment",
      "Our services",
      "Meet the doctors",
      "Patient portal",
      "Contact clinic",
    ],
    contentStyle: "calm, caring, trustworthy, accessible language",
    designStyle: "Healthcare trust minimal",
    designPreset: "minimal",
    layoutStyle: "corporate-trust",
    industryPattern: "healthcare-clinic",
    imageRequirements: [
      "Welcoming clinic / care environment hero",
      "Clinician portraits",
      "Patient care lifestyle imagery (respectful)",
      "Facility and waiting area photography",
    ],
    requiredFeatures: [
      "services",
      "appointments",
      "doctor-profiles",
      "insurance",
      "contact-form",
    ],
    preferredSmartTemplateId: "clinic",
    preferredPremiumTemplateId: "healthcare",
  },
  education: {
    id: "education",
    label: "Education",
    description:
      "Schools, courses, and learning brands with programs, faculty, and enrollment.",
    keywords: [
      "education",
      "school",
      "university",
      "course",
      "learning",
      "academy",
      "training",
      "student",
      "tuition",
      "elearning",
      "e-learning",
      "campus",
    ],
    recommendedPages: [
      "Home",
      "Programs",
      "Courses",
      "Admissions",
      "Faculty",
      "Campus life",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Featured programs",
      "Why learn with us",
      "Curriculum highlights",
      "Faculty",
      "Student outcomes",
      "Admissions CTA",
      "Contact",
    ],
    ctaTypes: [
      "Apply now",
      "Explore programs",
      "Request syllabus",
      "Book a campus tour",
      "Talk to admissions",
    ],
    contentStyle: "inspiring, clear outcomes, credibility-led academic tone",
    designStyle: "Education modern campus",
    designPreset: "modern",
    layoutStyle: "campus-education",
    industryPattern: "education-learning",
    imageRequirements: [
      "Campus or classroom hero photography",
      "Students learning / collaboration visuals",
      "Faculty and mentorship imagery",
      "Program outcome / graduation moments",
    ],
    requiredFeatures: [
      "programs",
      "courses",
      "admissions",
      "faculty",
      "enrollment-cta",
    ],
    preferredSmartTemplateId: "education-campus",
    preferredPremiumTemplateId: "education",
  },
  ecommerce: {
    id: "ecommerce",
    label: "E-commerce",
    description:
      "Product-led storefronts with catalog, cart signals, and conversion sections.",
    keywords: [
      "ecommerce",
      "e-commerce",
      "shop",
      "store",
      "product",
      "cart",
      "checkout",
      "retail",
      "marketplace",
      "sku",
    ],
    recommendedPages: [
      "Home",
      "Shop",
      "Collections",
      "Product",
      "About",
      "FAQ",
      "Contact",
    ],
    requiredSections: [
      "Hero offer",
      "Featured products",
      "Collections",
      "Benefits",
      "Social proof",
      "Shipping & returns",
      "FAQ",
      "CTA",
    ],
    ctaTypes: [
      "Shop now",
      "View collections",
      "Add to cart",
      "See bestsellers",
      "Get support",
    ],
    contentStyle: "clear, conversion-focused, benefit and trust driven",
    designStyle: "E-commerce modern retail",
    designPreset: "modern",
    layoutStyle: "commerce-grid",
    industryPattern: "retail-commerce",
    imageRequirements: [
      "Product hero and lifestyle shots",
      "Collection / category imagery",
      "Detail and packing / unboxing visuals",
      "Trust and lifestyle brand photography",
    ],
    requiredFeatures: [
      "product-catalog",
      "featured-products",
      "cart-cta",
      "trust-badges",
      "faq",
    ],
    preferredSmartTemplateId: "ecommerce-store",
    preferredPremiumTemplateId: "ecommerce",
  },
  agency: {
    id: "agency",
    label: "Agency",
    description:
      "Creative and consulting agency sites with services, work, and lead capture.",
    keywords: [
      "agency",
      "studio",
      "creative",
      "marketing agency",
      "design agency",
      "consultancy",
      "portfolio",
      "clients",
      "campaign",
    ],
    recommendedPages: [
      "Home",
      "Work",
      "Services",
      "About",
      "Insights",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Services",
      "Selected work",
      "Process",
      "Clients",
      "Capabilities",
      "Testimonials",
      "Contact",
    ],
    ctaTypes: [
      "Start a project",
      "View work",
      "Our services",
      "Book a call",
      "Contact the studio",
    ],
    contentStyle: "sharp, creative, confident with proof of craft",
    designStyle: "Agency studio portfolio",
    designPreset: "creative",
    layoutStyle: "studio-portfolio",
    industryPattern: "creative-agency",
    imageRequirements: [
      "Bold portfolio case study visuals",
      "Studio / team atmosphere photography",
      "Process and craft detail imagery",
      "Client brand / campaign stills",
    ],
    requiredFeatures: [
      "portfolio",
      "services",
      "case-studies",
      "lead-form",
      "process",
    ],
    preferredSmartTemplateId: "agency",
    preferredPremiumTemplateId: "agency",
  },
  business: {
    id: "business",
    label: "Luxury Business",
    description:
      "Premium firms, consultancies, and high-end professional brands with editorial luxury presentation.",
    keywords: [
      "business",
      "luxury",
      "premium",
      "company",
      "services",
      "consulting",
      "professional",
      "corporate",
      "executive",
      "private",
      "enterprise",
      "smb",
    ],
    recommendedPages: [
      "Home",
      "Services",
      "About",
      "Insights",
      "Testimonials",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Services",
      "Features",
      "Showcase",
      "Testimonials",
      "Team",
      "FAQ",
      "CTA",
      "Contact",
    ],
    ctaTypes: [
      "Request consultation",
      "View services",
      "Read insights",
      "Talk to us",
      "Contact",
    ],
    contentStyle: "refined, confident, concise, exclusive without arrogance",
    designStyle: "Luxury editorial",
    designPreset: "luxury",
    layoutStyle: "corporate-trust",
    industryPattern: "luxury-professional-services",
    imageRequirements: [
      "Cinematic luxury brand atmosphere hero",
      "Premium service lifestyle photography",
      "Editorial detail shots for features",
      "Portfolio-quality brand moments",
    ],
    requiredFeatures: [
      "services",
      "about",
      "testimonials",
      "contact-form",
      "trust-signals",
      "insights",
    ],
    preferredSmartTemplateId: "agency",
    preferredPremiumTemplateId: "luxury-business",
  },
};

export const WEBSITE_INDUSTRY_IDS = Object.keys(
  WEBSITE_INDUSTRY_INTELLIGENCE,
) as IndustryId[];

/** Primary Website Builder verticals called out in product requirements. */
export const PRIMARY_WEBSITE_INDUSTRIES: IndustryId[] = [
  "tourism",
  "automotive",
  "real-estate",
  "restaurant",
  "saas",
  "clinic",
  "education",
  "ecommerce",
  "agency",
];

export function getWebsiteIndustryIntelligence(
  id: IndustryId,
): WebsiteIndustryIntelligence {
  return WEBSITE_INDUSTRY_INTELLIGENCE[id];
}

export function listWebsiteIndustryIntelligence(): WebsiteIndustryIntelligence[] {
  return WEBSITE_INDUSTRY_IDS.map((id) => WEBSITE_INDUSTRY_INTELLIGENCE[id]);
}

export function listPrimaryWebsiteIndustryIntelligence(): WebsiteIndustryIntelligence[] {
  return PRIMARY_WEBSITE_INDUSTRIES.map((id) => WEBSITE_INDUSTRY_INTELLIGENCE[id]);
}
