import type { IndustryId } from "@/lib/ai-core/templates/types";
import type { WebsiteIndustryIntelligence } from "@/lib/ai-core/industry-intelligence/types";

/**
 * AI Industry Website Intelligence — agency-grade blueprints per vertical.
 * Used by Website Builder: detect → strategy → template → design → content.
 */
export const WEBSITE_INDUSTRY_INTELLIGENCE: Record<
  IndustryId,
  WebsiteIndustryIntelligence
> = {
  tourism: {
    id: "tourism",
    label: "Tourism",
    description:
      "Travel and tourism brands with destinations, tours, packages, and booking.",
    keywords: [
      "tourism",
      "travel",
      "tour",
      "destination",
      "vacation",
      "holiday",
      "trip",
      "hotel",
      "resort",
      "adventure",
      "cruise",
      "travel agency",
    ],
    recommendedPages: [
      "Home",
      "Destinations",
      "Tours",
      "Packages",
      "About",
      "Testimonials",
      "Contact",
      "Booking",
    ],
    requiredSections: [
      "Hero destination",
      "Featured destinations",
      "Popular tours",
      "Travel packages",
      "Why travel with us",
      "Traveler stories",
      "Booking CTA",
      "Contact",
    ],
    ctaTypes: [
      "Book a trip",
      "Explore destinations",
      "View packages",
      "Request itinerary",
      "Contact a travel expert",
    ],
    contentStyle:
      "inspirational, wanderlust-driven, clear trip details and trust signals",
    designStyle: "Travel premium",
    designPreset: "luxury",
    layoutStyle: "travel-premium",
    industryPattern: "travel-tourism",
    imageRequirements: [
      "Cinematic destination hero landscapes",
      "Tour and experience lifestyle photography",
      "Package / itinerary mood images",
      "Happy traveler testimonials visuals",
      "Map or destination collage accents",
    ],
    requiredFeatures: [
      "destinations",
      "tours",
      "packages",
      "booking-cta",
      "testimonials",
      "itinerary-inquiry",
    ],
    preferredSmartTemplateId: "tourism-premium",
    preferredPremiumTemplateId: "tourism",
  },
  automotive: {
    id: "automotive",
    label: "Automotive",
    description:
      "Dealership and auto brand experiences with inventory and service CTAs.",
    keywords: [
      "automotive",
      "car",
      "dealer",
      "dealership",
      "vehicle",
      "auto",
      "motors",
      "garage",
      "ev",
      "showroom",
    ],
    recommendedPages: [
      "Home",
      "Inventory",
      "Models",
      "Services",
      "Finance",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero models",
      "Vehicle showcase",
      "Inventory",
      "Finance calculator",
      "Compare models",
      "Test drive calendar",
      "Branch locations",
      "Owner testimonials",
      "Contact",
    ],
    ctaTypes: [
      "Book a test drive",
      "View inventory",
      "Get finance offer",
      "Schedule service",
      "Contact sales",
    ],
    contentStyle: "bold, refined, performance-driven with clear offers",
    designStyle: "Automotive luxury showroom",
    designPreset: "luxury",
    layoutStyle: "vehicle-showroom",
    industryPattern: "auto-mobility",
    imageRequirements: [
      "Premium vehicle hero photography",
      "Showroom and inventory grid shots",
      "Service bay / lifestyle ownership imagery",
      "Detail close-ups of craftsmanship",
    ],
    requiredFeatures: [
      "inventory",
      "model-showcase",
      "finance-cta",
      "service-booking",
      "test-drive",
    ],
    preferredSmartTemplateId: "automotive-luxury",
    preferredPremiumTemplateId: "automotive",
  },
  "real-estate": {
    id: "real-estate",
    label: "Real Estate",
    description:
      "Property marketing with listings, neighborhoods, and inquiry flows.",
    keywords: [
      "real estate",
      "real-estate",
      "property",
      "homes",
      "realtor",
      "listings",
      "apartment",
      "housing",
      "broker",
      "mortgage",
    ],
    recommendedPages: [
      "Home",
      "Listings",
      "Neighborhoods",
      "Buying",
      "Selling",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero search",
      "Featured listings",
      "Neighborhoods",
      "Buying process",
      "Agent trust",
      "Testimonials",
      "Inquiry form",
      "Contact",
    ],
    ctaTypes: [
      "Browse listings",
      "Schedule a viewing",
      "Get a valuation",
      "Talk to an agent",
      "Contact us",
    ],
    contentStyle: "trustworthy, aspirational, neighborhood-aware",
    designStyle: "Property showcase corporate",
    designPreset: "corporate",
    layoutStyle: "property-showcase",
    industryPattern: "property-real-estate",
    imageRequirements: [
      "Luxury property exterior and interior heroes",
      "Featured listing photography",
      "Neighborhood lifestyle imagery",
      "Agent portrait / trust visuals",
    ],
    requiredFeatures: [
      "listings",
      "property-search",
      "inquiry-form",
      "neighborhoods",
      "agent-profiles",
    ],
    preferredSmartTemplateId: "real-estate",
    preferredPremiumTemplateId: "real-estate",
  },
  restaurant: {
    id: "restaurant",
    label: "Restaurant",
    description:
      "Hospitality sites with menus, reservations, ambiance, and location trust.",
    keywords: [
      "restaurant",
      "cafe",
      "coffee",
      "bistro",
      "dining",
      "menu",
      "food",
      "chef",
      "hospitality",
      "bar",
      "bakery",
    ],
    recommendedPages: [
      "Home",
      "Menu",
      "Reservations",
      "Private dining",
      "About",
      "Gallery",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Signature dishes",
      "Menu highlights",
      "Reservations",
      "Atmosphere",
      "Location",
      "Reviews",
      "Contact",
    ],
    ctaTypes: [
      "Reserve a table",
      "View menu",
      "Order online",
      "Book private dining",
      "Find us",
    ],
    contentStyle: "warm, appetizing, sensory and hospitality-led",
    designStyle: "Restaurant premium editorial",
    designPreset: "luxury",
    layoutStyle: "editorial-hero",
    industryPattern: "hospitality-dining",
    imageRequirements: [
      "Signature dish hero photography",
      "Dining room atmosphere shots",
      "Chef / kitchen craft imagery",
      "Menu and ingredient close-ups",
    ],
    requiredFeatures: [
      "menu",
      "reservations",
      "gallery",
      "location-map",
      "reviews",
    ],
    preferredSmartTemplateId: "restaurant-premium",
    preferredPremiumTemplateId: "restaurant",
  },
  saas: {
    id: "saas",
    label: "SaaS",
    description:
      "Software product marketing with features, pricing, and onboarding CTAs.",
    keywords: [
      "saas",
      "software",
      "platform",
      "subscription",
      "dashboard",
      "api",
      "b2b",
      "startup",
      "product",
      "cloud",
    ],
    recommendedPages: [
      "Home",
      "Features",
      "Pricing",
      "Solutions",
      "Docs",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Problem",
      "Solution",
      "Features",
      "How it works",
      "Pricing",
      "Testimonials",
      "CTA",
    ],
    ctaTypes: [
      "Start free trial",
      "Book a demo",
      "See pricing",
      "View features",
      "Talk to sales",
    ],
    contentStyle: "confident, product-led, benefit-first and crisp",
    designStyle: "SaaS modern product",
    designPreset: "tech",
    layoutStyle: "product-saas",
    industryPattern: "product-saas",
    imageRequirements: [
      "Product UI / dashboard hero mockups",
      "Feature illustration or screenshots",
      "Team collaboration lifestyle imagery",
      "Logo wall / social proof visuals",
    ],
    requiredFeatures: [
      "pricing",
      "feature-grid",
      "integrations",
      "auth-cta",
      "demo-request",
    ],
    preferredSmartTemplateId: "saas-startup",
    preferredPremiumTemplateId: "saas",
  },
  gaming: {
    id: "gaming",
    label: "Gaming & Esports",
    description:
      "Game studios, esports organizations, gaming platforms, and interactive entertainment brands.",
    keywords: [
      "gaming",
      "esports",
      "e-sports",
      "game studio",
      "video game",
      "videogame",
      "game developer",
      "gamer",
      "twitch",
      "streamer",
      "console",
      "pc gaming",
      "lan",
      "tournament",
      "multiplayer",
      "vr gaming",
      "entertainment",
      "game publisher",
      "indie game",
      "ألعاب",
      "العاب",
      "جيمينج",
      "ألعاب فيديو",
      "استوديو ألعاب",
      "رياضات إلكترونية",
      "شركة ألعاب",
    ],
    recommendedPages: [
      "Home",
      "Games",
      "Esports",
      "Community",
      "News",
      "Careers",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Featured titles",
      "Esports / tournaments",
      "Platform features",
      "Community",
      "Press kit",
      "CTA",
      "Contact",
    ],
    ctaTypes: [
      "Play now",
      "Join the community",
      "Watch live",
      "Download press kit",
      "View tournaments",
    ],
    contentStyle: "bold, immersive, community-driven, high-energy",
    designStyle: "Dark-mode tech with neon accents",
    designPreset: "tech",
    layoutStyle: "product-saas",
    industryPattern: "gaming-esports",
    imageRequirements: [
      "Neon gaming setups and RGB hardware",
      "Esports arena and tournament photography",
      "High-end PC builds and peripherals",
      "VR headsets and immersive play",
      "Community and streaming culture visuals",
    ],
    requiredFeatures: [
      "game-showcase",
      "esports-calendar",
      "community-cta",
      "press-kit",
      "trailer-embed",
    ],
    preferredSmartTemplateId: "saas-enterprise",
    preferredPremiumTemplateId: "saas",
  },
  clinic: {
    id: "clinic",
    label: "Medical",
    description:
      "Hospitals, clinics, dental practices, labs, and healthcare startups with care services, clinicians, and appointments.",
    keywords: [
      "clinic",
      "medical",
      "doctor",
      "healthcare",
      "health care",
      "dental",
      "dentist",
      "wellness",
      "hospital",
      "medical center",
      "laboratory",
      "lab",
      "patient",
      "appointment",
      "therapy",
      "physician",
      "healthcare startup",
      "private doctor",
      "emergency",
      "insurance",
      "department",
    ],
    recommendedPages: [
      "Home",
      "About",
      "Services",
      "Doctors",
      "Departments",
      "Appointments",
      "Emergency",
      "Insurance",
      "Patients",
      "Contact",
      "Location",
    ],
    requiredSections: [
      "Hero",
      "About",
      "Doctors",
      "Departments",
      "Care services",
      "Appointment booking",
      "Emergency",
      "Insurance",
      "Testimonials",
      "FAQ",
      "Contact",
      "Location",
      "Medical CTA",
    ],
    ctaTypes: [
      "Book appointment",
      "Emergency care",
      "Our services",
      "Meet the doctors",
      "Patient portal",
      "Contact clinic",
    ],
    contentStyle: "calm, caring, trustworthy, accessible language",
    designStyle: "Medical trust minimal",
    designPreset: "minimal",
    layoutStyle: "corporate-trust",
    industryPattern: "healthcare-medical",
    imageRequirements: [
      "Welcoming hospital or clinic hero photography",
      "Doctor and clinician portrait photography",
      "Healthcare facility and department imagery",
      "Patient care lifestyle photography (respectful)",
      "Medical technology and laboratory visuals",
    ],
    requiredFeatures: [
      "services",
      "appointments",
      "doctor-profiles",
      "departments",
      "emergency",
      "insurance",
      "booking-cta",
      "contact-form",
      "location-map",
    ],
    preferredSmartTemplateId: "clinic",
    preferredPremiumTemplateId: "healthcare",
  },
  education: {
    id: "education",
    label: "Education",
    description:
      "Universities, schools, academies, training centers, online courses, and bootcamps.",
    keywords: [
      "education",
      "school",
      "university",
      "course",
      "courses",
      "learning",
      "academy",
      "training",
      "training center",
      "bootcamp",
      "online course",
      "student",
      "teacher",
      "tuition",
      "elearning",
      "e-learning",
      "campus",
      "admissions",
      "certificate",
      "certificates",
    ],
    recommendedPages: [
      "Home",
      "Programs",
      "Courses",
      "Teachers",
      "Admissions",
      "Events",
      "Certificates",
      "News",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Programs",
      "Courses",
      "Teachers",
      "Admissions",
      "Events",
      "Certificates",
      "Testimonials",
      "FAQ",
      "News",
      "Contact",
      "Education CTA",
    ],
    ctaTypes: [
      "Apply now",
      "Explore programs",
      "View courses",
      "Request syllabus",
      "Book a campus tour",
      "Talk to admissions",
    ],
    contentStyle: "inspiring, clear outcomes, credibility-led academic tone",
    designStyle: "Education modern campus",
    designPreset: "modern",
    layoutStyle: "campus-education",
    industryPattern: "education-learning",
    imageRequirements: [
      "Campus or classroom hero photography",
      "Students learning and collaboration visuals",
      "Teachers and faculty mentorship imagery",
      "Graduation and certificate outcome moments",
      "Online learning and bootcamp environment shots",
    ],
    requiredFeatures: [
      "programs",
      "courses",
      "admissions",
      "faculty",
      "events",
      "certificates",
      "enrollment-cta",
      "news",
    ],
    preferredSmartTemplateId: "education-campus",
    preferredPremiumTemplateId: "education",
  },
  ecommerce: {
    id: "ecommerce",
    label: "E-commerce",
    description:
      "Product-led storefronts with catalog, cart signals, and conversion sections.",
    keywords: [
      "ecommerce",
      "e-commerce",
      "shop",
      "store",
      "product",
      "cart",
      "checkout",
      "retail",
      "marketplace",
      "sku",
    ],
    recommendedPages: [
      "Home",
      "Shop",
      "Collections",
      "Product",
      "About",
      "FAQ",
      "Contact",
    ],
    requiredSections: [
      "Hero offer",
      "Featured products",
      "Collections",
      "Benefits",
      "Social proof",
      "Shipping & returns",
      "FAQ",
      "CTA",
    ],
    ctaTypes: [
      "Shop now",
      "View collections",
      "Add to cart",
      "See bestsellers",
      "Get support",
    ],
    contentStyle: "clear, conversion-focused, benefit and trust driven",
    designStyle: "E-commerce modern retail",
    designPreset: "modern",
    layoutStyle: "commerce-grid",
    industryPattern: "retail-commerce",
    imageRequirements: [
      "Product hero and lifestyle shots",
      "Collection / category imagery",
      "Detail and packing / unboxing visuals",
      "Trust and lifestyle brand photography",
    ],
    requiredFeatures: [
      "product-catalog",
      "featured-products",
      "cart-cta",
      "trust-badges",
      "faq",
    ],
    preferredSmartTemplateId: "ecommerce-store",
    preferredPremiumTemplateId: "ecommerce",
  },
  agency: {
    id: "agency",
    label: "Agency",
    description:
      "Creative and consulting agency sites with services, work, and lead capture.",
    keywords: [
      "agency",
      "studio",
      "creative",
      "marketing agency",
      "design agency",
      "consultancy",
      "portfolio",
      "clients",
      "campaign",
    ],
    recommendedPages: [
      "Home",
      "Work",
      "Services",
      "About",
      "Insights",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Services",
      "Selected work",
      "Process",
      "Clients",
      "Capabilities",
      "Testimonials",
      "Contact",
    ],
    ctaTypes: [
      "Start a project",
      "View work",
      "Our services",
      "Book a call",
      "Contact the studio",
    ],
    contentStyle: "sharp, creative, confident with proof of craft",
    designStyle: "Agency studio portfolio",
    designPreset: "creative",
    layoutStyle: "studio-portfolio",
    industryPattern: "creative-agency",
    imageRequirements: [
      "Bold portfolio case study visuals",
      "Studio / team atmosphere photography",
      "Process and craft detail imagery",
      "Client brand / campaign stills",
    ],
    requiredFeatures: [
      "portfolio",
      "services",
      "case-studies",
      "lead-form",
      "process",
    ],
    preferredSmartTemplateId: "agency",
    preferredPremiumTemplateId: "agency",
  },
  furniture: {
    id: "furniture",
    label: "Furniture",
    description:
      "Furniture showrooms and home furnishing brands with collections, rooms, and catalog browsing.",
    keywords: [
      "furniture",
      "sofa",
      "bedroom",
      "living room",
      "showroom",
      "home furnish",
      "upholstery",
      "dining table",
      "wardrobe",
      "interior",
      "أثاث",
      "كنب",
      "غرفة نوم",
      "مفروشات",
    ],
    recommendedPages: [
      "Home",
      "Collections",
      "Living Room",
      "Bedroom",
      "Showroom",
      "About",
      "Contact",
    ],
    requiredSections: [
      "Hero showroom",
      "Featured collections",
      "Room inspiration",
      "Product highlights",
      "Craftsmanship",
      "Testimonials",
      "Visit showroom CTA",
      "Contact",
    ],
    ctaTypes: [
      "Browse collections",
      "Visit showroom",
      "Book consultation",
      "View catalog",
      "Contact sales",
    ],
    contentStyle: "warm, tactile, aspirational home living with craftsmanship detail",
    designStyle: "Furniture showroom premium",
    designPreset: "luxury",
    layoutStyle: "commerce-grid",
    industryPattern: "furniture-showroom",
    imageRequirements: [
      "Luxury sofa and living room hero photography",
      "Bedroom set lifestyle shots",
      "Showroom interior wide angles",
      "Material and fabric close-ups",
      "Dining and living room styled scenes",
    ],
    requiredFeatures: [
      "catalog",
      "collections",
      "showroom-cta",
      "gallery",
      "lead-form",
    ],
    preferredSmartTemplateId: "ecommerce-store",
    preferredPremiumTemplateId: "ecommerce",
  },
  technology: {
    id: "technology",
    label: "Technology",
    description:
      "Computer companies, IT services, hardware vendors, and technology consultancies.",
    keywords: [
      "technology",
      "computer",
      "computers",
      "it services",
      "hardware",
      "servers",
      "networking",
      "software house",
      "tech company",
      "data center",
      "تكنولوجيا",
      "حاسوب",
      "حواسيب",
      "شركة تقنية",
    ],
    recommendedPages: [
      "Home",
      "Solutions",
      "Products",
      "Services",
      "About",
      "Support",
      "Contact",
    ],
    requiredSections: [
      "Hero product",
      "Solutions overview",
      "Hardware / software highlights",
      "Enterprise trust",
      "Case studies",
      "Support CTA",
      "Contact",
    ],
    ctaTypes: [
      "Request demo",
      "View solutions",
      "Contact sales",
      "Get support",
      "Explore products",
    ],
    contentStyle: "clear, credible, innovation-forward with enterprise trust",
    designStyle: "Modern technology",
    designPreset: "tech",
    layoutStyle: "product-saas",
    industryPattern: "technology-company",
    imageRequirements: [
      "Modern office with computers and monitors",
      "Server room or data center imagery",
      "Hardware product photography",
      "Team collaborating with technology",
      "Clean workspace hero shots",
    ],
    requiredFeatures: [
      "solutions",
      "products",
      "support-cta",
      "case-studies",
      "lead-form",
    ],
    preferredSmartTemplateId: "saas-growth",
    preferredPremiumTemplateId: "saas",
  },
  law: {
    id: "law",
    label: "Law",
    description:
      "Law firms, attorneys, and legal consultants across corporate, family, and immigration practice areas.",
    keywords: [
      "law",
      "lawyer",
      "attorney",
      "legal",
      "law firm",
      "solicitor",
      "barrister",
      "litigation",
      "corporate law",
      "family law",
      "immigration",
      "legal consultant",
      "counsel",
      "practice areas",
      "court",
      "محاماة",
      "محاماه",
      "محامي",
      "مكتب محاماة",
      "قانوني",
      "استشارات قانونية",
      "القضايا التجارية",
    ],
    recommendedPages: [
      "Home",
      "Practice Areas",
      "Lawyers",
      "Cases",
      "Consultation",
      "About",
      "Testimonials",
      "FAQ",
      "Contact",
      "Office",
    ],
    requiredSections: [
      "Hero",
      "Practice areas",
      "Lawyers",
      "Cases",
      "Consultation",
      "Testimonials",
      "FAQ",
      "Contact",
      "Office",
      "Legal CTA",
    ],
    ctaTypes: [
      "Book consultation",
      "Practice areas",
      "Meet our attorneys",
      "Free case review",
      "Contact our office",
    ],
    contentStyle: "authoritative, precise, reassuring, professional without jargon",
    designStyle: "Legal dark luxury",
    designPreset: "luxury",
    layoutStyle: "legal-trust",
    industryPattern: "legal-services",
    imageRequirements: [
      "Professional law office and courtroom atmosphere",
      "Attorney portrait photography",
      "Legal consultation and client trust imagery",
      "Corporate boardroom and office detail shots",
    ],
    requiredFeatures: [
      "practice-areas",
      "attorney-profiles",
      "case-studies",
      "consultation-booking",
      "contact-form",
      "office-location",
    ],
    preferredSmartTemplateId: "law-firm",
    preferredPremiumTemplateId: "law",
  },
  blog: {
    id: "blog",
    label: "Blog",
    description:
      "Personal, business, news, magazine, and technology blogs with editorial layouts.",
    keywords: [
      "blog",
      "article",
      "articles",
      "news",
      "magazine",
      "editorial",
      "publishing",
      "writer",
      "journalism",
      "technology blog",
      "personal blog",
      "business blog",
      "newsletter",
      "posts",
    ],
    recommendedPages: [
      "Home",
      "Articles",
      "Categories",
      "Authors",
      "About",
      "Newsletter",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Featured articles",
      "Categories",
      "Search",
      "Newsletter",
      "Author",
      "Popular posts",
      "Latest posts",
      "Related posts",
      "Comments",
      "CTA",
    ],
    ctaTypes: [
      "Read latest",
      "Subscribe",
      "Browse categories",
      "Meet the author",
      "Contact",
    ],
    contentStyle: "editorial, readable, engaging, scannable with strong headlines",
    designStyle: "Editorial blog",
    designPreset: "creative",
    layoutStyle: "editorial-blog",
    industryPattern: "editorial-blog",
    imageRequirements: [
      "Editorial hero photography for featured articles",
      "Author portrait and writing workspace imagery",
      "Publishing and magazine layout mood shots",
      "Technology and news desk photography",
    ],
    requiredFeatures: [
      "blog",
      "categories",
      "search",
      "newsletter",
      "author-profiles",
      "comments",
    ],
    preferredSmartTemplateId: "blog-editorial",
    preferredPremiumTemplateId: "blog",
  },
  "landing-page": {
    id: "landing-page",
    label: "Landing Page",
    description:
      "High-conversion landing pages for startups, SaaS, marketing campaigns, and product launches.",
    keywords: [
      "landing page",
      "landing-page",
      "launch",
      "product launch",
      "campaign",
      "marketing",
      "lead generation",
      "lead gen",
      "startup",
      "saas landing",
      "conversion",
      "waitlist",
      "signup",
      "product page",
    ],
    recommendedPages: ["Home"],
    requiredSections: [
      "Hero",
      "Benefits",
      "Features",
      "Statistics",
      "Testimonials",
      "Pricing",
      "FAQ",
      "CTA",
      "Contact",
      "Sticky CTA",
    ],
    ctaTypes: [
      "Get started",
      "Start free trial",
      "Join waitlist",
      "Book a demo",
      "Contact sales",
    ],
    contentStyle: "direct, benefit-led, conversion-focused, minimal navigation",
    designStyle: "Conversion landing",
    designPreset: "modern",
    layoutStyle: "conversion-landing",
    industryPattern: "conversion-landing",
    imageRequirements: [
      "Product hero and startup launch photography",
      "SaaS dashboard and marketing campaign visuals",
      "Team and founder credibility shots",
      "Feature and benefit illustration-friendly imagery",
    ],
    requiredFeatures: [
      "hero-cta",
      "benefits",
      "features",
      "pricing",
      "testimonials",
      "faq",
      "sticky-cta",
      "lead-form",
    ],
    preferredSmartTemplateId: "landing-conversion",
    preferredPremiumTemplateId: "landing-page",
  },
  business: {
    id: "business",
    label: "Luxury Business",
    description:
      "Premium firms, consultancies, and high-end professional brands with editorial luxury presentation.",
    keywords: [
      "business",
      "luxury",
      "premium",
      "company",
      "services",
      "consulting",
      "professional",
      "corporate",
      "executive",
      "private",
      "enterprise",
      "smb",
    ],
    recommendedPages: [
      "Home",
      "Services",
      "About",
      "Insights",
      "Testimonials",
      "Contact",
    ],
    requiredSections: [
      "Hero",
      "Services",
      "Features",
      "Showcase",
      "Testimonials",
      "Team",
      "FAQ",
      "CTA",
      "Contact",
    ],
    ctaTypes: [
      "Request consultation",
      "View services",
      "Read insights",
      "Talk to us",
      "Contact",
    ],
    contentStyle: "refined, confident, concise, exclusive without arrogance",
    designStyle: "Luxury editorial",
    designPreset: "luxury",
    layoutStyle: "corporate-trust",
    industryPattern: "luxury-professional-services",
    imageRequirements: [
      "Cinematic luxury brand atmosphere hero",
      "Premium service lifestyle photography",
      "Editorial detail shots for features",
      "Portfolio-quality brand moments",
    ],
    requiredFeatures: [
      "services",
      "about",
      "testimonials",
      "contact-form",
      "trust-signals",
      "insights",
    ],
    preferredSmartTemplateId: "agency",
    preferredPremiumTemplateId: "luxury-business",
  },
};

export const WEBSITE_INDUSTRY_IDS = Object.keys(
  WEBSITE_INDUSTRY_INTELLIGENCE,
) as IndustryId[];

/** Primary Website Builder verticals called out in product requirements. */
export const PRIMARY_WEBSITE_INDUSTRIES: IndustryId[] = [
  "furniture",
  "technology",
  "gaming",
  "tourism",
  "automotive",
  "real-estate",
  "restaurant",
  "saas",
  "clinic",
  "law",
  "education",
  "blog",
  "landing-page",
  "ecommerce",
  "agency",
];

export function getWebsiteIndustryIntelligence(
  id: IndustryId,
): WebsiteIndustryIntelligence {
  return WEBSITE_INDUSTRY_INTELLIGENCE[id];
}

export function listWebsiteIndustryIntelligence(): WebsiteIndustryIntelligence[] {
  return WEBSITE_INDUSTRY_IDS.map((id) => WEBSITE_INDUSTRY_INTELLIGENCE[id]);
}

export function listPrimaryWebsiteIndustryIntelligence(): WebsiteIndustryIntelligence[] {
  return PRIMARY_WEBSITE_INDUSTRIES.map((id) => WEBSITE_INDUSTRY_INTELLIGENCE[id]);
}
