// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import { BUILDER_DEFAULT_STRUCTURE_TEMPLATE_INTELLIGENCE_ID } from "@/lib/website/builder/template-catalog-mapping";

/** Distinct Template Intelligence profile per premium structure package. */
export const STRUCTURE_TEMPLATE_INTELLIGENCE_MAP: Record<string, string> = {
  "modern-business": "ti-corporate-trust",
  "ai-startup-signal": "ti-ai-company-signal",
};

export function resolveStructureTemplateIntelligenceId(
  templatePackageId: string,
): string {
  const id = templatePackageId.trim();
  return (
    STRUCTURE_TEMPLATE_INTELLIGENCE_MAP[id] ??
    BUILDER_DEFAULT_STRUCTURE_TEMPLATE_INTELLIGENCE_ID
  );
}

export function isKnownStructureTemplatePackage(
  templatePackageId: string,
): boolean {
  return Boolean(
    STRUCTURE_TEMPLATE_INTELLIGENCE_MAP[templatePackageId.trim()],
  );
}
