// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import modern_businessManifest from "@/templates/website/modern-business/manifest.json";
import corporate_businessManifest from "@/templates/website/corporate-business/manifest.json";
import ai_startup_signalManifest from "@/templates/website/ai-startup-signal/manifest.json";
import saas_enterpriseManifest from "@/templates/website/saas-enterprise/manifest.json";
import restaurant_signatureManifest from "@/templates/website/restaurant-signature/manifest.json";
import restaurant_premiumManifest from "@/templates/website/restaurant-premium/manifest.json";
import real_estate_premiumManifest from "@/templates/website/real-estate-premium/manifest.json";
import real_estate_prestigeManifest from "@/templates/website/real-estate-prestige/manifest.json";
import medical_premiumManifest from "@/templates/website/medical-premium/manifest.json";
import creative_agency_premiumManifest from "@/templates/website/creative-agency-premium/manifest.json";
import creative_portfolioManifest from "@/templates/website/creative-portfolio/manifest.json";
import hotel_resort_premiumManifest from "@/templates/website/hotel-resort-premium/manifest.json";
import finance_premiumManifest from "@/templates/website/finance-premium/manifest.json";
import education_premiumManifest from "@/templates/website/education-premium/manifest.json";
import ecommerce_premiumManifest from "@/templates/website/ecommerce-premium/manifest.json";

import { mapPackageManifestToStructureTemplate } from "@/lib/website/builder/template-catalog-mapping";
import type { WebsiteStructureTemplate } from "@/lib/website/builder/structure-templates";

/** Sync index of installed template packages (includes 3 flagship V2 templates). */
export const WEBSITE_STRUCTURE_TEMPLATES: WebsiteStructureTemplate[] = [
  mapPackageManifestToStructureTemplate(corporate_businessManifest),
  mapPackageManifestToStructureTemplate(saas_enterpriseManifest),
  mapPackageManifestToStructureTemplate(restaurant_premiumManifest),
  mapPackageManifestToStructureTemplate(modern_businessManifest),
  mapPackageManifestToStructureTemplate(ai_startup_signalManifest),
  mapPackageManifestToStructureTemplate(restaurant_signatureManifest),
  mapPackageManifestToStructureTemplate(real_estate_premiumManifest),
  mapPackageManifestToStructureTemplate(real_estate_prestigeManifest),
  mapPackageManifestToStructureTemplate(medical_premiumManifest),
  mapPackageManifestToStructureTemplate(creative_agency_premiumManifest),
  mapPackageManifestToStructureTemplate(creative_portfolioManifest),
  mapPackageManifestToStructureTemplate(ecommerce_premiumManifest),
  mapPackageManifestToStructureTemplate(education_premiumManifest),
  mapPackageManifestToStructureTemplate(finance_premiumManifest),
  mapPackageManifestToStructureTemplate(hotel_resort_premiumManifest),
];

export const WEBSITE_STRUCTURE_TEMPLATE_INDEX: Record<string, WebsiteStructureTemplate> =
  Object.fromEntries(WEBSITE_STRUCTURE_TEMPLATES.map((template) => [template.id, template]));
