// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import modern_businessManifest from "@/templates/website/modern-business/manifest.json";
import enterprise_scaleManifest from "@/templates/website/enterprise-scale/manifest.json";
import saas_starterManifest from "@/templates/website/saas-starter/manifest.json";
import ai_startup_signalManifest from "@/templates/website/ai-startup-signal/manifest.json";
import agency_portfolioManifest from "@/templates/website/agency-portfolio/manifest.json";
import marketing_agency_growthManifest from "@/templates/website/marketing-agency-growth/manifest.json";
import portfolio_showcaseManifest from "@/templates/website/portfolio-showcase/manifest.json";
import restaurant_bistroManifest from "@/templates/website/restaurant-bistro/manifest.json";
import cafe_artisanManifest from "@/templates/website/cafe-artisan/manifest.json";
import hotel_sanctuaryManifest from "@/templates/website/hotel-sanctuary/manifest.json";
import travel_horizonManifest from "@/templates/website/travel-horizon/manifest.json";
import real_estate_listingsManifest from "@/templates/website/real-estate-listings/manifest.json";
import architecture_monographManifest from "@/templates/website/architecture-monograph/manifest.json";
import construction_buildManifest from "@/templates/website/construction-build/manifest.json";
import medical_care_plusManifest from "@/templates/website/medical-care-plus/manifest.json";
import dental_smileManifest from "@/templates/website/dental-smile/manifest.json";
import pharmacy_wellnessManifest from "@/templates/website/pharmacy-wellness/manifest.json";
import law_firm_authorityManifest from "@/templates/website/law-firm-authority/manifest.json";
import finance_ledger_proManifest from "@/templates/website/finance-ledger-pro/manifest.json";
import insurance_shieldManifest from "@/templates/website/insurance-shield/manifest.json";
import education_academyManifest from "@/templates/website/education-academy/manifest.json";
import university_heritageManifest from "@/templates/website/university-heritage/manifest.json";
import ecommerce_atelierManifest from "@/templates/website/ecommerce-atelier/manifest.json";
import fashion_runwayManifest from "@/templates/website/fashion-runway/manifest.json";
import beauty_glowManifest from "@/templates/website/beauty-glow/manifest.json";
import fitness_pulseManifest from "@/templates/website/fitness-pulse/manifest.json";
import automotive_showroomManifest from "@/templates/website/automotive-showroom/manifest.json";
import logistics_freightManifest from "@/templates/website/logistics-freight/manifest.json";
import manufacturing_precisionManifest from "@/templates/website/manufacturing-precision/manifest.json";
import nonprofit_impactManifest from "@/templates/website/nonprofit-impact/manifest.json";

import { mapPackageManifestToStructureTemplate } from "@/lib/website/builder/template-catalog-mapping";
import type { WebsiteStructureTemplate } from "@/lib/website/builder/structure-templates";

/** Sync index of 30 premium installed template packages. */
export const WEBSITE_STRUCTURE_TEMPLATES: WebsiteStructureTemplate[] = [
  mapPackageManifestToStructureTemplate(modern_businessManifest),
  mapPackageManifestToStructureTemplate(enterprise_scaleManifest),
  mapPackageManifestToStructureTemplate(saas_starterManifest),
  mapPackageManifestToStructureTemplate(ai_startup_signalManifest),
  mapPackageManifestToStructureTemplate(agency_portfolioManifest),
  mapPackageManifestToStructureTemplate(marketing_agency_growthManifest),
  mapPackageManifestToStructureTemplate(portfolio_showcaseManifest),
  mapPackageManifestToStructureTemplate(restaurant_bistroManifest),
  mapPackageManifestToStructureTemplate(cafe_artisanManifest),
  mapPackageManifestToStructureTemplate(hotel_sanctuaryManifest),
  mapPackageManifestToStructureTemplate(travel_horizonManifest),
  mapPackageManifestToStructureTemplate(real_estate_listingsManifest),
  mapPackageManifestToStructureTemplate(architecture_monographManifest),
  mapPackageManifestToStructureTemplate(construction_buildManifest),
  mapPackageManifestToStructureTemplate(medical_care_plusManifest),
  mapPackageManifestToStructureTemplate(dental_smileManifest),
  mapPackageManifestToStructureTemplate(pharmacy_wellnessManifest),
  mapPackageManifestToStructureTemplate(law_firm_authorityManifest),
  mapPackageManifestToStructureTemplate(finance_ledger_proManifest),
  mapPackageManifestToStructureTemplate(insurance_shieldManifest),
  mapPackageManifestToStructureTemplate(education_academyManifest),
  mapPackageManifestToStructureTemplate(university_heritageManifest),
  mapPackageManifestToStructureTemplate(ecommerce_atelierManifest),
  mapPackageManifestToStructureTemplate(fashion_runwayManifest),
  mapPackageManifestToStructureTemplate(beauty_glowManifest),
  mapPackageManifestToStructureTemplate(fitness_pulseManifest),
  mapPackageManifestToStructureTemplate(automotive_showroomManifest),
  mapPackageManifestToStructureTemplate(logistics_freightManifest),
  mapPackageManifestToStructureTemplate(manufacturing_precisionManifest),
  mapPackageManifestToStructureTemplate(nonprofit_impactManifest),
];

export const WEBSITE_STRUCTURE_TEMPLATE_INDEX: Record<string, WebsiteStructureTemplate> =
  Object.fromEntries(WEBSITE_STRUCTURE_TEMPLATES.map((template) => [template.id, template]));
