// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import modern_businessManifest from "@/templates/website/modern-business/manifest.json";
import ai_startup_signalManifest from "@/templates/website/ai-startup-signal/manifest.json";

import { mapPackageManifestToStructureTemplate } from "@/lib/website/builder/template-catalog-mapping";
import type { WebsiteStructureTemplate } from "@/lib/website/builder/structure-templates";

/** Sync index of 2 premium installed template packages. */
export const WEBSITE_STRUCTURE_TEMPLATES: WebsiteStructureTemplate[] = [
  mapPackageManifestToStructureTemplate(modern_businessManifest),
  mapPackageManifestToStructureTemplate(ai_startup_signalManifest),
];

export const WEBSITE_STRUCTURE_TEMPLATE_INDEX: Record<string, WebsiteStructureTemplate> =
  Object.fromEntries(WEBSITE_STRUCTURE_TEMPLATES.map((template) => [template.id, template]));
