// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import { BUILDER_DEFAULT_STRUCTURE_TEMPLATE_INTELLIGENCE_ID } from "@/lib/website/builder/template-catalog-mapping";

/** Distinct Template Intelligence profile per premium structure package. */
export const STRUCTURE_TEMPLATE_INTELLIGENCE_MAP: Record<string, string> = {
  "modern-business": "ti-corporate-trust",
  "enterprise-scale": "ti-consulting-clarity",
  "saas-starter": "ti-saas-growth",
  "ai-startup-signal": "ti-ai-company-signal",
  "agency-portfolio": "ti-creative-studio",
  "marketing-agency-growth": "ti-agency-portfolio",
  "portfolio-showcase": "ti-blog-editorial",
  "restaurant-bistro": "ti-restaurant-dining",
  "cafe-artisan": "ti-cafe-artisan",
  "hotel-sanctuary": "ti-hotel-sanctuary",
  "travel-horizon": "ti-travel-horizon",
  "real-estate-listings": "ti-real-estate-listings",
  "architecture-monograph": "ti-architecture-monograph",
  "construction-build": "ti-construction-industrial",
  "medical-care-plus": "ti-medical-care",
  "dental-smile": "ti-dental-smile",
  "pharmacy-wellness": "ti-pharmacy-wellness",
  "law-firm-authority": "ti-law-firm",
  "finance-ledger-pro": "ti-finance-ledger",
  "insurance-shield": "ti-insurance-shield",
  "education-academy": "ti-education-campus",
  "university-heritage": "ti-university-heritage",
  "ecommerce-atelier": "ti-ecommerce-atelier",
  "fashion-runway": "ti-luxury-brands-atelier",
  "beauty-glow": "ti-beauty-glow",
  "fitness-pulse": "ti-fitness-pulse",
  "automotive-showroom": "ti-automotive-showroom",
  "logistics-freight": "ti-logistics-freight",
  "manufacturing-precision": "ti-manufacturing-precision",
  "nonprofit-impact": "ti-nonprofit-impact",
};

export function resolveStructureTemplateIntelligenceId(
  templatePackageId: string,
): string {
  const id = templatePackageId.trim();
  return (
    STRUCTURE_TEMPLATE_INTELLIGENCE_MAP[id] ??
    BUILDER_DEFAULT_STRUCTURE_TEMPLATE_INTELLIGENCE_ID
  );
}

export function isKnownStructureTemplatePackage(
  templatePackageId: string,
): boolean {
  return Boolean(
    STRUCTURE_TEMPLATE_INTELLIGENCE_MAP[templatePackageId.trim()],
  );
}
