// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import { BUILDER_DEFAULT_STRUCTURE_TEMPLATE_INTELLIGENCE_ID } from "@/lib/website/builder/template-catalog-mapping";

/** No installed structure packages — TI profiles resolve via builder default. */
export const STRUCTURE_TEMPLATE_INTELLIGENCE_MAP: Record<string, string> = {};

export function resolveStructureTemplateIntelligenceId(
  templatePackageId: string,
): string {
  const id = templatePackageId.trim();
  if (id.startsWith("ti-")) {
    return id;
  }
  return (
    STRUCTURE_TEMPLATE_INTELLIGENCE_MAP[id] ??
    BUILDER_DEFAULT_STRUCTURE_TEMPLATE_INTELLIGENCE_ID
  );
}

export function isKnownStructureTemplatePackage(
  templatePackageId: string,
): boolean {
  const id = templatePackageId.trim();
  if (id.startsWith("ti-")) {
    return true;
  }
  return Boolean(STRUCTURE_TEMPLATE_INTELLIGENCE_MAP[id]);
}
