import Link from "next/link";
import {
  ArrowRight,
  Lightbulb,
  LineChart,
  FileText,
  Sparkles,
  Globe,
  Clock3,
  Star,
  type LucideIcon,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { DASHBOARD_NAV } from "@/lib/constants/dashboard-nav";
import { DashboardStatCard } from "@/components/dashboard/ui/dashboard-stat-card";
import { DashboardPanel } from "@/components/dashboard/ui/dashboard-card";
import { DashboardIconBox } from "@/components/dashboard/ui/icon-box";
import { DashboardEmptyState } from "@/components/dashboard/ui/dashboard-empty-state";
import type { DashboardActivityItem, DashboardHomeData } from "@/types/database";

const QUICK_ACTIONS = [
  {
    title: "Generate Ideas",
    description: "Create business concepts tailored to your skills, interests, and budget.",
    href: "/dashboard/ideas",
    icon: Lightbulb,
    cta: "Generate ideas",
  },
  {
    title: "Analyze Market",
    description: "Research market size, competitors, risks, and opportunity signals.",
    href: "/dashboard/market-analysis",
    icon: LineChart,
    cta: "Run analysis",
  },
  {
    title: "Create Report",
    description: "Turn a topic into a strategic report you can export as MD or PDF.",
    href: "/dashboard/reports",
    icon: FileText,
    cta: "Create report",
  },
  {
    title: "Plan Website",
    description: "Generate a blueprint with pages, components, colors, typography, and SEO.",
    href: "/dashboard/website-builder",
    icon: Globe,
    cta: "Plan website",
  },
] as const;

type DashboardOverviewProps = {
  data: DashboardHomeData;
};

const ACTIVITY_ICONS: Record<DashboardActivityItem["type"], LucideIcon> = {
  idea: Lightbulb,
  analysis: LineChart,
  report: FileText,
  website: Globe,
};

function formatActivityDate(value: string) {
  return new Intl.DateTimeFormat(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(value));
}

export function DashboardOverview({ data }: DashboardOverviewProps) {
  const { stats, recentActivity } = data;
  const totalAssets = stats.ideas + stats.analyses + stats.reports + stats.websites;
  const hasActivity = recentActivity.length > 0;
  const statItems = [
    {
      label: "Ideas Generated",
      value: stats.ideas,
      change: "All time",
      description: "Business concepts saved in your workspace.",
      icon: Lightbulb,
    },
    {
      label: "Market Analyses",
      value: stats.analyses,
      change: "All time",
      description: "Industry and opportunity research runs.",
      icon: LineChart,
    },
    {
      label: "AI Reports",
      value: stats.reports,
      change: "All time",
      description: "Strategic reports available for export.",
      icon: FileText,
    },
    {
      label: "Website Blueprints",
      value: stats.websites,
      change: "Beta",
      description: "Website plans generated by the builder.",
      icon: Globe,
    },
  ] as const;

  return (
    <div className="space-y-8 lg:space-y-10">
      <DashboardPanel gold className="relative overflow-hidden">
        <div
          className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_0%_0%,rgb(255_215_0_/_0.1),transparent_55%)]"
          aria-hidden="true"
        />
        <div className="relative flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-premium-gold/25 bg-premium-gold/10 px-3 py-1">
              <Sparkles className="size-3.5 text-premium-gold-light" />
              <span className="text-[11px] font-semibold tracking-wide text-premium-gold-light uppercase">
                Welcome back
              </span>
            </div>
            <h2 className="text-xl font-bold tracking-tight text-white sm:text-2xl">
              Your AI command center
            </h2>
            <p className="mt-2 max-w-xl text-[14px] leading-relaxed text-white/50 sm:text-[15px]">
              Track your business ideas, market analyses, strategic reports,
              and website blueprints from one private workspace.
            </p>
          </div>
          <Button className="btn-gold h-11 shrink-0 rounded-xl px-6 font-bold text-luxury-black" asChild>
            <Link href={totalAssets > 0 ? "/dashboard/reports" : "/dashboard/ideas"}>
              {totalAssets > 0 ? "Create next asset" : "Start generating"}
              <ArrowRight className="ml-1 size-4" />
            </Link>
          </Button>
        </div>
      </DashboardPanel>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {statItems.map((stat) => (
          <DashboardStatCard key={stat.label} {...stat} />
        ))}
      </div>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(320px,0.9fr)]">
        <DashboardPanel>
          <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-3">
              <DashboardIconBox icon={Clock3} />
              <div>
                <h3 className="font-bold text-white">Recent Activity</h3>
                <p className="text-[13px] text-white/40">
                  Latest assets saved in your dashboard
                </p>
              </div>
            </div>
            {hasActivity && (
              <span className="rounded-full bg-premium-gold/10 px-2.5 py-1 text-[11px] font-semibold text-premium-gold-light ring-1 ring-premium-gold/20">
                {recentActivity.length} recent
              </span>
            )}
          </div>

          {hasActivity ? (
            <div className="space-y-2.5">
              {recentActivity.map((item) => {
                const Icon = ACTIVITY_ICONS[item.type];

                return (
                  <Link
                    key={`${item.type}-${item.id}`}
                    href={item.href}
                    className="group flex items-center gap-3 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-3 transition-all hover:border-premium-gold/25 hover:bg-premium-gold/[0.04]"
                  >
                    <DashboardIconBox icon={Icon} className="size-9" gold={false} />
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-semibold text-white transition-colors group-hover:text-premium-gold-light">
                        {item.title}
                      </p>
                      <p className="truncate text-[12px] text-white/40">
                        {item.description}
                      </p>
                    </div>
                    <span className="hidden shrink-0 text-[11px] text-white/30 sm:inline">
                      {formatActivityDate(item.createdAt)}
                    </span>
                    <ArrowRight className="size-4 shrink-0 text-white/20 transition-all group-hover:translate-x-0.5 group-hover:text-premium-gold" />
                  </Link>
                );
              })}
            </div>
          ) : (
            <DashboardEmptyState
              icon={Sparkles}
              title="No activity yet"
              description="Generate your first idea, market analysis, report, or website blueprint to start building your workspace history."
              className="py-12 sm:py-14"
            />
          )}
        </DashboardPanel>

        <DashboardPanel>
          <div className="mb-5 flex items-center gap-3">
            <DashboardIconBox icon={Star} />
            <div>
              <h3 className="font-bold text-white">Workspace Summary</h3>
              <p className="text-[13px] text-white/40">
                Real totals from your saved data
              </p>
            </div>
          </div>
          <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-1">
            <SummaryRow label="Total assets" value={totalAssets} />
            <SummaryRow label="Favorites" value={stats.saved} />
            <SummaryRow
              label="Next best action"
              value={totalAssets > 0 ? "Create report" : "Generate idea"}
              href={totalAssets > 0 ? "/dashboard/reports" : "/dashboard/ideas"}
            />
          </div>
        </DashboardPanel>
      </div>

      <div>
        <h2 className="mb-5 text-lg font-bold text-white sm:text-xl">Quick Actions</h2>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {QUICK_ACTIONS.map((action) => (
            <QuickActionCard key={action.href} {...action} />
          ))}
        </div>
      </div>

      <div>
        <h2 className="mb-5 text-lg font-bold text-white sm:text-xl">All Tools</h2>
        <div className="grid gap-3 sm:grid-cols-2">
          {DASHBOARD_NAV.filter((item) => item.href !== "/dashboard").map(
            (item) => (
              <Link
                key={item.href}
                href={item.href}
                className="group flex items-center gap-4 rounded-2xl border border-white/[0.08] glass-panel p-4 transition-all duration-300 hover:border-premium-gold/25 hover:shadow-gold-sm sm:p-5"
              >
                <DashboardIconBox icon={item.icon} />
                <div className="min-w-0 flex-1">
                  <p className="font-semibold text-white transition-colors group-hover:text-premium-gold-light">
                    {item.label}
                  </p>
                  <p className="truncate text-[13px] text-white/40">
                    {item.description}
                  </p>
                </div>
                <ArrowRight className="size-4 shrink-0 text-white/25 transition-all group-hover:translate-x-0.5 group-hover:text-premium-gold" />
              </Link>
            ),
          )}
        </div>
      </div>
    </div>
  );
}

function QuickActionCard({
  title,
  description,
  href,
  icon,
  cta,
}: {
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  cta: string;
}) {
  return (
    <div className="group flex h-full flex-col rounded-2xl border border-white/[0.08] glass-panel glass-panel-premium p-5 transition-all duration-300 hover:border-premium-gold/25 hover:shadow-gold-sm sm:p-6">
      <div className="mb-4 flex items-start justify-between">
        <DashboardIconBox icon={icon} />
        <Button
          variant="ghost"
          size="icon-sm"
          className="text-white/40 hover:text-premium-gold-light"
          asChild
        >
          <Link href={href} aria-label={title}>
            <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
          </Link>
        </Button>
      </div>
      <h3 className="font-bold text-white">{title}</h3>
      <p className="mt-2 flex-1 text-[14px] leading-relaxed text-white/45">
        {description}
      </p>
      <Button
        variant="outline"
        className="btn-ghost-gold mt-5 w-full rounded-xl"
        asChild
      >
        <Link href={href}>{cta}</Link>
      </Button>
    </div>
  );
}

function SummaryRow({
  label,
  value,
  href,
}: {
  label: string;
  value: number | string;
  href?: string;
}) {
  const content = (
    <div className="rounded-2xl border border-white/[0.08] bg-black/20 p-4 transition-all hover:border-premium-gold/20">
      <p className="text-[12px] font-medium text-white/40">{label}</p>
      <p className="mt-1 truncate text-lg font-bold text-white">{value}</p>
    </div>
  );

  if (!href) {
    return content;
  }

  return (
    <Link href={href} className="block">
      {content}
    </Link>
  );
}
