import type {
  CoreAssetItem,
  CoreAssetManifest,
  CoreAssetRole,
} from "@/lib/ai-core/layers/types";

export type AssetKind =
  | "realistic"
  | "hero"
  | "product"
  | "service"
  | "background"
  | "brand"
  | "section"
  | "icon";

export type CoreAssetPlanItem = {
  id: string;
  kind: AssetKind;
  role: CoreAssetRole;
  name: string;
  prompt: string;
  alt: string;
  /** Prefer photorealistic generation when provider available */
  realistic?: boolean;
};

export type GenerateCoreAssetsParams = {
  items: CoreAssetPlanItem[];
  /** Brand colors for prompt + SVG fallback */
  colors: { primary: string; secondary: string };
  userId?: string;
  generationKey?: string;
  websiteGenerationId?: string;
  aiRunId?: string;
  maxImages?: number;
  imageSettings?: import("@/lib/ai-core/assets/settings").ImageGenerationSettings;
  negativePrompt?: string;
  /** Persist rows to image_prompts / generated_images / image_assets when true. */
  persist?: boolean;
  /**
   * Optional storage upload. When omitted, generated bytes become data URLs.
   * Website Builder passes its existing website-assets uploader.
   */
  upload?: (params: {
    assetId: string;
    bytes: Buffer;
    contentType: string;
  }) => Promise<{ publicUrl: string; storagePath: string } | null>;
  onProgress?: (message: string) => void;
};

export type { CoreAssetItem, CoreAssetManifest, CoreAssetRole };
