import type { GcriHourCycle, GcriMeasurementSystem, GcriProfile } from "@/lib/language-platform/gcri/types";

type GcriCatalogRow = {
  countryCode: string;
  countryName: string;
  region: string;
  subregion: string;
  language: string;
  languageVariant: string;
  locale: string;
  currencyCode: string;
  currencyName: string;
  dateFormat: string;
  hourCycle?: GcriHourCycle;
  measurementSystem?: GcriMeasurementSystem;
  decimal?: string;
  group?: string;
  timezone: string;
  culturalNotes: string;
  marketingStyle: string;
  ctaStyle: string;
  businessStyle: string;
};

function numberExample(group: string, decimal: string): string {
  return `1${group}234${decimal}56`;
}

function timeFormatFor(cycle: GcriHourCycle): string {
  return cycle === "h12" ? "h:mm a" : "HH:mm";
}

function toProfile(row: GcriCatalogRow): GcriProfile {
  const hourCycle = row.hourCycle ?? "h23";
  const decimal = row.decimal ?? ".";
  const group = row.group ?? ",";
  return {
    countryCode: row.countryCode,
    countryName: row.countryName,
    region: row.region,
    subregion: row.subregion,
    language: row.language,
    languageVariant: row.languageVariant,
    locale: row.locale,
    currencyCode: row.currencyCode,
    currencyName: row.currencyName,
    dateFormat: row.dateFormat,
    timeFormat: timeFormatFor(hourCycle),
    hourCycle,
    measurementSystem: row.measurementSystem ?? "metric",
    numberFormat: {
      decimal,
      group,
      example: numberExample(group, decimal),
    },
    timezone: row.timezone,
    culturalNotes: row.culturalNotes,
    marketingStyle: row.marketingStyle,
    ctaStyle: row.ctaStyle,
    businessStyle: row.businessStyle,
    seoLocale: row.locale.toLowerCase(),
  };
}

const ROWS: GcriCatalogRow[] = [
  {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    region: "Middle East",
    subregion: "Arabian Peninsula",
    language: "Arabic",
    languageVariant: "Saudi Arabic (Modern Standard Arabic with Saudi market phrasing)",
    locale: "ar-SA",
    currencyCode: "SAR",
    currencyName: "Saudi Riyal",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Riyadh",
    culturalNotes:
      "Respectful, modest, family- and trust-oriented. Avoid alcohol, gambling, and overly casual Western slang. Weekend is Friday–Saturday.",
    marketingStyle:
      "Trust-led, premium, and relationship-based. Emphasize credibility, hospitality, and Vision 2030-aligned modernity without hype.",
    ctaStyle:
      "Direct but courteous CTAs (اطلب الآن، تواصل معنا، احجز استشارتك). Formal enough for business, clear on next step.",
    businessStyle:
      "Executive Arabic with clear recommendations, local market context, and SAR figures.",
  },
  {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    region: "Middle East",
    subregion: "Gulf",
    language: "Arabic",
    languageVariant: "UAE Arabic (Modern Standard Arabic with Gulf business phrasing)",
    locale: "ar-AE",
    currencyCode: "AED",
    currencyName: "UAE Dirham",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Dubai",
    culturalNotes: "International, ambitious, luxury-comfortable. Mix of Arabic formality and global business energy.",
    marketingStyle: "Premium, cosmopolitan, results-oriented. Highlight quality, speed, and regional hub status.",
    ctaStyle: "Confident CTAs with AED pricing and clear booking/contact actions.",
    businessStyle: "Polished Gulf corporate Arabic with AED and UAE regulatory awareness.",
  },
  {
    countryCode: "EG",
    countryName: "Egypt",
    region: "Middle East",
    subregion: "North Africa",
    language: "Arabic",
    languageVariant: "Egyptian Arabic-informed MSA for professional output",
    locale: "ar-EG",
    currencyCode: "EGP",
    currencyName: "Egyptian Pound",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Africa/Cairo",
    culturalNotes: "Warm, expressive, community-oriented. Professional copy stays MSA; avoid Gulf-only phrasing.",
    marketingStyle: "Accessible, story-driven, value-conscious with local social proof.",
    ctaStyle: "Friendly but professional CTAs with EGP pricing.",
    businessStyle: "Clear Egyptian market framing, EGP, and practical next steps.",
  },
  {
    countryCode: "QA",
    countryName: "Qatar",
    region: "Middle East",
    subregion: "Gulf",
    language: "Arabic",
    languageVariant: "Qatari Arabic-informed MSA",
    locale: "ar-QA",
    currencyCode: "QAR",
    currencyName: "Qatari Riyal",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Qatar",
    culturalNotes: "Formal, prestige-aware, nationally proud. Conservative visual and verbal tone.",
    marketingStyle: "Luxury-trust hybrid; national quality and long-term partnership.",
    ctaStyle: "Formal CTAs with QAR.",
    businessStyle: "Board-ready Arabic with QAR and Qatari context.",
  },
  {
    countryCode: "KW",
    countryName: "Kuwait",
    region: "Middle East",
    subregion: "Gulf",
    language: "Arabic",
    languageVariant: "Kuwaiti Arabic-informed MSA",
    locale: "ar-KW",
    currencyCode: "KWD",
    currencyName: "Kuwaiti Dinar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Kuwait",
    culturalNotes: "Direct Gulf business culture; high purchasing power; formal Arabic in professional copy.",
    marketingStyle: "Premium, concise, credibility-first.",
    ctaStyle: "Clear KWD CTAs.",
    businessStyle: "Executive Arabic with KWD figures.",
  },
  {
    countryCode: "BH",
    countryName: "Bahrain",
    region: "Middle East",
    subregion: "Gulf",
    language: "Arabic",
    languageVariant: "Bahraini Arabic-informed MSA",
    locale: "ar-BH",
    currencyCode: "BHD",
    currencyName: "Bahraini Dinar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Bahrain",
    culturalNotes: "Open, finance-aware Gulf market; professional MSA.",
    marketingStyle: "Professional, compact, finance- and service-friendly.",
    ctaStyle: "BHD-priced CTAs.",
    businessStyle: "Corporate Arabic with BHD.",
  },
  {
    countryCode: "OM",
    countryName: "Oman",
    region: "Middle East",
    subregion: "Arabian Peninsula",
    language: "Arabic",
    languageVariant: "Omani Arabic-informed MSA",
    locale: "ar-OM",
    currencyCode: "OMR",
    currencyName: "Omani Rial",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Muscat",
    culturalNotes: "Courteous, heritage-aware, unhurried professionalism.",
    marketingStyle: "Warm authority; heritage plus modern service.",
    ctaStyle: "Polite OMR CTAs.",
    businessStyle: "Respectful executive Arabic with OMR.",
  },
  {
    countryCode: "JO",
    countryName: "Jordan",
    region: "Middle East",
    subregion: "Levant",
    language: "Arabic",
    languageVariant: "Levantine-informed MSA for Jordan",
    locale: "ar-JO",
    currencyCode: "JOD",
    currencyName: "Jordanian Dinar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Amman",
    culturalNotes: "Educated, service-oriented, Levantine professionalism. Not Gulf phrasing.",
    marketingStyle: "Clear value, education, and trust.",
    ctaStyle: "JOD CTAs, practical next steps.",
    businessStyle: "Levantine business Arabic with JOD.",
  },
  {
    countryCode: "MA",
    countryName: "Morocco",
    region: "Africa",
    subregion: "North Africa",
    language: "Arabic",
    languageVariant: "Moroccan-informed MSA (not Gulf Arabic)",
    locale: "ar-MA",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    timezone: "Africa/Casablanca",
    culturalNotes: "Maghreb market; avoid Gulf idioms. French loanwords only if natural in the brief.",
    marketingStyle: "Warm, practical, locally grounded.",
    ctaStyle: "MAD CTAs.",
    businessStyle: "Maghreb professional Arabic with MAD.",
  },
  {
    countryCode: "IQ",
    countryName: "Iraq",
    region: "Middle East",
    subregion: "Mesopotamia",
    language: "Arabic",
    languageVariant: "Iraqi-informed MSA",
    locale: "ar-IQ",
    currencyCode: "IQD",
    currencyName: "Iraqi Dinar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Baghdad",
    culturalNotes: "Direct, dignity-focused, locally specific. Avoid Gulf-only terms.",
    marketingStyle: "Practical trust and service reliability.",
    ctaStyle: "IQD CTAs.",
    businessStyle: "Straightforward Arabic with IQD.",
  },
  {
    countryCode: "US",
    countryName: "United States",
    region: "Americas",
    subregion: "North America",
    language: "English",
    languageVariant: "American English",
    locale: "en-US",
    currencyCode: "USD",
    currencyName: "US Dollar",
    dateFormat: "MM/dd/yyyy",
    hourCycle: "h12",
    measurementSystem: "imperial",
    timezone: "America/New_York",
    culturalNotes: "Direct, optimistic, outcome-led. Use American spelling (color, organize, center).",
    marketingStyle: "Benefit-first US SEO and ads. Short headlines, social proof, urgency without hype clichés.",
    ctaStyle: "Get started, Book a demo, Shop now — USD pricing.",
    businessStyle: "US executive English, USD, imperial units, US market references.",
  },
  {
    countryCode: "GB",
    countryName: "United Kingdom",
    region: "Europe",
    subregion: "Northern Europe",
    language: "English",
    languageVariant: "British English",
    locale: "en-GB",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    timezone: "Europe/London",
    culturalNotes: "Understated, precise. British spelling (colour, organise, centre). Do not use Americanisms.",
    marketingStyle: "Credible, dry-witty only if on-brand, compliance-aware.",
    ctaStyle: "Get in touch, Request a quote — GBP.",
    businessStyle: "UK business English with GBP and metric units.",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    region: "Oceania",
    subregion: "Australia",
    language: "English",
    languageVariant: "Australian English",
    locale: "en-AU",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Australia/Sydney",
    culturalNotes: "Straightforward, informal-professional. Australian spelling (organise, colour).",
    marketingStyle: "Clear, friendly, no US holiday or tax assumptions.",
    ctaStyle: "Get started — AUD.",
    businessStyle: "Australian business English with AUD.",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    region: "Americas",
    subregion: "North America",
    language: "English",
    languageVariant: "Canadian English",
    locale: "en-CA",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    dateFormat: "yyyy-MM-dd",
    hourCycle: "h12",
    timezone: "America/Toronto",
    culturalNotes: "Polite, bilingual-aware, Canadian spelling (colour, centre). Never USD.",
    marketingStyle: "Inclusive, compliance-aware, Canadian terminology (postal code, GST/HST when relevant).",
    ctaStyle: "Get started — CAD.",
    businessStyle: "Canadian business English with CAD and metric units.",
  },
  {
    countryCode: "IE",
    countryName: "Ireland",
    region: "Europe",
    subregion: "Northern Europe",
    language: "English",
    languageVariant: "Irish English",
    locale: "en-IE",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    timezone: "Europe/Dublin",
    culturalNotes: "Warm, EU-aware, British-leaning spelling. Euro not sterling.",
    marketingStyle: "Approachable professional, Irish/EU context.",
    ctaStyle: "Get in touch — EUR.",
    businessStyle: "Irish business English with EUR.",
  },
  {
    countryCode: "NZ",
    countryName: "New Zealand",
    region: "Oceania",
    subregion: "New Zealand",
    language: "English",
    languageVariant: "New Zealand English",
    locale: "en-NZ",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Pacific/Auckland",
    culturalNotes: "Plain, practical, British-leaning spelling.",
    marketingStyle: "Direct and local; NZD only.",
    ctaStyle: "Get started — NZD.",
    businessStyle: "NZ business English with NZD.",
  },
  {
    countryCode: "SG",
    countryName: "Singapore",
    region: "Asia",
    subregion: "Southeast Asia",
    language: "English",
    languageVariant: "Singapore English (professional international English)",
    locale: "en-SG",
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    timezone: "Asia/Singapore",
    culturalNotes: "Concise, multicultural, highly professional. Avoid Singlish in formal copy.",
    marketingStyle: "Efficient, trust and quality, APAC hub framing.",
    ctaStyle: "Get started — SGD.",
    businessStyle: "Singapore business English with SGD.",
  },
  {
    countryCode: "IN",
    countryName: "India",
    region: "Asia",
    subregion: "South Asia",
    language: "English",
    languageVariant: "Indian English",
    locale: "en-IN",
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Kolkata",
    culturalNotes: "Formal-professional, respectful. Lakh/crore only when natural for finance copy.",
    marketingStyle: "Value, trust, scale; INR not USD.",
    ctaStyle: "Get started — INR.",
    businessStyle: "Indian business English with INR.",
  },
  {
    countryCode: "ZA",
    countryName: "South Africa",
    region: "Africa",
    subregion: "Southern Africa",
    language: "English",
    languageVariant: "South African English",
    locale: "en-ZA",
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    dateFormat: "yyyy/MM/dd",
    hourCycle: "h23",
    timezone: "Africa/Johannesburg",
    culturalNotes: "Professional, inclusive, British-leaning spelling.",
    marketingStyle: "Practical value, local proof, ZAR.",
    ctaStyle: "Get in touch — ZAR.",
    businessStyle: "South African business English with ZAR.",
  },
  {
    countryCode: "FR",
    countryName: "France",
    region: "Europe",
    subregion: "Western Europe",
    language: "French",
    languageVariant: "France French",
    locale: "fr-FR",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Paris",
    culturalNotes: "Formal vous by default in business. France terminology (not Canadian). Metric, EUR.",
    marketingStyle: "Elegant, precise, benefit + proof. Avoid Anglicisms unless the brief is tech-native.",
    ctaStyle: "Demander un devis, Commencer — EUR.",
    businessStyle: "French corporate register with EUR and metric units.",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    region: "Americas",
    subregion: "North America",
    language: "French",
    languageVariant: "Canadian French",
    locale: "fr-CA",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    dateFormat: "yyyy-MM-dd",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "America/Toronto",
    culturalNotes:
      "Canadian French terminology (courriel, fin de semaine, magasinage). Never France-only terms when a Canadian equivalent exists. Never EUR or USD.",
    marketingStyle: "Clear, inclusive, Quebec/Canada business norms. CAD pricing.",
    ctaStyle: "Commencer, Nous joindre — CAD.",
    businessStyle: "Canadian French professional tone with CAD and metric units.",
  },
  {
    countryCode: "BE",
    countryName: "Belgium",
    region: "Europe",
    subregion: "Western Europe",
    language: "French",
    languageVariant: "Belgian French",
    locale: "fr-BE",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Brussels",
    culturalNotes: "Belgian French; not Canadian. Formal business vous.",
    marketingStyle: "Precise, EU-aware, EUR.",
    ctaStyle: "Demander un devis — EUR.",
    businessStyle: "Belgian French corporate with EUR.",
  },
  {
    countryCode: "CH",
    countryName: "Switzerland",
    region: "Europe",
    subregion: "Western Europe",
    language: "French",
    languageVariant: "Swiss French",
    locale: "fr-CH",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ".",
    group: "'",
    timezone: "Europe/Zurich",
    culturalNotes: "Precise, reserved. CHF not EUR.",
    marketingStyle: "Quality, discretion, Swiss reliability.",
    ctaStyle: "Nous contacter — CHF.",
    businessStyle: "Swiss French with CHF.",
  },
  {
    countryCode: "MA",
    countryName: "Morocco",
    region: "Africa",
    subregion: "North Africa",
    language: "French",
    languageVariant: "Moroccan French",
    locale: "fr-MA",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Africa/Casablanca",
    culturalNotes: "Professional French used widely in Moroccan business. MAD not EUR.",
    marketingStyle: "Practical, local, MAD pricing.",
    ctaStyle: "Nous contacter — MAD.",
    businessStyle: "Moroccan business French with MAD.",
  },
  {
    countryCode: "SN",
    countryName: "Senegal",
    region: "Africa",
    subregion: "West Africa",
    language: "French",
    languageVariant: "Senegalese French",
    locale: "fr-SN",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Africa/Dakar",
    culturalNotes: "West African French; XOF not EUR.",
    marketingStyle: "Warm, community-aware, local proof.",
    ctaStyle: "Nous contacter — XOF.",
    businessStyle: "Senegalese business French with XOF.",
  },
  {
    countryCode: "ES",
    countryName: "Spain",
    region: "Europe",
    subregion: "Southern Europe",
    language: "Spanish",
    languageVariant: "Spain Spanish (Castilian)",
    locale: "es-ES",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Madrid",
    culturalNotes: "Use vosotros where natural in Spain; European vocabulary (ordenador, móvil). Not Latin American slang.",
    marketingStyle: "Clear, warm-professional, EUR.",
    ctaStyle: "Empieza ahora, Solicita información — EUR.",
    businessStyle: "Spain Spanish with EUR.",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    region: "Americas",
    subregion: "North America",
    language: "Spanish",
    languageVariant: "Mexican Spanish",
    locale: "es-MX",
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "America/Mexico_City",
    culturalNotes: "Ustedes not vosotros. Mexican terminology. MXN not USD or EUR.",
    marketingStyle: "Warm, direct, locally relevant social proof.",
    ctaStyle: "Comenzar, Contáctanos — MXN.",
    businessStyle: "Mexican business Spanish with MXN.",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    region: "Americas",
    subregion: "South America",
    language: "Spanish",
    languageVariant: "Argentinian Spanish",
    locale: "es-AR",
    currencyCode: "ARS",
    currencyName: "Argentine Peso",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "America/Argentina/Buenos_Aires",
    culturalNotes: "Rioplatense phrasing where natural; ARS not USD.",
    marketingStyle: "Expressive but professional; local market.",
    ctaStyle: "Empezá ahora — ARS.",
    businessStyle: "Argentinian business Spanish with ARS.",
  },
  {
    countryCode: "CO",
    countryName: "Colombia",
    region: "Americas",
    subregion: "South America",
    language: "Spanish",
    languageVariant: "Colombian Spanish",
    locale: "es-CO",
    currencyCode: "COP",
    currencyName: "Colombian Peso",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "America/Bogota",
    culturalNotes: "Neutral Latin American professional Spanish. COP not USD.",
    marketingStyle: "Warm, clear, COP pricing.",
    ctaStyle: "Comenzar — COP.",
    businessStyle: "Colombian business Spanish with COP.",
  },
  {
    countryCode: "CL",
    countryName: "Chile",
    region: "Americas",
    subregion: "South America",
    language: "Spanish",
    languageVariant: "Chilean Spanish (professional register)",
    locale: "es-CL",
    currencyCode: "CLP",
    currencyName: "Chilean Peso",
    dateFormat: "dd-MM-yyyy",
    hourCycle: "h23",
    timezone: "America/Santiago",
    culturalNotes: "Professional Chilean Spanish. CLP not USD.",
    marketingStyle: "Direct, local, CLP.",
    ctaStyle: "Comenzar — CLP.",
    businessStyle: "Chilean business Spanish with CLP.",
  },
  {
    countryCode: "PE",
    countryName: "Peru",
    region: "Americas",
    subregion: "South America",
    language: "Spanish",
    languageVariant: "Peruvian Spanish",
    locale: "es-PE",
    currencyCode: "PEN",
    currencyName: "Peruvian Sol",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "America/Lima",
    culturalNotes: "Neutral professional Spanish. PEN not USD.",
    marketingStyle: "Clear, local, PEN.",
    ctaStyle: "Comenzar — PEN.",
    businessStyle: "Peruvian business Spanish with PEN.",
  },
  {
    countryCode: "US",
    countryName: "United States",
    region: "Americas",
    subregion: "North America",
    language: "Spanish",
    languageVariant: "US Spanish",
    locale: "es-US",
    currencyCode: "USD",
    currencyName: "US Dollar",
    dateFormat: "MM/dd/yyyy",
    hourCycle: "h12",
    measurementSystem: "imperial",
    timezone: "America/New_York",
    culturalNotes: "US Hispanic market Spanish. USD, US conventions. Not Spain vosotros.",
    marketingStyle: "Bilingual-aware US Spanish marketing, USD.",
    ctaStyle: "Comienza ahora — USD.",
    businessStyle: "US Spanish business copy with USD.",
  },
  {
    countryCode: "DE",
    countryName: "Germany",
    region: "Europe",
    subregion: "Western Europe",
    language: "German",
    languageVariant: "Germany German",
    locale: "de-DE",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Berlin",
    culturalNotes: "Formal Sie in business. Precise, factual. Not Swiss or Austrian variants.",
    marketingStyle: "Evidence-led, clear benefits, DSGVO-aware tone.",
    ctaStyle: "Jetzt starten, Angebot anfordern — EUR.",
    businessStyle: "German business German with EUR and metric units.",
  },
  {
    countryCode: "AT",
    countryName: "Austria",
    region: "Europe",
    subregion: "Western Europe",
    language: "German",
    languageVariant: "Austrian German",
    locale: "de-AT",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Vienna",
    culturalNotes: "Austrian terminology where it differs from Germany. Formal Sie.",
    marketingStyle: "Reliable, local Austrian context, EUR.",
    ctaStyle: "Jetzt starten — EUR.",
    businessStyle: "Austrian business German with EUR.",
  },
  {
    countryCode: "CH",
    countryName: "Switzerland",
    region: "Europe",
    subregion: "Western Europe",
    language: "German",
    languageVariant: "Swiss Standard German",
    locale: "de-CH",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ".",
    group: "'",
    timezone: "Europe/Zurich",
    culturalNotes: "Swiss High German (ss not ß). CHF not EUR.",
    marketingStyle: "Precise, quality, discreet.",
    ctaStyle: "Kontakt aufnehmen — CHF.",
    businessStyle: "Swiss German business copy with CHF.",
  },
  {
    countryCode: "JP",
    countryName: "Japan",
    region: "Asia",
    subregion: "East Asia",
    language: "Japanese",
    languageVariant: "Japanese (Japan)",
    locale: "ja-JP",
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    dateFormat: "yyyy/MM/dd",
    hourCycle: "h23",
    timezone: "Asia/Tokyo",
    culturalNotes: "Polite professional keigo in business. Yen amounts without decimals. Metric.",
    marketingStyle: "Trust, quality, detail. Avoid overly aggressive US-style urgency.",
    ctaStyle: "お問い合わせ, 無料で始める — JPY.",
    businessStyle: "Japanese business register with JPY.",
  },
  {
    countryCode: "IT",
    countryName: "Italy",
    region: "Europe",
    subregion: "Southern Europe",
    language: "Italian",
    languageVariant: "Italy Italian",
    locale: "it-IT",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Rome",
    culturalNotes: "Formal Lei in business. EUR, metric.",
    marketingStyle: "Elegant, quality-led, EUR.",
    ctaStyle: "Inizia ora, Richiedi informazioni — EUR.",
    businessStyle: "Italian business Italian with EUR.",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    region: "Americas",
    subregion: "South America",
    language: "Portuguese",
    languageVariant: "Brazilian Portuguese",
    locale: "pt-BR",
    currencyCode: "BRL",
    currencyName: "Brazilian Real",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "America/Sao_Paulo",
    culturalNotes: "Brazilian Portuguese (você). Not European Portuguese. BRL not EUR.",
    marketingStyle: "Warm, energetic, local proof, BRL.",
    ctaStyle: "Começar agora, Fale conosco — BRL.",
    businessStyle: "Brazilian business Portuguese with BRL.",
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    region: "Europe",
    subregion: "Southern Europe",
    language: "Portuguese",
    languageVariant: "European Portuguese",
    locale: "pt-PT",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Lisbon",
    culturalNotes: "European Portuguese. Not Brazilian vocabulary. EUR.",
    marketingStyle: "Measured, formal-friendly, EUR.",
    ctaStyle: "Começar, Pedir informações — EUR.",
    businessStyle: "Portugal business Portuguese with EUR.",
  },
  {
    countryCode: "NL",
    countryName: "Netherlands",
    region: "Europe",
    subregion: "Western Europe",
    language: "Dutch",
    languageVariant: "Netherlands Dutch",
    locale: "nl-NL",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd-MM-yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Amsterdam",
    culturalNotes: "Direct, informal-professional. EUR.",
    marketingStyle: "Clear, no-nonsense, EUR.",
    ctaStyle: "Aan de slag — EUR.",
    businessStyle: "Dutch business Dutch with EUR.",
  },
  {
    countryCode: "BE",
    countryName: "Belgium",
    region: "Europe",
    subregion: "Western Europe",
    language: "Dutch",
    languageVariant: "Belgian Dutch (Flemish professional)",
    locale: "nl-BE",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Brussels",
    culturalNotes: "Flemish professional Dutch. EUR.",
    marketingStyle: "Clear, local Belgian context.",
    ctaStyle: "Aan de slag — EUR.",
    businessStyle: "Belgian Dutch with EUR.",
  },
  {
    countryCode: "TR",
    countryName: "Turkey",
    region: "Europe",
    subregion: "Anatolia",
    language: "Turkish",
    languageVariant: "Turkish (Turkey)",
    locale: "tr-TR",
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Istanbul",
    culturalNotes: "Professional Istanbul Turkish. TRY not EUR or USD.",
    marketingStyle: "Warm-professional, local proof, TRY.",
    ctaStyle: "Hemen başla — TRY.",
    businessStyle: "Turkish business copy with TRY.",
  },
  {
    countryCode: "CN",
    countryName: "China",
    region: "Asia",
    subregion: "East Asia",
    language: "Simplified Chinese",
    languageVariant: "Mainland Simplified Chinese",
    locale: "zh-CN",
    currencyCode: "CNY",
    currencyName: "Chinese Yuan",
    dateFormat: "yyyy/MM/dd",
    hourCycle: "h23",
    timezone: "Asia/Shanghai",
    culturalNotes: "Mainland Simplified Chinese. CNY/RMB. Not Traditional characters.",
    marketingStyle: "Trust, quality, practical benefits, CNY.",
    ctaStyle: "立即咨询 — CNY.",
    businessStyle: "Mainland Chinese business copy with CNY.",
  },
  {
    countryCode: "TW",
    countryName: "Taiwan",
    region: "Asia",
    subregion: "East Asia",
    language: "Traditional Chinese",
    languageVariant: "Taiwan Traditional Chinese",
    locale: "zh-TW",
    currencyCode: "TWD",
    currencyName: "New Taiwan Dollar",
    dateFormat: "yyyy/MM/dd",
    hourCycle: "h12",
    timezone: "Asia/Taipei",
    culturalNotes: "Traditional characters. TWD not CNY.",
    marketingStyle: "Polite, quality-led, TWD.",
    ctaStyle: "立即諮詢 — TWD.",
    businessStyle: "Taiwan business Chinese with TWD.",
  },
  {
    countryCode: "HK",
    countryName: "Hong Kong",
    region: "Asia",
    subregion: "East Asia",
    language: "Traditional Chinese",
    languageVariant: "Hong Kong Traditional Chinese",
    locale: "zh-HK",
    currencyCode: "HKD",
    currencyName: "Hong Kong Dollar",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Hong_Kong",
    culturalNotes: "Hong Kong Traditional Chinese. HKD not CNY or TWD.",
    marketingStyle: "International, efficient, HKD.",
    ctaStyle: "立即查詢 — HKD.",
    businessStyle: "Hong Kong business Chinese with HKD.",
  },
  {
    countryCode: "KR",
    countryName: "South Korea",
    region: "Asia",
    subregion: "East Asia",
    language: "Korean",
    languageVariant: "Korean (South Korea)",
    locale: "ko-KR",
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    dateFormat: "yyyy. MM. dd.",
    hourCycle: "h12",
    timezone: "Asia/Seoul",
    culturalNotes: "Polite professional Korean. KRW, no decimals on won.",
    marketingStyle: "Trust, quality, KRW.",
    ctaStyle: "시작하기 — KRW.",
    businessStyle: "Korean business copy with KRW.",
  },
  {
    countryCode: "RU",
    countryName: "Russia",
    region: "Europe",
    subregion: "Eastern Europe",
    language: "Russian",
    languageVariant: "Russian (Russia)",
    locale: "ru-RU",
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Moscow",
    culturalNotes: "Formal professional Russian. RUB.",
    marketingStyle: "Factual, authoritative, RUB.",
    ctaStyle: "Начать — RUB.",
    businessStyle: "Russian business copy with RUB.",
  },
  {
    countryCode: "IN",
    countryName: "India",
    region: "Asia",
    subregion: "South Asia",
    language: "Hindi",
    languageVariant: "Hindi (India)",
    locale: "hi-IN",
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Kolkata",
    culturalNotes: "Professional Hindi. INR. Respectful address.",
    marketingStyle: "Clear value, local trust, INR.",
    ctaStyle: "शुरू करें — INR.",
    businessStyle: "Hindi business copy with INR.",
  },
  {
    countryCode: "ID",
    countryName: "Indonesia",
    region: "Asia",
    subregion: "Southeast Asia",
    language: "Indonesian",
    languageVariant: "Bahasa Indonesia",
    locale: "id-ID",
    currencyCode: "IDR",
    currencyName: "Indonesian Rupiah",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Asia/Jakarta",
    culturalNotes: "Formal-professional Indonesian. IDR.",
    marketingStyle: "Friendly-professional, IDR.",
    ctaStyle: "Mulai sekarang — IDR.",
    businessStyle: "Indonesian business copy with IDR.",
  },
  {
    countryCode: "VN",
    countryName: "Vietnam",
    region: "Asia",
    subregion: "Southeast Asia",
    language: "Vietnamese",
    languageVariant: "Vietnamese (Vietnam)",
    locale: "vi-VN",
    currencyCode: "VND",
    currencyName: "Vietnamese Dong",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Asia/Ho_Chi_Minh",
    culturalNotes: "Professional Vietnamese. VND, no decimals.",
    marketingStyle: "Clear, local, VND.",
    ctaStyle: "Bắt đầu — VND.",
    businessStyle: "Vietnamese business copy with VND.",
  },
  {
    countryCode: "TH",
    countryName: "Thailand",
    region: "Asia",
    subregion: "Southeast Asia",
    language: "Thai",
    languageVariant: "Thai (Thailand)",
    locale: "th-TH",
    currencyCode: "THB",
    currencyName: "Thai Baht",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    timezone: "Asia/Bangkok",
    culturalNotes: "Polite professional Thai. THB.",
    marketingStyle: "Warm, respectful, THB.",
    ctaStyle: "เริ่มต้น — THB.",
    businessStyle: "Thai business copy with THB.",
  },
  {
    countryCode: "PL",
    countryName: "Poland",
    region: "Europe",
    subregion: "Central Europe",
    language: "Polish",
    languageVariant: "Polish (Poland)",
    locale: "pl-PL",
    currencyCode: "PLN",
    currencyName: "Polish Zloty",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Warsaw",
    culturalNotes: "Formal professional Polish. PLN not EUR.",
    marketingStyle: "Clear, factual, PLN.",
    ctaStyle: "Zacznij teraz — PLN.",
    businessStyle: "Polish business copy with PLN.",
  },
  {
    countryCode: "SE",
    countryName: "Sweden",
    region: "Europe",
    subregion: "Northern Europe",
    language: "Swedish",
    languageVariant: "Swedish (Sweden)",
    locale: "sv-SE",
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    dateFormat: "yyyy-MM-dd",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Stockholm",
    culturalNotes: "Direct, egalitarian. SEK not EUR.",
    marketingStyle: "Understated, clear, SEK.",
    ctaStyle: "Kom igång — SEK.",
    businessStyle: "Swedish business copy with SEK.",
  },
  {
    countryCode: "NO",
    countryName: "Norway",
    region: "Europe",
    subregion: "Northern Europe",
    language: "Norwegian",
    languageVariant: "Norwegian Bokmål",
    locale: "nb-NO",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Oslo",
    culturalNotes: "Bokmål professional. NOK not EUR.",
    marketingStyle: "Plain, trustworthy, NOK.",
    ctaStyle: "Kom i gang — NOK.",
    businessStyle: "Norwegian business copy with NOK.",
  },
  {
    countryCode: "DK",
    countryName: "Denmark",
    region: "Europe",
    subregion: "Northern Europe",
    language: "Danish",
    languageVariant: "Danish (Denmark)",
    locale: "da-DK",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Copenhagen",
    culturalNotes: "Direct, informal-professional. DKK not EUR.",
    marketingStyle: "Clear, no-hype, DKK.",
    ctaStyle: "Kom i gang — DKK.",
    businessStyle: "Danish business copy with DKK.",
  },
  {
    countryCode: "FI",
    countryName: "Finland",
    region: "Europe",
    subregion: "Northern Europe",
    language: "Finnish",
    languageVariant: "Finnish (Finland)",
    locale: "fi-FI",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "d.M.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Helsinki",
    culturalNotes: "Concise, factual. EUR.",
    marketingStyle: "Understated, clear, EUR.",
    ctaStyle: "Aloita — EUR.",
    businessStyle: "Finnish business copy with EUR.",
  },
  {
    countryCode: "GR",
    countryName: "Greece",
    region: "Europe",
    subregion: "Southern Europe",
    language: "Greek",
    languageVariant: "Greek (Greece)",
    locale: "el-GR",
    currencyCode: "EUR",
    currencyName: "Euro",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Athens",
    culturalNotes: "Professional Greek. EUR.",
    marketingStyle: "Warm-professional, EUR.",
    ctaStyle: "Ξεκινήστε — EUR.",
    businessStyle: "Greek business copy with EUR.",
  },
  {
    countryCode: "CZ",
    countryName: "Czechia",
    region: "Europe",
    subregion: "Central Europe",
    language: "Czech",
    languageVariant: "Czech (Czechia)",
    locale: "cs-CZ",
    currencyCode: "CZK",
    currencyName: "Czech Koruna",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Prague",
    culturalNotes: "Professional Czech. CZK not EUR.",
    marketingStyle: "Factual, local, CZK.",
    ctaStyle: "Začít — CZK.",
    businessStyle: "Czech business copy with CZK.",
  },
  {
    countryCode: "RO",
    countryName: "Romania",
    region: "Europe",
    subregion: "Eastern Europe",
    language: "Romanian",
    languageVariant: "Romanian (Romania)",
    locale: "ro-RO",
    currencyCode: "RON",
    currencyName: "Romanian Leu",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: ".",
    timezone: "Europe/Bucharest",
    culturalNotes: "Professional Romanian. RON not EUR unless the brief is export pricing.",
    marketingStyle: "Clear, local, RON.",
    ctaStyle: "Începe acum — RON.",
    businessStyle: "Romanian business copy with RON.",
  },
  {
    countryCode: "UA",
    countryName: "Ukraine",
    region: "Europe",
    subregion: "Eastern Europe",
    language: "Ukrainian",
    languageVariant: "Ukrainian (Ukraine)",
    locale: "uk-UA",
    currencyCode: "UAH",
    currencyName: "Ukrainian Hryvnia",
    dateFormat: "dd.MM.yyyy",
    hourCycle: "h23",
    decimal: ",",
    group: " ",
    timezone: "Europe/Kyiv",
    culturalNotes: "Ukrainian language, not Russian. UAH.",
    marketingStyle: "Direct, respectful, UAH.",
    ctaStyle: "Почати — UAH.",
    businessStyle: "Ukrainian business copy with UAH.",
  },
  {
    countryCode: "MY",
    countryName: "Malaysia",
    region: "Asia",
    subregion: "Southeast Asia",
    language: "Malay",
    languageVariant: "Bahasa Malaysia",
    locale: "ms-MY",
    currencyCode: "MYR",
    currencyName: "Malaysian Ringgit",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Kuala_Lumpur",
    culturalNotes: "Professional Malay. MYR.",
    marketingStyle: "Inclusive, local, MYR.",
    ctaStyle: "Mula sekarang — MYR.",
    businessStyle: "Malaysian business Malay with MYR.",
  },
  {
    countryCode: "BD",
    countryName: "Bangladesh",
    region: "Asia",
    subregion: "South Asia",
    language: "Bengali",
    languageVariant: "Bengali (Bangladesh)",
    locale: "bn-BD",
    currencyCode: "BDT",
    currencyName: "Bangladeshi Taka",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Dhaka",
    culturalNotes: "Professional Bengali. BDT not INR.",
    marketingStyle: "Respectful, local, BDT.",
    ctaStyle: "শুরু করুন — BDT.",
    businessStyle: "Bengali business copy with BDT.",
  },
  {
    countryCode: "IR",
    countryName: "Iran",
    region: "Middle East",
    subregion: "Iran",
    language: "Persian",
    languageVariant: "Persian (Iran)",
    locale: "fa-IR",
    currencyCode: "IRR",
    currencyName: "Iranian Rial",
    dateFormat: "yyyy/MM/dd",
    hourCycle: "h23",
    timezone: "Asia/Tehran",
    culturalNotes: "Formal professional Persian. RTL. IRR.",
    marketingStyle: "Respectful, formal, IRR.",
    ctaStyle: "شروع کنید — IRR.",
    businessStyle: "Persian business copy with IRR.",
  },
  {
    countryCode: "PK",
    countryName: "Pakistan",
    region: "Asia",
    subregion: "South Asia",
    language: "Urdu",
    languageVariant: "Urdu (Pakistan)",
    locale: "ur-PK",
    currencyCode: "PKR",
    currencyName: "Pakistani Rupee",
    dateFormat: "dd/MM/yyyy",
    hourCycle: "h12",
    timezone: "Asia/Karachi",
    culturalNotes: "Professional Urdu. RTL. PKR not INR.",
    marketingStyle: "Respectful, local, PKR.",
    ctaStyle: "شروع کریں — PKR.",
    businessStyle: "Urdu business copy with PKR.",
  },
];

export const GCRI_CATALOG: readonly GcriProfile[] = ROWS.map(toProfile);

/** Language → default ISO country when the user has not chosen a market. */
export const GCRI_DEFAULT_COUNTRY_BY_LANGUAGE: Record<string, string> = {
  Arabic: "SA",
  Bilingual: "SA",
  English: "US",
  French: "FR",
  Spanish: "ES",
  German: "DE",
  Italian: "IT",
  Portuguese: "BR",
  Dutch: "NL",
  Turkish: "TR",
  "Simplified Chinese": "CN",
  "Traditional Chinese": "TW",
  Japanese: "JP",
  Korean: "KR",
  Russian: "RU",
  Hindi: "IN",
  Indonesian: "ID",
  Vietnamese: "VN",
  Thai: "TH",
  Polish: "PL",
  Swedish: "SE",
  Norwegian: "NO",
  Danish: "DK",
  Finnish: "FI",
  Greek: "GR",
  Czech: "CZ",
  Romanian: "RO",
  Ukrainian: "UA",
  Malay: "MY",
  Bengali: "BD",
  Persian: "IR",
  Urdu: "PK",
};
