import type {
  TemplateAnimationProfile,
  TemplateIntelligenceDefinition,
} from "@/lib/ai-core/template-intelligence/types";
import {
  PALETTE_ARCHITECTURE,
  PALETTE_BEAUTY,
  PALETTE_CAFE,
  PALETTE_CONSTRUCTION,
  PALETTE_DENTAL,
  PALETTE_FITNESS,
  PALETTE_INSURANCE,
  PALETTE_LOGISTICS,
  PALETTE_MANUFACTURING,
  PALETTE_NONPROFIT,
  PALETTE_PHARMACY,
  PALETTE_UNIVERSITY,
} from "@/lib/ai-core/template-intelligence/industry-palettes";

const fadeUp: TemplateAnimationProfile = {
  id: "fade-up",
  label: "Fade up",
  entrance: "fadeUp 0.75s cubic-bezier(0.22,1,0.36,1)",
  hover: "subtle lift 4px",
  scroll: "section reveal on enter",
  reducedMotion: "disable transforms",
};

const cinematic: TemplateAnimationProfile = {
  id: "cinematic",
  label: "Cinematic",
  entrance: "slowReveal 1s cubic-bezier(0.22,1,0.36,1)",
  hover: "scale 1.02 media",
  scroll: "parallax-lite hero",
  reducedMotion: "opacity only",
};

const crisp: TemplateAnimationProfile = {
  id: "crisp",
  label: "Crisp SaaS",
  entrance: "fadeUp 0.55s ease-out",
  hover: "border glow",
  scroll: "stagger cards 70ms",
  reducedMotion: "instant",
};

const warmReveal: TemplateAnimationProfile = {
  id: "warm-reveal",
  label: "Warm reveal",
  entrance: "fadeUp 0.9s cubic-bezier(0.16,1,0.3,1)",
  hover: "soft scale 1.015",
  scroll: "gentle section fade",
  reducedMotion: "opacity only",
};

const industrialSnap: TemplateAnimationProfile = {
  id: "industrial-snap",
  label: "Industrial snap",
  entrance: "clipReveal 0.65s cubic-bezier(0.4,0,0.2,1)",
  hover: "border accent pulse",
  scroll: "stagger grid 50ms",
  reducedMotion: "instant",
};

const editorialFlow: TemplateAnimationProfile = {
  id: "editorial-flow",
  label: "Editorial flow",
  entrance: "slideUp 1.1s cubic-bezier(0.22,1,0.36,1)",
  hover: "underline grow",
  scroll: "parallax columns",
  reducedMotion: "opacity only",
};

const energeticPulse: TemplateAnimationProfile = {
  id: "energetic-pulse",
  label: "Energetic pulse",
  entrance: "scaleIn 0.5s cubic-bezier(0.34,1.56,0.64,1)",
  hover: "lift 6px + glow",
  scroll: "momentum scroll sections",
  reducedMotion: "fade only",
};

/** Premium industry Template Intelligence profiles for the 30-template library. */
export const PREMIUM_INDUSTRY_TEMPLATE_INTELLIGENCE = [
    {
      id: "ti-cafe-artisan",
      name: "Cafe Artisan",
      tagline: "Neighborhood craft coffee with warmth and ritual",
      description:
        "Morning-light hero, roast story, menu cards, and community booking flows.",
      category: "Restaurant",
      industry: "cafe",
      designStyle: "Artisan morning",
      designPreset: "modern",
      layoutStructure: "editorial-hero",
      colors: {
        primary: "#3F2E26",
        secondary: "#8B6F5C",
        accent: "#C4A574",
        background: "#FBF7F2",
        foreground: "#2C211B",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Fraunces",
        heading: "Fraunces",
        body: "DM Sans",
      },
      components: PALETTE_CAFE,
      animations: warmReveal,
      brandPresetId: "modern-brand",
      premiumTemplateId: "cafe-artisan",
      keywords: ["cafe", "coffee", "bakery", "brunch", "artisan"],
      audienceHints: ["locals", "remote workers", "foodies"],
      brandStyleHints: ["cafe", "coffee", "artisan"],
    },
    {
      id: "ti-architecture-monograph",
      name: "Architecture Monograph",
      tagline: "Monographic project storytelling for studios",
      description:
        "Magazine grids, project folios, process essays, and inquiry-led CTAs.",
      category: "Creative",
      industry: "architecture",
      designStyle: "Architectural monograph",
      designPreset: "minimal",
      layoutStructure: "editorial-hero",
      colors: {
        primary: "#111111",
        secondary: "#6B6B6B",
        accent: "#B8A88A",
        background: "#F4F2EE",
        foreground: "#111111",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Instrument Serif",
        heading: "Instrument Serif",
        body: "Inter",
      },
      components: PALETTE_ARCHITECTURE,
      animations: editorialFlow,
      brandPresetId: "creative-brand",
      premiumTemplateId: "architecture-monograph",
      keywords: ["architecture", "studio", "blueprint", "interior", "urban"],
      audienceHints: ["developers", "homeowners", "institutions"],
      brandStyleHints: ["architecture", "design studio"],
    },
    {
      id: "ti-construction-industrial",
      name: "Construction Industrial",
      tagline: "Heavy-duty credibility for builders and contractors",
      description:
        "Safety-first hero, capability grids, project timelines, and bid CTAs.",
      category: "Corporate",
      industry: "construction",
      designStyle: "Industrial precision",
      designPreset: "corporate",
      layoutStructure: "split-hero",
      colors: {
        primary: "#1A2332",
        secondary: "#4A5568",
        accent: "#F59E0B",
        background: "#F1F5F9",
        foreground: "#0F172A",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Barlow Condensed",
        heading: "Barlow Condensed",
        body: "Source Sans 3",
      },
      components: PALETTE_CONSTRUCTION,
      animations: industrialSnap,
      brandPresetId: "corporate-brand",
      premiumTemplateId: "construction-build",
      keywords: ["construction", "contractor", "building", "infrastructure"],
      audienceHints: ["property owners", "developers", "municipalities"],
      brandStyleHints: ["construction", "industrial"],
    },
    {
      id: "ti-dental-smile",
      name: "Dental Smile",
      tagline: "Clinical calm with premium patient reassurance",
      description:
        "Bright trust hero, treatment cards, doctor profiles, and booking.",
      category: "Corporate",
      industry: "dental",
      designStyle: "Clinical serenity",
      designPreset: "minimal",
      layoutStructure: "split-hero",
      colors: {
        primary: "#0E7490",
        secondary: "#67E8F9",
        accent: "#14B8A6",
        background: "#FFFFFF",
        foreground: "#0F172A",
        surface: "#F0FDFA",
      },
      typography: {
        display: "Plus Jakarta Sans",
        heading: "Plus Jakarta Sans",
        body: "Inter",
      },
      components: PALETTE_DENTAL,
      animations: fadeUp,
      brandPresetId: "corporate-brand",
      premiumTemplateId: "dental-smile",
      keywords: ["dental", "dentist", "orthodontics", "smile", "clinic"],
      audienceHints: ["families", "professionals", "patients"],
      brandStyleHints: ["dental", "healthcare"],
    },
    {
      id: "ti-pharmacy-wellness",
      name: "Pharmacy Wellness",
      tagline: "Accessible care with product clarity",
      description:
        "Wellness hero, service lanes, pharmacist trust, and refill CTAs.",
      category: "Corporate",
      industry: "pharmacy",
      designStyle: "Wellness clarity",
      designPreset: "modern",
      layoutStructure: "product-saas",
      colors: {
        primary: "#047857",
        secondary: "#10B981",
        accent: "#34D399",
        background: "#F0FDF4",
        foreground: "#064E3B",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Nunito Sans",
        heading: "Nunito Sans",
        body: "Open Sans",
      },
      components: PALETTE_PHARMACY,
      animations: warmReveal,
      brandPresetId: "corporate-brand",
      premiumTemplateId: "pharmacy-wellness",
      keywords: ["pharmacy", "wellness", "health", "prescription", "care"],
      audienceHints: ["patients", "caregivers", "seniors"],
      brandStyleHints: ["pharmacy", "wellness"],
    },
    {
      id: "ti-insurance-shield",
      name: "Insurance Shield",
      tagline: "Trust architecture for coverage and claims",
      description:
        "Assurance hero, plan comparison, advisor profiles, and quote flows.",
      category: "Corporate",
      industry: "insurance",
      designStyle: "Assured trust",
      designPreset: "corporate",
      layoutStructure: "split-hero",
      colors: {
        primary: "#1E3A5F",
        secondary: "#3B82F6",
        accent: "#60A5FA",
        background: "#F8FAFC",
        foreground: "#0F172A",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Libre Franklin",
        heading: "Libre Franklin",
        body: "Source Sans 3",
      },
      components: PALETTE_INSURANCE,
      animations: fadeUp,
      brandPresetId: "corporate-brand",
      premiumTemplateId: "insurance-shield",
      keywords: ["insurance", "coverage", "policy", "claims", "protection"],
      audienceHints: ["families", "businesses", "homeowners"],
      brandStyleHints: ["insurance", "financial trust"],
    },
    {
      id: "ti-university-heritage",
      name: "University Heritage",
      tagline: "Scholarly gravitas with modern admissions",
      description:
        "Campus cinematic hero, schools grid, research highlights, and apply CTAs.",
      category: "Corporate",
      industry: "university",
      designStyle: "Heritage campus",
      designPreset: "corporate",
      layoutStructure: "campus-education",
      colors: {
        primary: "#7F1D1D",
        secondary: "#B45309",
        accent: "#D97706",
        background: "#FFFBEB",
        foreground: "#1C1917",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Libre Baskerville",
        heading: "Libre Baskerville",
        body: "Source Sans 3",
      },
      components: PALETTE_UNIVERSITY,
      animations: cinematic,
      brandPresetId: "corporate-brand",
      premiumTemplateId: "university-heritage",
      keywords: ["university", "college", "campus", "research", "alumni"],
      audienceHints: ["students", "parents", "researchers"],
      brandStyleHints: ["university", "higher education"],
    },
    {
      id: "ti-beauty-glow",
      name: "Beauty Glow",
      tagline: "Luminous editorial beauty and spa experiences",
      description:
        "Soft cinematic hero, treatment rituals, product stories, and booking.",
      category: "Luxury",
      industry: "beauty",
      designStyle: "Luminous spa",
      designPreset: "luxury",
      layoutStructure: "editorial-hero",
      colors: {
        primary: "#4A044E",
        secondary: "#A21CAF",
        accent: "#F0ABFC",
        background: "#FDF4FF",
        foreground: "#3B0764",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Cormorant Garamond",
        heading: "Cormorant Garamond",
        body: "Outfit",
      },
      components: PALETTE_BEAUTY,
      animations: cinematic,
      brandPresetId: "luxury-brand",
      premiumTemplateId: "beauty-glow",
      keywords: ["beauty", "spa", "skincare", "salon", "wellness"],
      audienceHints: ["clients", "luxury seekers", "brides"],
      brandStyleHints: ["beauty", "spa", "luxury"],
    },
    {
      id: "ti-fitness-pulse",
      name: "Fitness Pulse",
      tagline: "High-energy training brands with momentum",
      description:
        "Dynamic hero, program cards, trainer roster, and membership CTAs.",
      category: "Modern",
      industry: "fitness",
      designStyle: "Athletic momentum",
      designPreset: "bold",
      layoutStructure: "conversion-landing",
      colors: {
        primary: "#DC2626",
        secondary: "#171717",
        accent: "#FACC15",
        background: "#0A0A0A",
        foreground: "#FAFAFA",
        surface: "#171717",
      },
      typography: {
        display: "Bebas Neue",
        heading: "Bebas Neue",
        body: "Inter",
      },
      components: PALETTE_FITNESS,
      animations: energeticPulse,
      brandPresetId: "bold-brand",
      premiumTemplateId: "fitness-pulse",
      keywords: ["fitness", "gym", "training", "crossfit", "wellness"],
      audienceHints: ["athletes", "beginners", "coaches"],
      brandStyleHints: ["fitness", "gym", "sports"],
    },
    {
      id: "ti-logistics-freight",
      name: "Logistics Freight",
      tagline: "Global freight with operational clarity",
      description:
        "Route hero, fleet capabilities, tracking proof, and quote requests.",
      category: "Corporate",
      industry: "logistics",
      designStyle: "Freight operations",
      designPreset: "corporate",
      layoutStructure: "split-hero",
      colors: {
        primary: "#0F4C81",
        secondary: "#1D6FA5",
        accent: "#38BDF8",
        background: "#F0F9FF",
        foreground: "#0C4A6E",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Roboto Condensed",
        heading: "Roboto Condensed",
        body: "Roboto",
      },
      components: PALETTE_LOGISTICS,
      animations: industrialSnap,
      brandPresetId: "corporate-brand",
      premiumTemplateId: "logistics-freight",
      keywords: ["logistics", "freight", "shipping", "supply chain", "fleet"],
      audienceHints: ["shippers", "enterprises", "distributors"],
      brandStyleHints: ["logistics", "freight"],
    },
    {
      id: "ti-manufacturing-precision",
      name: "Manufacturing Precision",
      tagline: "Engineering excellence for industrial leaders",
      description:
        "Precision hero, capability matrix, quality certifications, and RFQ flows.",
      category: "Technology",
      industry: "manufacturing",
      designStyle: "Precision engineering",
      designPreset: "corporate",
      layoutStructure: "product-saas",
      colors: {
        primary: "#1E293B",
        secondary: "#475569",
        accent: "#0EA5E9",
        background: "#F8FAFC",
        foreground: "#0F172A",
        surface: "#FFFFFF",
      },
      typography: {
        display: "IBM Plex Sans",
        heading: "IBM Plex Sans",
        body: "IBM Plex Sans",
      },
      components: PALETTE_MANUFACTURING,
      animations: crisp,
      brandPresetId: "technology-brand",
      premiumTemplateId: "manufacturing-precision",
      keywords: ["manufacturing", "industrial", "factory", "engineering", "oem"],
      audienceHints: ["procurement", "engineers", "distributors"],
      brandStyleHints: ["manufacturing", "industrial"],
    },
    {
      id: "ti-nonprofit-impact",
      name: "Nonprofit Impact",
      tagline: "Human-centered storytelling that drives action",
      description:
        "Mission hero, impact metrics, volunteer paths, and donation CTAs.",
      category: "Modern",
      industry: "non-profit",
      designStyle: "Humanitarian warmth",
      designPreset: "modern",
      layoutStructure: "editorial-hero",
      colors: {
        primary: "#0D9488",
        secondary: "#14B8A6",
        accent: "#F59E0B",
        background: "#FFFBEB",
        foreground: "#134E4A",
        surface: "#FFFFFF",
      },
      typography: {
        display: "Merriweather",
        heading: "Merriweather",
        body: "Source Sans 3",
      },
      components: PALETTE_NONPROFIT,
      animations: warmReveal,
      brandPresetId: "modern-brand",
      premiumTemplateId: "nonprofit-impact",
      keywords: ["nonprofit", "charity", "foundation", "volunteer", "donate"],
      audienceHints: ["donors", "volunteers", "communities"],
      brandStyleHints: ["nonprofit", "charity", "impact"],
    },
  ] as unknown as TemplateIntelligenceDefinition[];
