import type { VisualSkin, VisualSkinImageTreatment } from "@/lib/website/visual-skin/types";

const base = (
  id: string,
  label: string,
  description: string,
  tokens: VisualSkin["tokens"],
  typography: VisualSkin["typography"],
  sectionShellVariant: string,
  extras: {
    shadows: VisualSkin["shadows"];
    imageTreatment: VisualSkinImageTreatment;
    motionIntensity: VisualSkin["motionIntensity"];
    rtlTypography?: VisualSkin["rtlTypography"];
    flagship?: boolean;
  },
): VisualSkin => ({
  id,
  label,
  description,
  tokens,
  typography,
  sectionShellVariant,
  shadows: extras.shadows,
  imageTreatment: extras.imageTreatment,
  motionIntensity: extras.motionIntensity,
  rtlTypography: extras.rtlTypography,
  flagship: extras.flagship,
});

/** Published visual skins — global-grade full-frame design systems. */
export const VISUAL_SKIN_CATALOG: readonly VisualSkin[] = [
  base(
    "signal",
    "Signal — Aura",
    "مظهر عالمي داكن — زجاجي، لوحة تحكم AI، توهج سماوي مع لمسة قرمزية فاخرة للتفاعل. للمنتجات التقنية والمنصات العالمية.",
    {
      primary: "#020617",
      secondary: "#111827",
      accent: "#E8364E",
      background: "#030712",
      foreground: "#F1F5F9",
      radius: "1rem",
      signal: "#2EC8E0",
      surface: "#0B1220",
      muted: "rgba(241,245,249,0.58)",
    },
    { headingFont: "Syne", bodyFont: "Outfit" },
    "tech-glass",
    {
      shadows: {
        sm: "0 0 24px color-mix(in srgb, #E8364E 12%, transparent)",
        md: "0 32px 80px rgba(0,0,0,0.45)",
        lg: "0 0 100px color-mix(in srgb, #2EC8E0 16%, transparent)",
      },
      imageTreatment: {
        radius: "1rem",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #2EC8E0 22%, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #2EC8E0 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "volt",
    "Volt — Studio",
    "مظهر وكالة عالمية — أسود صناعي، ليمون كهربائي، typography جريء. للعلامات التي تريد حضوراً مميزاً.",
    {
      primary: "#0A0A0B",
      secondary: "#121214",
      accent: "#D4FF00",
      background: "#0A0A0B",
      foreground: "#F4F4F0",
      radius: "0",
    },
    { headingFont: "Space Grotesk", bodyFont: "Inter" },
    "creative-gradient",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #D4FF00 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #D4FF00 18%, transparent)" },
      imageTreatment: {
        radius: "0",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #D4FF00 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #D4FF00 12%, transparent)",
      },
      motionIntensity: "expressive",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "ledger",
    "Ledger — Capital",
    "ثقة مالية عالمية — كحلي عميق، ذهب راقٍ، typography كلاسيكي. للبنوك وصناديق الاستثمار والخدمات المالية.",
    {
      primary: "#0B1F33",
      secondary: "#163352",
      accent: "#C9A962",
      background: "#EDEAE4",
      foreground: "#0B1F33",
      radius: "0.5rem",
    },
    { headingFont: "Playfair Display", bodyFont: "Lato" },
    "card-first",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0.5rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #C9A962 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C9A962 12%, transparent)",
      },
      motionIntensity: "subtle",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "atlas",
    "Atlas — Executive",
    "شركات عالمية — كريم فاخر، serif راقٍ، إطار ثقة تنفيذي. للاستشارات والمؤسسات والخدمات المهنية.",
    {
      primary: "#0A1628",
      secondary: "#152238",
      accent: "#B89B6E",
      background: "#F8F6F2",
      foreground: "#0A1628",
      radius: "0.75rem",
    },
    { headingFont: "Cormorant Garamond", bodyFont: "Inter" },
    "card-first",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0.75rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #B89B6E 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #B89B6E 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "monolith",
    "Monolith — Estate",
    "عقارات فاخرة عالمية — حجري داكن، brass خفيف، إطار editorial. للتطوير العقاري والعقارات الراقية.",
    {
      primary: "#141210",
      secondary: "#1F1C18",
      accent: "#C4A574",
      background: "#0F0E0C",
      foreground: "#F5F0E8",
      radius: "0.25rem",
    },
    { headingFont: "Fraunces", bodyFont: "Outfit" },
    "editorial",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #C4A574 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #C4A574 18%, transparent)" },
      imageTreatment: {
        radius: "0.25rem",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #C4A574 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C4A574 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "serenity",
    "Serenity — Clinical",
    "رعاية صحية عالمية — sage ناعم، أبيض دافئ، هدوء سريري. للعيادات والمستشفيات ومراكز العافية.",
    {
      primary: "#1B4D48",
      secondary: "#2A635D",
      accent: "#C4A882",
      background: "#F7FAF8",
      foreground: "#142E2B",
      radius: "0.75rem",
    },
    { headingFont: "Libre Baskerville", bodyFont: "Source Sans 3" },
    "minimal",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0.75rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #C4A882 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C4A882 12%, transparent)",
      },
      motionIntensity: "subtle",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "haven",
    "Haven — Mirage",
    "ضيافة غير تقليدية — ضباب بنفسجي، بنية حبرية، وردي نيون. مظهر مرن للعلامات الراقية في أي قطاع.",
    {
      primary: "#2A2340",
      secondary: "#4E3D6B",
      accent: "#FF5C8A",
      background: "#E6E0F5",
      foreground: "#1A1228",
      radius: "0.75rem",
    },
    { headingFont: "Playfair Display", bodyFont: "Outfit" },
    "editorial",
    {
      shadows: { sm: "0 4px 16px rgba(78,61,107,0.1)", md: "0 12px 40px rgba(255,92,138,0.12)", lg: "0 24px 64px rgba(42,35,64,0.14)" },
      imageTreatment: {
        radius: "1.25rem",
        aspectRatio: "4 / 5",
        frame: "1px solid rgba(255,92,138,0.22)",
        shadow: "0 16px 48px rgba(78,61,107,0.14)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Amiri", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "ember",
    "Ember — Global",
    "هيكل شركة عالمية احترافي — شريط علوي، بطل مؤسسي، قدرات، نهج، أعمال، وتواصل.",
    {
      primary: "#1A1410",
      secondary: "#2A2118",
      accent: "#C87840",
      background: "#110D0A",
      foreground: "#F5EDE4",
      radius: "0.125rem",
    },
    { headingFont: "Fraunces", bodyFont: "Literata" },
    "editorial",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #C87840 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #C87840 18%, transparent)" },
      imageTreatment: {
        radius: "0.25rem",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #C87840 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C87840 12%, transparent)",
      },
      motionIntensity: "expressive",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "heritage",
    "Heritage — Academy",
    "تعليم عالمي — كحلي أكاديمي، ذهب كلاسيكي، إحساس جامعي راقٍ. للجامعات والمدارس والمؤسسات التعليمية.",
    {
      primary: "#1B2A4A",
      secondary: "#2A3F66",
      accent: "#C5A572",
      background: "#F7F3EC",
      foreground: "#1B2A4A",
      radius: "0.5rem",
    },
    { headingFont: "EB Garamond", bodyFont: "Nunito Sans" },
    "card-first",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0.5rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #C5A572 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C5A572 12%, transparent)",
      },
      motionIntensity: "subtle",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "atelier",
    "Atelier — Commerce",
    "تجارة فاخرة عالمية — عاجي، حبر، ذهب شامبانيا. للمتاجر الراقية والعلامات التجارية الفاخرة.",
    {
      primary: "#12100E",
      secondary: "#2A2724",
      accent: "#C9A962",
      background: "#FAF8F5",
      foreground: "#12100E",
      radius: "0",
    },
    { headingFont: "Playfair Display", bodyFont: "Manrope" },
    "editorial",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #C9A962 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C9A962 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "nexus",
    "Nexus — Command",
    "منصة SaaS عالمية — indigo فاتح، bento dashboard، ثقة enterprise. للمنتجات B2B عالية النمو.",
    {
      primary: "#4338CA",
      secondary: "#1E1B4B",
      accent: "#818CF8",
      background: "#F8F9FC",
      foreground: "#0F172A",
      radius: "1rem",
    },
    { headingFont: "Syne", bodyFont: "DM Sans" },
    "bento",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "1rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #818CF8 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #818CF8 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "kinetic",
    "Kinetic — Portfolio",
    "معرض إبداعي عالمي — typography ضخم، volt/magenta، حركة spring. للمصممين والمبدعين.",
    {
      primary: "#09090B",
      secondary: "#18181B",
      accent: "#E8FF47",
      background: "#09090B",
      foreground: "#F4F4EF",
      radius: "0",
    },
    { headingFont: "Syne", bodyFont: "Instrument Sans" },
    "creative-gradient",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #E8FF47 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #E8FF47 18%, transparent)" },
      imageTreatment: {
        radius: "0",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #E8FF47 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #E8FF47 12%, transparent)",
      },
      motionIntensity: "expressive",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "estates",
    "Estates — Prestige",
    "عقارات فاخرة فاتحة — كريم، serif راقٍ، معارض properties. للوكالات العقارية العالمية.",
    {
      primary: "#1C1917",
      secondary: "#3D3834",
      accent: "#B8956B",
      background: "#FAF7F2",
      foreground: "#1C1917",
      radius: "0.5rem",
    },
    { headingFont: "Cormorant", bodyFont: "Work Sans" },
    "editorial",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0.5rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #B8956B 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #B8956B 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "forest",
    "Forest — Table",
    "مطعم طبيعي فاخر — أخضر غابة، نحاس، أجواء organic. للمطاعم المستوحاة من الطبيعة.",
    {
      primary: "#1A3D32",
      secondary: "#264A3E",
      accent: "#B87333",
      background: "#0A1210",
      foreground: "#F4EDE4",
      radius: "0.25rem",
    },
    { headingFont: "Cormorant Garamond", bodyFont: "DM Sans" },
    "editorial",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #B87333 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #B87333 18%, transparent)" },
      imageTreatment: {
        radius: "0.25rem",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #B87333 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #B87333 12%, transparent)",
      },
      motionIntensity: "expressive",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "prism",
    "Prism — Aurora",
    "تقنية متوهجة — gradient بنفسجي/أزرق، SaaS عالمي مشرق. للشركات الناشئة الطموحة.",
    {
      primary: "#6D28D9",
      secondary: "#3730A3",
      accent: "#A78BFA",
      background: "#FAFAFF",
      foreground: "#0F0A1E",
      radius: "1.25rem",
    },
    { headingFont: "Plus Jakarta Sans", bodyFont: "Inter" },
    "bento",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "1.25rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #A78BFA 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #A78BFA 12%, transparent)",
      },
      motionIntensity: "expressive",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "obsidian",
    "Obsidian — Noir",
    "فخامة سوداء — أسود عميق، ذهب، serif راقٍ. للساعات والمجوهرات والأزياء الراقية.",
    {
      primary: "#080808",
      secondary: "#141414",
      accent: "#C9A227",
      background: "#060606",
      foreground: "#F5F0E6",
      radius: "0",
    },
    { headingFont: "Cormorant Garamond", bodyFont: "Inter" },
    "editorial",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #C9A227 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #C9A227 18%, transparent)" },
      imageTreatment: {
        radius: "0",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #C9A227 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #C9A227 12%, transparent)",
      },
      motionIntensity: "subtle",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "pulse",
    "Pulse — Fintech",
    "فنتك عالمي — أخضر نيون، داكن، dashboard مالي. للمدفوعات والبنوك الرقمية.",
    {
      primary: "#021A14",
      secondary: "#063D2F",
      accent: "#10B981",
      background: "#010A08",
      foreground: "#ECFDF5",
      radius: "0.75rem",
    },
    { headingFont: "IBM Plex Sans", bodyFont: "IBM Plex Sans" },
    "bento",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #10B981 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #10B981 18%, transparent)" },
      imageTreatment: {
        radius: "0.75rem",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #10B981 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #10B981 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "forge",
    "Forge — Industrial",
    "صناعة عالمية — فولاذ وبرتقالي، B2B قوي. للتصنيع واللوجستيات والطاقة.",
    {
      primary: "#1C1917",
      secondary: "#44403C",
      accent: "#E85D04",
      background: "#F5F4F2",
      foreground: "#1C1917",
      radius: "0.25rem",
    },
    { headingFont: "Archivo", bodyFont: "Inter" },
    "card-first",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "0.25rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #E85D04 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #E85D04 12%, transparent)",
      },
      motionIntensity: "balanced",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "citadel",
    "Citadel — Trust",
    "قانون وحكومة — أزرق سلطة، داكن، ثقة مؤسسية. للمحاماة والقطاع العام والامتثال.",
    {
      primary: "#0A1F35",
      secondary: "#143050",
      accent: "#6B9DC4",
      background: "#060E18",
      foreground: "#E6EEF5",
      radius: "0.5rem",
    },
    { headingFont: "Libre Baskerville", bodyFont: "Source Sans 3" },
    "card-first",
    {
      shadows: { sm: "0 0 24px color-mix(in srgb, #6B9DC4 12%, transparent)", md: "0 32px 80px rgba(0,0,0,0.45)", lg: "0 0 120px color-mix(in srgb, #6B9DC4 18%, transparent)" },
      imageTreatment: {
        radius: "0.5rem",
        aspectRatio: "16 / 10",
        frame: "1px solid color-mix(in srgb, #6B9DC4 0.22, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #6B9DC4 12%, transparent)",
      },
      motionIntensity: "subtle",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
  base(
    "lumina",
    "Lumina — Wellness",
    "عافية وفخامة — وردي ناعم، أبيض دافئ، إحساس spa عالمي. للجمال والعافية ونمط الحياة.",
    {
      primary: "#4A3F55",
      secondary: "#6B5C7A",
      accent: "#E0A8AD",
      background: "#FFF8F6",
      foreground: "#2A2230",
      radius: "1.5rem",
    },
    { headingFont: "Fraunces", bodyFont: "Nunito Sans" },
    "minimal",
    {
      shadows: { sm: "0 2px 12px rgba(0,0,0,0.06)", md: "0 24px 64px rgba(0,0,0,0.1)", lg: "0 48px 96px rgba(0,0,0,0.12)" },
      imageTreatment: {
        radius: "1.5rem",
        aspectRatio: "4 / 3",
        frame: "1px solid color-mix(in srgb, #E0A8AD 0.14, transparent)",
        shadow: "0 0 48px color-mix(in srgb, #E0A8AD 12%, transparent)",
      },
      motionIntensity: "subtle",
      rtlTypography: { display: "Alexandria", body: "Noto Sans Arabic" },
      flagship: true,
    },
  ),
] as const;

export const DEFAULT_VISUAL_SKIN_ID = "signal";

/** @deprecated Retired flagship skins — kept for migration lookups only. */
export const LEGACY_VISUAL_SKIN_ALIASES: Record<string, string> = {
  sovereign: "signal",
  prestige: "volt",
};
