import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  BrainCircuit,
  Clapperboard,
  Contact,
  CreditCard,
  Building2,
  Briefcase,
  FileStack,
  FolderKanban,
  Globe2,
  History,
  Image,
  Key,
  LayoutDashboard,
  LayoutTemplate,
  Megaphone,
  Palette,
  PenLine,
  PieChart,
  Radar,
  SearchCheck,
  Settings,
  Sparkles,
  Shield,
  Smartphone,
  Users,
  type LucideIcon,
} from "lucide-react";

export type DashboardNavItem = {
  labelKey: string;
  descriptionKey?: string;
  /** English fallback for non-i18n contexts */
  label: string;
  href: string;
  icon: LucideIcon;
  description?: string;
};

/** Primary Phase-3 sidebar sections */
export const DASHBOARD_PRIMARY_NAV: DashboardNavItem[] = [
  {
    labelKey: "nav.dashboard",
    descriptionKey: "navDescriptions.dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    description: "Overview and quick actions",
  },
  {
    labelKey: "nav.projects",
    descriptionKey: "navDescriptions.projects",
    label: "Projects",
    href: "/dashboard/projects",
    icon: FolderKanban,
    description: "All generated projects",
  },
  {
    labelKey: "nav.crm",
    descriptionKey: "navDescriptions.crm",
    label: "CRM",
    href: "/dashboard/crm",
    icon: Contact,
    description: "Sales pipeline, contacts, and deals",
  },
  {
    labelKey: "nav.erp",
    descriptionKey: "navDescriptions.erp",
    label: "ERP",
    href: "/dashboard/erp",
    icon: Building2,
    description: "Finance, inventory, operations, and HR",
  },
  {
    labelKey: "nav.businessIntelligence",
    descriptionKey: "navDescriptions.businessIntelligence",
    label: "Business Intelligence",
    href: "/dashboard/bi",
    icon: PieChart,
    description: "Analytics dashboards, metrics, and AI insights",
  },
  {
    labelKey: "nav.businessManager",
    descriptionKey: "navDescriptions.businessManager",
    label: "Business Manager",
    href: "/dashboard/business-manager",
    icon: Briefcase,
    description: "Projects, teams, tasks, workflows, and KPIs",
  },
  {
    labelKey: "nav.cybersecurity",
    descriptionKey: "navDescriptions.cybersecurity",
    label: "Cybersecurity",
    href: "/dashboard/cybersecurity",
    icon: Shield,
    description: "Threat intelligence, monitoring, and incident response",
  },
];

/** AI Products group — expandable in sidebar */
export const DASHBOARD_AI_PRODUCTS_NAV: DashboardNavItem[] = [
  {
    labelKey: "nav.websiteBuilder",
    descriptionKey: "navDescriptions.websiteBuilder",
    label: "Website Builder",
    href: "/dashboard/website-builder",
    icon: Globe2,
    description: "Full website blueprints",
  },
  {
    labelKey: "nav.landingPages",
    descriptionKey: "navDescriptions.landingPages",
    label: "Landing Pages",
    href: "/dashboard/landing-page-builder",
    icon: LayoutTemplate,
    description: "High-converting landing pages",
  },
  {
    labelKey: "nav.webAppBuilder",
    descriptionKey: "navDescriptions.webAppBuilder",
    label: "Web App Builder",
    href: "/dashboard/app-builder",
    icon: Smartphone,
    description: "Full-stack web applications",
  },
  {
    labelKey: "nav.logoDesigner",
    descriptionKey: "navDescriptions.logoDesigner",
    label: "Logo Designer",
    href: "/dashboard/logo-maker",
    icon: Sparkles,
    description: "Professional logo marks and brand symbols",
  },
  {
    labelKey: "nav.brandIdentity",
    descriptionKey: "navDescriptions.brandIdentity",
    label: "Brand Identity",
    href: "/dashboard/brand-studio",
    icon: Palette,
    description: "Complete brand identity systems",
  },
  {
    labelKey: "nav.imageGenerator",
    descriptionKey: "navDescriptions.imageGenerator",
    label: "Image Generator",
    href: "/dashboard/image-generator",
    icon: Image,
    description: "Visual concepts and image assets",
  },
  {
    labelKey: "nav.videoStudio",
    descriptionKey: "navDescriptions.videoStudio",
    label: "Video Studio",
    href: "/dashboard/video-studio",
    icon: Clapperboard,
    description: "AI video production and storyboards",
  },
  {
    labelKey: "nav.contentStudio",
    descriptionKey: "navDescriptions.contentStudio",
    label: "Content Studio",
    href: "/dashboard/content-studio",
    icon: PenLine,
    description: "AI content creation and calendar",
  },
  {
    labelKey: "nav.socialMedia",
    descriptionKey: "navDescriptions.socialMedia",
    label: "Social Media",
    href: "/dashboard/social-media",
    icon: Smartphone,
    description: "Channel planning",
  },
  {
    labelKey: "nav.marketingStrategy",
    descriptionKey: "navDescriptions.marketingStrategy",
    label: "Marketing Strategy",
    href: "/dashboard/marketing",
    icon: Megaphone,
    description: "Campaigns and funnels",
  },
  {
    labelKey: "nav.businessSuite",
    descriptionKey: "navDescriptions.businessSuite",
    label: "Business Suite",
    href: "/dashboard/business-intelligence",
    icon: BarChart3,
    description: "AI business intelligence and strategy",
  },
  {
    labelKey: "nav.feasibilityStudy",
    descriptionKey: "navDescriptions.feasibilityStudy",
    label: "Feasibility Study",
    href: "/dashboard/feasibility-study",
    icon: SearchCheck,
    description: "Go / no-go assessments",
  },
  {
    labelKey: "nav.aiAgents",
    descriptionKey: "navDescriptions.aiAgents",
    label: "AI Agents",
    href: "/dashboard/ai-agents",
    icon: Bot,
    description: "Intelligent agents and automation workflows",
  },
];

export const DASHBOARD_SECONDARY_NAV: DashboardNavItem[] = [
  {
    labelKey: "nav.templates",
    descriptionKey: "navDescriptions.templates",
    label: "Templates",
    href: "/dashboard/templates",
    icon: LayoutTemplate,
    description: "Creator template marketplace",
  },
  {
    labelKey: "nav.history",
    descriptionKey: "navDescriptions.history",
    label: "History",
    href: "/dashboard/history",
    icon: History,
    description: "All generations",
  },
  {
    labelKey: "nav.files",
    descriptionKey: "navDescriptions.files",
    label: "Files",
    href: "/dashboard/files",
    icon: FileStack,
    description: "Exports and assets",
  },
  {
    labelKey: "nav.analytics",
    descriptionKey: "navDescriptions.analytics",
    label: "Analytics",
    href: "/dashboard/analytics",
    icon: BarChart3,
    description: "Usage and insights",
  },
  {
    labelKey: "nav.seoEngine",
    descriptionKey: "navDescriptions.seoEngine",
    label: "SEO Engine",
    href: "/dashboard/seo",
    icon: SearchCheck,
    description: "SEO health and analyzer",
  },
  {
    labelKey: "nav.aiSearchCenter",
    descriptionKey: "navDescriptions.aiSearchCenter",
    label: "AI Search Center",
    href: "/dashboard/ai-search",
    icon: Radar,
    description: "AEO, GEO and AI search domination",
  },
  {
    labelKey: "nav.growthEngine",
    descriptionKey: "navDescriptions.growthEngine",
    label: "Growth Engine",
    href: "/dashboard/growth",
    icon: Megaphone,
    description: "Affiliates, CRM and campaigns",
  },
  {
    labelKey: "nav.billing",
    descriptionKey: "navDescriptions.billing",
    label: "Billing",
    href: "/dashboard/billing",
    icon: CreditCard,
    description: "Plan and invoices",
  },
  {
    labelKey: "nav.aiProviders",
    descriptionKey: "navDescriptions.aiProviders",
    label: "AI Providers",
    href: "/dashboard/ai-providers",
    icon: BrainCircuit,
    description: "Manage AI provider keys and models",
  },
  {
    labelKey: "nav.team",
    descriptionKey: "navDescriptions.team",
    label: "Team",
    href: "/dashboard/team",
    icon: Users,
    description: "Team members and invitations",
  },
  {
    labelKey: "nav.notifications",
    descriptionKey: "navDescriptions.notifications",
    label: "Notifications",
    href: "/dashboard/notifications",
    icon: Bell,
    description: "Alerts and updates",
  },
  {
    labelKey: "nav.apiKeys",
    descriptionKey: "navDescriptions.apiKeys",
    label: "API Keys",
    href: "/dashboard/api-keys",
    icon: Key,
    description: "Manage API access keys",
  },
  {
    labelKey: "nav.usage",
    descriptionKey: "navDescriptions.usage",
    label: "Usage",
    href: "/dashboard/usage",
    icon: Activity,
    description: "Track AI usage and tokens",
  },
  {
    labelKey: "nav.settings",
    descriptionKey: "navDescriptions.settings",
    label: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
    description: "Workspace preferences",
  },
];

/** Flat list for search / overview grids (backward compatible) */
export const DASHBOARD_NAV: DashboardNavItem[] = [
  ...DASHBOARD_PRIMARY_NAV,
  ...DASHBOARD_AI_PRODUCTS_NAV.map((item) => ({
    ...item,
    label: item.label.startsWith("AI ") ? item.label : `AI ${item.label}`,
  })),
  ...DASHBOARD_SECONDARY_NAV,
];

export const DASHBOARD_QUICK_ACTIONS = [
  {
    titleKey: "quickActions.websiteBuilder.title",
    descriptionKey: "quickActions.websiteBuilder.description",
    title: "Website Builder",
    description: "Build pages and site blueprints",
    href: "/dashboard/website-builder",
    icon: Globe2,
  },
  {
    titleKey: "quickActions.landingPage.title",
    descriptionKey: "quickActions.landingPage.description",
    title: "Landing Page",
    description: "Generate conversion-focused pages",
    href: "/dashboard/landing-page-builder",
    icon: LayoutTemplate,
  },
  {
    titleKey: "quickActions.webAppBuilder.title",
    descriptionKey: "quickActions.webAppBuilder.description",
    title: "Web App Builder",
    description: "Generate full-stack web applications",
    href: "/dashboard/app-builder",
    icon: Smartphone,
  },
  {
    titleKey: "quickActions.logoDesigner.title",
    descriptionKey: "quickActions.logoDesigner.description",
    title: "Logo Designer",
    description: "Professional logo marks and symbols",
    href: "/dashboard/logo-maker",
    icon: Sparkles,
  },
  {
    titleKey: "quickActions.brandIdentity.title",
    descriptionKey: "quickActions.brandIdentity.description",
    title: "Brand Identity",
    description: "Complete brand identity systems",
    href: "/dashboard/brand-studio",
    icon: Palette,
  },
  {
    titleKey: "quickActions.imageGenerator.title",
    descriptionKey: "quickActions.imageGenerator.description",
    title: "Image Generator",
    description: "Visual concepts and image assets",
    href: "/dashboard/image-generator",
    icon: Image,
  },
  {
    titleKey: "quickActions.videoStudio.title",
    descriptionKey: "quickActions.videoStudio.description",
    title: "Video Studio",
    description: "Produce AI video storyboards and scripts",
    href: "/dashboard/video-studio",
    icon: Clapperboard,
  },
  {
    titleKey: "quickActions.contentStudio.title",
    descriptionKey: "quickActions.contentStudio.description",
    title: "Content Studio",
    description: "Create and schedule AI content",
    href: "/dashboard/content-studio",
    icon: PenLine,
  },
  {
    titleKey: "quickActions.marketingStrategy.title",
    descriptionKey: "quickActions.marketingStrategy.description",
    title: "Marketing Strategy",
    description: "Campaign angles and offers",
    href: "/dashboard/marketing",
    icon: Megaphone,
  },
  {
    titleKey: "quickActions.businessSuite.title",
    descriptionKey: "quickActions.businessSuite.description",
    title: "Business Suite",
    description: "AI planning, analysis and strategy",
    href: "/dashboard/business-intelligence",
    icon: BarChart3,
  },
  {
    titleKey: "quickActions.feasibilityStudy.title",
    descriptionKey: "quickActions.feasibilityStudy.description",
    title: "Feasibility Study",
    description: "Go / no-go opportunity audits",
    href: "/dashboard/feasibility-study",
    icon: SearchCheck,
  },
  {
    titleKey: "quickActions.aiAgents.title",
    descriptionKey: "quickActions.aiAgents.description",
    title: "AI Agents",
    description: "Create and run AI agents and workflows",
    href: "/dashboard/ai-agents",
    icon: Bot,
  },
] as const;

export const DASHBOARD_STATS = [
  { label: "Ideas Generated", key: "ideas" as const },
  { label: "Market Analyses", key: "analyses" as const },
  { label: "AI Reports", key: "reports" as const },
  { label: "Website Blueprints", key: "websites" as const },
  { label: "AI Workspaces", key: "workspaces" as const },
  { label: "Saved Items", key: "saved" as const },
];

export const DASHBOARD_WORKSPACES = [
  { id: "personal", name: "Personal", plan: "Free Beta" },
  { id: "team", name: "Team Workspace", plan: "Free Beta" },
] as const;
