/**
 * Deterministic runtime modules for App Builder — shared by scaffold (pre-LLM)
 * and hardener upserts (post-LLM). Never generated by DeepSeek.
 */

export {
  buildCanonicalAuthLoginRoute,
  buildCanonicalAuthLogoutRoute,
  buildCanonicalLoginPage,
} from "@/lib/ai/webapp-auth-scaffold";

export function buildCanonicalDbModule(): string {
  return `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const db = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = db;
}
`;
}

export function buildCanonicalMiddleware(): string {
  return `import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { verifySessionCookie } from "@/lib/session-cookie";
import { t } from "@/lib/i18n";

const STAFF_ROLES = new Set(["admin", "manager", "employee"]);

function clearSessionCookies(response: NextResponse) {
  response.cookies.delete("session");
  response.cookies.delete("app_session");
  response.cookies.delete("session_role");
  return response;
}

export async function middleware(request: NextRequest) {
  const cookieValue =
    request.cookies.get("session")?.value ??
    request.cookies.get("app_session")?.value;
  const claims = await verifySessionCookie(cookieValue);
  const path = request.nextUrl.pathname;
  const method = request.method.toUpperCase();
  const isAuthApi = path.startsWith("/api/auth/");
  const isProtectedPage = path.startsWith("/dashboard") || path.startsWith("/app");
  const isProtectedApi = path.startsWith("/api/") && !isAuthApi;
  const isAuthPage = path === "/login" || path === "/signup";
  const isAdminPage = path.startsWith("/dashboard/admin");

  if ((isProtectedPage || isProtectedApi) && !claims) {
    if (isProtectedApi) {
      return clearSessionCookies(
        NextResponse.json({ error: t("middleware.unauthorized") }, { status: 401 }),
      );
    }
    return clearSessionCookies(
      NextResponse.redirect(new URL("/login", request.url)),
    );
  }

  if (
    isProtectedApi &&
    ["POST", "PATCH", "PUT", "DELETE"].includes(method) &&
    !claims?.role
  ) {
    return NextResponse.json({ error: t("middleware.forbidden") }, { status: 403 });
  }

  if (isAdminPage && (!claims || !STAFF_ROLES.has(claims.role))) {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }

  if (claims && isAuthPage) {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }
  return NextResponse.next();
}

export const config = {
  matcher: [
    "/dashboard/:path*",
    "/app/:path*",
    "/api/:path*",
    "/login",
    "/signup",
  ],
};
`;
}

export function buildCanonicalHomePage(options: {
  requiresDashboard?: boolean;
  requiresAuth?: boolean;
}): string {
  const target = options.requiresDashboard
    ? "/dashboard"
    : options.requiresAuth
      ? "/login"
      : "/dashboard";
  return `import { redirect } from "next/navigation";

export default function HomePage() {
  redirect("${target}");
}
`;
}

export function buildCanonicalRootLayout(title: string): string {
  return `import type { Metadata, Viewport } from "next";
import { Providers } from "@/app/providers";
import { PwaRegister } from "@/app/pwa-register";
import { locale, t } from "@/lib/i18n";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: t("meta.description"),
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: ${JSON.stringify(title)},
  },
  applicationName: ${JSON.stringify(title)},
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#0f172a",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={locale.htmlLang} dir={locale.dir} data-scroll-behavior="smooth">
      <body className="min-h-screen bg-background text-foreground antialiased">
        <PwaRegister />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
`;
}

export function buildCanonicalDashboardPage(options: {
  title: string;
  entityLinks?: Array<{ entity: string; href: string }>;
}): string {
  const titleLiteral = JSON.stringify(options.title);
  const entityNav = (options.entityLinks ?? []).map((link) => ({
    entity: link.entity,
    href: link.href,
  }));
  const entityNavLiteral = JSON.stringify(entityNav);

  return `import Link from "next/link";
import { t, te } from "@/lib/i18n";

const TITLE = ${titleLiteral};
const ENTITY_NAV = ${entityNavLiteral} as Array<{ entity: string; href: string }>;

export default function DashboardPage() {
  return (
    <main className="mx-auto max-w-5xl space-y-6 p-8">
      <header className="space-y-1">
        <h1 className="text-3xl font-semibold tracking-tight">{TITLE}</h1>
        <p className="text-muted-foreground">{t("dashboard.overviewSubtitle")}</p>
      </header>
      {ENTITY_NAV.length === 0 ? (
        <p className="text-muted-foreground">{t("dashboard.emptyHint")}</p>
      ) : (
        <ul className="grid gap-3 sm:grid-cols-2">
          {ENTITY_NAV.map((link) => (
            <li key={link.href}>
              <Link
                href={link.href}
                className="block rounded-xl border bg-card p-4 shadow-sm transition hover:border-primary"
              >
                <span className="font-medium">{te(link.entity)}</span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
`;
}
