/**
 * Deterministic runtime modules for App Builder — shared by scaffold (pre-LLM)
 * and hardener upserts (post-LLM). Never generated by DeepSeek.
 */

export {
  buildCanonicalAuthLoginRoute,
  buildCanonicalAuthLogoutRoute,
  buildCanonicalLoginPage,
} from "@/lib/ai/webapp-auth-scaffold";

export function buildCanonicalDbModule(): string {
  return `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const db = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = db;
}
`;
}

export function buildCanonicalMiddleware(): string {
  return `import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(request: NextRequest) {
  const session =
    request.cookies.get("session")?.value ??
    request.cookies.get("app_session")?.value;
  const path = request.nextUrl.pathname;
  const isProtected = path.startsWith("/dashboard") || path.startsWith("/app");
  const isAuthPage = path === "/login" || path === "/signup";

  if (!session && isProtected) {
    return NextResponse.redirect(new URL("/login", request.url));
  }
  if (session && isAuthPage) {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }
  return NextResponse.next();
}

export const config = {
  matcher: ["/dashboard/:path*", "/app/:path*", "/login", "/signup"],
};
`;
}

export function buildCanonicalHomePage(options: {
  requiresDashboard?: boolean;
  requiresAuth?: boolean;
}): string {
  const target = options.requiresDashboard
    ? "/dashboard"
    : options.requiresAuth
      ? "/login"
      : "/dashboard";
  return `import { redirect } from "next/navigation";

export default function HomePage() {
  redirect("${target}");
}
`;
}

export function buildCanonicalRootLayout(title: string): string {
  return `import type { Metadata } from "next";
import { Providers } from "@/app/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: "Production web application generated by Trend Business AI.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className="min-h-screen bg-background text-foreground antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
`;
}

export function buildCanonicalDashboardPage(options: {
  title: string;
  entityLinks?: Array<{ label: string; href: string }>;
}): string {
  const titleLiteral = JSON.stringify(options.title);
  const linksLiteral = JSON.stringify(options.entityLinks ?? []);

  return `import Link from "next/link";

const TITLE = ${titleLiteral};
const ENTITY_LINKS = ${linksLiteral} as Array<{ label: string; href: string }>;

export default function DashboardPage() {
  return (
    <main className="mx-auto max-w-5xl space-y-6 p-8">
      <header className="space-y-1">
        <h1 className="text-3xl font-semibold tracking-tight">{TITLE}</h1>
        <p className="text-muted-foreground">Overview of your workspace.</p>
      </header>
      {ENTITY_LINKS.length === 0 ? (
        <p className="text-muted-foreground">Use the navigation to manage your records.</p>
      ) : (
        <ul className="grid gap-3 sm:grid-cols-2">
          {ENTITY_LINKS.map((link) => (
            <li key={link.href}>
              <Link
                href={link.href}
                className="block rounded-xl border bg-card p-4 shadow-sm transition hover:border-primary"
              >
                <span className="font-medium">{link.label}</span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
`;
}
