import { generateColorHarmony } from "@/lib/ai-core/design-system/premium/color-harmony";
import type {
  PremiumDesignSystem,
  PremiumStyleId,
} from "@/lib/ai-core/design-system/premium/types";
import type { DesignPresetId } from "@/lib/ai-core/design-system/types";

type StyleBase = Omit<PremiumDesignSystem, "colors" | "brandSummary"> & {
  seed: { primary: string; secondary: string; accent: string; background: string; dark?: boolean };
};

const SHARED_RESPONSIVE = {
  breakpoints: { sm: "640px", md: "768px", lg: "1024px", xl: "1280px" },
  containerPadding: { mobile: "1.25rem", tablet: "1.75rem", desktop: "2.5rem" },
  typographyScale: { mobile: "0.95", desktop: "1" },
  gridColumns: { mobile: 1, tablet: 2, desktop: 3 },
  heroMinHeight: { mobile: "72vh", desktop: "88vh" },
  rules: [
    "Mobile-first: stack sections before md:",
    "Hero min-height shrinks on small screens; keep CTA visible",
    "Card grids: 1 → 2 → 3 columns across breakpoints",
    "Navigation collapses to compact bar under md",
  ],
};

const PREMIUM_STYLE_BASES: Record<PremiumStyleId, StyleBase> = {
  luxury: {
    styleId: "luxury",
    enginePreset: "luxury",
    label: "Luxury",
    seed: {
      primary: "#D4AF37",
      secondary: "#1A1A1A",
      accent: "#C9A227",
      background: "#0A0A0A",
      dark: true,
    },
    typography: {
      displayFont: "Playfair Display",
      headingFont: "Playfair Display",
      bodyFont: "Source Sans 3",
      monoFont: "IBM Plex Mono",
      weights: { display: 600, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.05", heading: "1.15", body: "1.65" },
      tracking: { display: "-0.03em", heading: "-0.02em", body: "0" },
      scale: {
        display: "clamp(2.75rem, 6vw, 4.5rem)",
        h1: "clamp(2.25rem, 4vw, 3.5rem)",
        h2: "clamp(1.75rem, 3vw, 2.25rem)",
        h3: "1.35rem",
        body: "1.0625rem",
        small: "0.875rem",
      },
      notes: "Serif display + refined sans — editorial luxury",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        "2xl": "4rem",
        "3xl": "6rem",
      },
      sectionY: "6.5rem",
      sectionYMobile: "4rem",
      containerMax: "72rem",
      gutter: "1.5rem",
      stack: "1.25rem",
      notes: "Generous editorial whitespace",
    },
    radius: {
      none: "0",
      sm: "0.35rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.5rem",
      full: "9999px",
      default: "0.75rem",
    },
    shadows: {
      none: "none",
      sm: "0 4px 16px rgb(0 0 0 / 0.25)",
      md: "0 12px 40px rgb(0 0 0 / 0.35)",
      lg: "0 24px 80px rgb(0 0 0 / 0.45)",
      xl: "0 40px 120px rgb(0 0 0 / 0.55)",
      glow: "0 0 40px rgb(212 175 55 / 0.28)",
      default: "0 12px 40px rgb(0 0 0 / 0.35)",
      notes: "Soft gold glow on CTAs and cards",
    },
    gradients: {
      hero: "linear-gradient(135deg, rgb(10 10 10 / 0.2), rgb(10 10 10 / 0.75))",
      cta: "linear-gradient(135deg, #D4AF37, #C9A227)",
      surface: "linear-gradient(180deg, rgb(255 255 255 / 0.04), transparent)",
      accent: "radial-gradient(circle at 20% 20%, rgb(212 175 55 / 0.25), transparent 55%)",
      mesh: "radial-gradient(at 10% 20%, rgb(212 175 55 / 0.15), transparent 40%)",
      notes: "Cinematic dark overlays + gold accents",
    },
    glass: {
      enabled: true,
      background: "rgb(255 255 255 / 0.06)",
      border: "1px solid rgb(212 175 55 / 0.28)",
      blur: "16px",
      saturate: "140%",
      notes: "Dark glass panels with thin gold borders",
    },
    animation: {
      motion: "subtle",
      easing: "cubic-bezier(0.22, 1, 0.36, 1)",
      durationFast: "220ms",
      duration: "600ms",
      durationSlow: "900ms",
      entrances: ["fade-up", "slow-reveal"],
      hover: "lift-soft",
      pageTransition: "fade",
      notes: "Slow premium reveals — never busy",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "full-bleed-cinematic",
      sectionLayout: "editorial-asymmetric",
      cardStyle: "glass-bordered",
      navigationStyle: "minimal-logo-led",
      footerStyle: "multi-column-quiet",
      ctaStyle: "solid-gold-pill",
      density: "airy",
      rules: [
        "Full-bleed hero only — no inset hero cards",
        "Gold accent CTAs with quiet ghost secondary",
        "Glass/dark panels for proof and galleries",
      ],
    },
  },
  modern: {
    styleId: "modern",
    enginePreset: "modern",
    label: "Modern",
    seed: {
      primary: "#2563EB",
      secondary: "#0F172A",
      accent: "#22D3EE",
      background: "#FFFFFF",
      dark: false,
    },
    typography: {
      displayFont: "Space Grotesk",
      headingFont: "Space Grotesk",
      bodyFont: "IBM Plex Sans",
      monoFont: "IBM Plex Mono",
      weights: { display: 700, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.05", heading: "1.2", body: "1.6" },
      tracking: { display: "-0.04em", heading: "-0.02em", body: "0" },
      scale: {
        display: "clamp(2.5rem, 5vw, 4rem)",
        h1: "clamp(2rem, 3.5vw, 3rem)",
        h2: "clamp(1.5rem, 2.5vw, 2rem)",
        h3: "1.25rem",
        body: "1rem",
        small: "0.875rem",
      },
      notes: "Geometric product UI typography",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "0.875rem",
        lg: "1.25rem",
        xl: "2rem",
        "2xl": "3.5rem",
        "3xl": "5rem",
      },
      sectionY: "5rem",
      sectionYMobile: "3.25rem",
      containerMax: "72rem",
      gutter: "1.25rem",
      stack: "1rem",
      notes: "Product marketing rhythm",
    },
    radius: {
      none: "0",
      sm: "0.5rem",
      md: "0.85rem",
      lg: "1.15rem",
      xl: "1.5rem",
      full: "9999px",
      default: "1rem",
    },
    shadows: {
      none: "none",
      sm: "0 2px 8px rgb(15 23 42 / 0.06)",
      md: "0 10px 30px rgb(15 23 42 / 0.1)",
      lg: "0 20px 50px rgb(15 23 42 / 0.14)",
      xl: "0 32px 80px rgb(15 23 42 / 0.18)",
      glow: "0 0 32px rgb(37 99 235 / 0.25)",
      default: "0 10px 30px rgb(15 23 42 / 0.1)",
      notes: "Soft elevated product shadows",
    },
    gradients: {
      hero: "linear-gradient(160deg, #EFF6FF 0%, #FFFFFF 55%, #ECFEFF 100%)",
      cta: "linear-gradient(135deg, #2563EB, #0891B2)",
      surface: "linear-gradient(180deg, #F8FAFC, #FFFFFF)",
      accent: "radial-gradient(circle at 80% 10%, rgb(34 211 238 / 0.25), transparent 50%)",
      notes: "Cool product washes",
    },
    glass: {
      enabled: true,
      background: "rgb(255 255 255 / 0.72)",
      border: "1px solid rgb(15 23 42 / 0.08)",
      blur: "12px",
      saturate: "160%",
      notes: "Light frosted nav/cards",
    },
    animation: {
      motion: "subtle",
      easing: "ease-out",
      durationFast: "180ms",
      duration: "400ms",
      durationSlow: "700ms",
      entrances: ["fade-up", "stagger-cards"],
      hover: "lift",
      pageTransition: "fade",
      notes: "Crisp micro-interactions",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "split-product",
      sectionLayout: "bento-grid",
      cardStyle: "elevated-soft",
      navigationStyle: "sticky-product-cta",
      footerStyle: "compact-product",
      ctaStyle: "filled-primary",
      density: "balanced",
      rules: [
        "Card grids with clear hierarchy",
        "High-contrast primary CTAs",
        "Bento features for capability storytelling",
      ],
    },
  },
  minimal: {
    styleId: "minimal",
    enginePreset: "minimal",
    label: "Minimal",
    seed: {
      primary: "#111111",
      secondary: "#525252",
      accent: "#171717",
      background: "#FAFAFA",
      dark: false,
    },
    typography: {
      displayFont: "Instrument Sans",
      headingFont: "Instrument Sans",
      bodyFont: "Instrument Sans",
      monoFont: "IBM Plex Mono",
      weights: { display: 500, heading: 500, body: 400, medium: 500 },
      lineHeights: { display: "1.1", heading: "1.2", body: "1.7" },
      tracking: { display: "-0.02em", heading: "-0.01em", body: "0.01em" },
      scale: {
        display: "clamp(2.25rem, 4vw, 3.5rem)",
        h1: "clamp(1.85rem, 3vw, 2.75rem)",
        h2: "1.5rem",
        h3: "1.2rem",
        body: "1.05rem",
        small: "0.875rem",
      },
      notes: "Single-family restraint, quiet confidence",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.75rem",
        xl: "3rem",
        "2xl": "4.5rem",
        "3xl": "7rem",
      },
      sectionY: "5.5rem",
      sectionYMobile: "3.5rem",
      containerMax: "68rem",
      gutter: "1.25rem",
      stack: "1.15rem",
      notes: "Airy minimal rhythm",
    },
    radius: {
      none: "0",
      sm: "0.25rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      full: "9999px",
      default: "0.5rem",
    },
    shadows: {
      none: "none",
      sm: "0 1px 2px rgb(0 0 0 / 0.04)",
      md: "0 4px 16px rgb(0 0 0 / 0.06)",
      lg: "0 12px 32px rgb(0 0 0 / 0.08)",
      xl: "0 24px 48px rgb(0 0 0 / 0.1)",
      glow: "none",
      default: "0 4px 16px rgb(0 0 0 / 0.06)",
      notes: "Near-flat shadows",
    },
    gradients: {
      hero: "linear-gradient(180deg, #FFFFFF, #FAFAFA)",
      cta: "linear-gradient(135deg, #111111, #404040)",
      surface: "linear-gradient(180deg, #FFFFFF, #F5F5F5)",
      accent: "none",
      notes: "Almost no gradient — purity first",
    },
    glass: {
      enabled: false,
      background: "rgb(255 255 255 / 0.85)",
      border: "1px solid rgb(0 0 0 / 0.06)",
      blur: "8px",
      saturate: "100%",
      notes: "Glass off — solid quiet surfaces",
    },
    animation: {
      motion: "subtle",
      easing: "ease",
      durationFast: "160ms",
      duration: "350ms",
      durationSlow: "600ms",
      entrances: ["fade"],
      hover: "opacity",
      pageTransition: "fade",
      notes: "Barely-there motion",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "centered-quiet",
      sectionLayout: "single-column-editorial",
      cardStyle: "border-only",
      navigationStyle: "hairline-minimal",
      footerStyle: "single-line-quiet",
      ctaStyle: "solid-ink",
      density: "airy",
      rules: [
        "Whitespace is the primary design material",
        "Avoid decorative gradients and glow",
        "One strong CTA per viewport",
      ],
    },
  },
  corporate: {
    styleId: "corporate",
    enginePreset: "corporate",
    label: "Corporate",
    seed: {
      primary: "#1E3A5F",
      secondary: "#334155",
      accent: "#0EA5E9",
      background: "#F8FAFC",
      dark: false,
    },
    typography: {
      displayFont: "Source Serif 4",
      headingFont: "Source Serif 4",
      bodyFont: "Source Sans 3",
      monoFont: "IBM Plex Mono",
      weights: { display: 600, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.15", heading: "1.25", body: "1.65" },
      tracking: { display: "-0.015em", heading: "-0.01em", body: "0" },
      scale: {
        display: "clamp(2.25rem, 4vw, 3.25rem)",
        h1: "clamp(1.9rem, 3vw, 2.75rem)",
        h2: "1.6rem",
        h3: "1.25rem",
        body: "1.05rem",
        small: "0.875rem",
      },
      notes: "Trustworthy serif + clear sans",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.25rem",
        "2xl": "3.5rem",
        "3xl": "5rem",
      },
      sectionY: "5rem",
      sectionYMobile: "3.25rem",
      containerMax: "70rem",
      gutter: "1.5rem",
      stack: "1rem",
      notes: "Balanced corporate rhythm",
    },
    radius: {
      none: "0",
      sm: "0.35rem",
      md: "0.6rem",
      lg: "0.85rem",
      xl: "1.1rem",
      full: "9999px",
      default: "0.6rem",
    },
    shadows: {
      none: "none",
      sm: "0 2px 6px rgb(30 58 95 / 0.08)",
      md: "0 8px 24px rgb(30 58 95 / 0.1)",
      lg: "0 16px 40px rgb(30 58 95 / 0.12)",
      xl: "0 28px 64px rgb(30 58 95 / 0.14)",
      glow: "0 0 24px rgb(14 165 233 / 0.2)",
      default: "0 8px 24px rgb(30 58 95 / 0.1)",
      notes: "Trust-building soft elevation",
    },
    gradients: {
      hero: "linear-gradient(135deg, #1E3A5F 0%, #0F172A 55%, #0EA5E9 140%)",
      cta: "linear-gradient(135deg, #0EA5E9, #0284C7)",
      surface: "linear-gradient(180deg, #FFFFFF, #F1F5F9)",
      accent: "radial-gradient(circle at 0% 0%, rgb(14 165 233 / 0.18), transparent 45%)",
      notes: "Navy trust gradients with sky accent",
    },
    glass: {
      enabled: true,
      background: "rgb(255 255 255 / 0.78)",
      border: "1px solid rgb(30 58 95 / 0.1)",
      blur: "10px",
      saturate: "120%",
      notes: "Subtle frosted panels for trust modules",
    },
    animation: {
      motion: "subtle",
      easing: "ease-out",
      durationFast: "180ms",
      duration: "420ms",
      durationSlow: "700ms",
      entrances: ["fade-up"],
      hover: "lift-soft",
      pageTransition: "fade",
      notes: "Conservative professional motion",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "trust-split",
      sectionLayout: "symmetric-grid",
      cardStyle: "elevated-trust",
      navigationStyle: "corporate-topbar",
      footerStyle: "multi-column-legal",
      ctaStyle: "solid-sky",
      density: "balanced",
      rules: [
        "Clear hierarchy and readable trust copy",
        "Symmetric grids for services and proof",
        "Accessible contrast on all CTAs",
      ],
    },
  },
  futuristic: {
    styleId: "futuristic",
    enginePreset: "tech",
    label: "Futuristic",
    seed: {
      primary: "#22D3EE",
      secondary: "#6366F1",
      accent: "#A5F3FC",
      background: "#020617",
      dark: true,
    },
    typography: {
      displayFont: "Space Grotesk",
      headingFont: "Space Grotesk",
      bodyFont: "IBM Plex Sans",
      monoFont: "JetBrains Mono",
      weights: { display: 700, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.05", heading: "1.15", body: "1.6" },
      tracking: { display: "-0.04em", heading: "-0.02em", body: "0" },
      scale: {
        display: "clamp(2.6rem, 5.5vw, 4.25rem)",
        h1: "clamp(2.1rem, 4vw, 3.25rem)",
        h2: "1.65rem",
        h3: "1.25rem",
        body: "1rem",
        small: "0.85rem",
      },
      notes: "Tech futurist — geometric + mono accents",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "0.875rem",
        lg: "1.25rem",
        xl: "2rem",
        "2xl": "3.25rem",
        "3xl": "5rem",
      },
      sectionY: "5rem",
      sectionYMobile: "3.25rem",
      containerMax: "72rem",
      gutter: "1.25rem",
      stack: "0.9rem",
      notes: "Dense product/tech marketing rhythm",
    },
    radius: {
      none: "0",
      sm: "0.4rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.25rem",
      full: "9999px",
      default: "0.75rem",
    },
    shadows: {
      none: "none",
      sm: "0 4px 16px rgb(2 6 23 / 0.5)",
      md: "0 12px 40px rgb(2 6 23 / 0.65)",
      lg: "0 24px 70px rgb(2 6 23 / 0.75)",
      xl: "0 40px 100px rgb(2 6 23 / 0.85)",
      glow: "0 0 36px rgb(34 211 238 / 0.35)",
      default: "0 12px 40px rgb(2 6 23 / 0.65)",
      notes: "Cyan soft glow on interactive surfaces",
    },
    gradients: {
      hero: "linear-gradient(145deg, #020617 0%, #0F172A 45%, #1E1B4B 100%)",
      cta: "linear-gradient(135deg, #22D3EE, #6366F1)",
      surface: "linear-gradient(180deg, rgb(255 255 255 / 0.04), transparent)",
      accent: "radial-gradient(circle at 70% 20%, rgb(34 211 238 / 0.28), transparent 50%)",
      mesh: "radial-gradient(at 20% 80%, rgb(99 102 241 / 0.25), transparent 40%)",
      notes: "Dark neon mesh + cyan/indigo accents",
    },
    glass: {
      enabled: true,
      background: "rgb(15 23 42 / 0.55)",
      border: "1px solid rgb(165 243 252 / 0.18)",
      blur: "18px",
      saturate: "160%",
      notes: "Dark glass panels with hairline neon borders",
    },
    animation: {
      motion: "subtle",
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      durationFast: "160ms",
      duration: "450ms",
      durationSlow: "750ms",
      entrances: ["fade-up", "glow-in"],
      hover: "glow",
      pageTransition: "fade",
      notes: "Precise product motion, subtle glow",
    },
    responsive: {
      ...SHARED_RESPONSIVE,
      heroMinHeight: { mobile: "78vh", desktop: "92vh" },
    },
    layout: {
      heroStyle: "dark-product-frame",
      sectionLayout: "tech-bento",
      cardStyle: "dark-glass",
      navigationStyle: "compact-tech-sticky",
      footerStyle: "dark-compact",
      ctaStyle: "glow-cyan",
      density: "compact",
      rules: [
        "Dark full-bleed hero with product UI frame",
        "Glass cards with cyan glow CTAs",
        "Prefer monospace accents for tech credibility",
      ],
    },
  },
  creative: {
    styleId: "creative",
    enginePreset: "creative",
    label: "Creative",
    seed: {
      primary: "#E11D48",
      secondary: "#111827",
      accent: "#F59E0B",
      background: "#FFF7ED",
      dark: false,
    },
    typography: {
      displayFont: "Fraunces",
      headingFont: "Fraunces",
      bodyFont: "DM Sans",
      monoFont: "IBM Plex Mono",
      weights: { display: 700, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.05", heading: "1.15", body: "1.65" },
      tracking: { display: "-0.03em", heading: "-0.02em", body: "0" },
      scale: {
        display: "clamp(2.75rem, 6vw, 4.75rem)",
        h1: "clamp(2.25rem, 4vw, 3.5rem)",
        h2: "1.75rem",
        h3: "1.3rem",
        body: "1.05rem",
        small: "0.875rem",
      },
      notes: "Expressive display + energetic sans",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        "2xl": "4rem",
        "3xl": "6rem",
      },
      sectionY: "5.5rem",
      sectionYMobile: "3.5rem",
      containerMax: "76rem",
      gutter: "1.5rem",
      stack: "1.1rem",
      notes: "Studio portfolio rhythm",
    },
    radius: {
      none: "0",
      sm: "0.25rem",
      md: "0.5rem",
      lg: "1rem",
      xl: "1.75rem",
      full: "9999px",
      default: "0.5rem",
    },
    shadows: {
      none: "none",
      sm: "0 4px 12px rgb(17 24 39 / 0.08)",
      md: "0 12px 32px rgb(17 24 39 / 0.12)",
      lg: "0 24px 60px rgb(17 24 39 / 0.16)",
      xl: "0 40px 90px rgb(17 24 39 / 0.2)",
      glow: "0 0 28px rgb(225 29 72 / 0.25)",
      default: "0 12px 32px rgb(17 24 39 / 0.12)",
      notes: "Bold but soft studio shadows",
    },
    gradients: {
      hero: "linear-gradient(120deg, #FFF7ED 0%, #FFE4E6 45%, #FEF3C7 100%)",
      cta: "linear-gradient(135deg, #E11D48, #F59E0B)",
      surface: "linear-gradient(180deg, #FFFFFF, #FFF7ED)",
      accent: "radial-gradient(circle at 15% 20%, rgb(225 29 72 / 0.2), transparent 45%)",
      mesh: "radial-gradient(at 80% 0%, rgb(245 158 11 / 0.22), transparent 40%)",
      notes: "Warm creative washes",
    },
    glass: {
      enabled: true,
      background: "rgb(255 255 255 / 0.65)",
      border: "1px solid rgb(225 29 72 / 0.15)",
      blur: "14px",
      saturate: "150%",
      notes: "Soft glass for portfolio overlays",
    },
    animation: {
      motion: "expressive",
      easing: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      durationFast: "200ms",
      duration: "500ms",
      durationSlow: "850ms",
      entrances: ["fade-up", "scale-in", "stagger-cards"],
      hover: "lift-tilt",
      pageTransition: "fade",
      notes: "Playful but controlled studio motion",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "asymmetric-studio",
      sectionLayout: "portfolio-mosaic",
      cardStyle: "bold-media",
      navigationStyle: "studio-transparent",
      footerStyle: "editorial-columns",
      ctaStyle: "gradient-pill",
      density: "airy",
      rules: [
        "Work-first storytelling — portfolio before services",
        "Expressive type with restrained color accents",
        "Asymmetric layouts over rigid corporate grids",
      ],
    },
  },
  technology: {
    styleId: "technology",
    enginePreset: "tech",
    label: "Technology",
    seed: {
      primary: "#06B6D4",
      secondary: "#020617",
      accent: "#A78BFA",
      background: "#020617",
      dark: true,
    },
    typography: {
      displayFont: "Space Grotesk",
      headingFont: "Space Grotesk",
      bodyFont: "IBM Plex Sans",
      monoFont: "JetBrains Mono",
      weights: { display: 600, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.05", heading: "1.15", body: "1.6" },
      tracking: { display: "-0.03em", heading: "-0.02em", body: "0" },
      scale: {
        display: "clamp(2.5rem, 5.5vw, 4rem)",
        h1: "clamp(2.1rem, 4vw, 3.25rem)",
        h2: "clamp(1.6rem, 2.8vw, 2.1rem)",
        h3: "1.25rem",
        body: "1.05rem",
        small: "0.875rem",
      },
      notes: "Precision tech typography — geometric display + product body",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.25rem",
        "2xl": "3.5rem",
        "3xl": "5.5rem",
      },
      sectionY: "5.25rem",
      sectionYMobile: "3.25rem",
      containerMax: "72rem",
      gutter: "1.5rem",
      stack: "1.1rem",
      notes: "Product-marketing density with breathable gaps",
    },
    radius: {
      none: "0",
      sm: "0.35rem",
      md: "0.65rem",
      lg: "0.9rem",
      xl: "1.25rem",
      full: "9999px",
      default: "0.65rem",
    },
    shadows: {
      none: "none",
      sm: "0 4px 16px rgb(0 0 0 / 0.35)",
      md: "0 16px 48px rgb(0 0 0 / 0.45)",
      lg: "0 28px 80px rgb(0 0 0 / 0.55)",
      xl: "0 40px 110px rgb(0 0 0 / 0.65)",
      glow: "0 0 36px rgb(6 182 212 / 0.35)",
      default: "0 16px 48px rgb(0 0 0 / 0.45)",
      notes: "Cyan glow on interactive tech surfaces",
    },
    gradients: {
      hero: "linear-gradient(145deg, rgb(2 6 23 / 0.15), rgb(2 6 23 / 0.85))",
      cta: "linear-gradient(135deg, #06B6D4, #A78BFA)",
      surface: "linear-gradient(180deg, rgb(255 255 255 / 0.04), transparent)",
      accent: "radial-gradient(circle at 25% 15%, rgb(6 182 212 / 0.28), transparent 50%)",
      mesh: "radial-gradient(at 80% 10%, rgb(167 139 250 / 0.2), transparent 40%)",
      notes: "Dark tech washes with luminous accents",
    },
    glass: {
      enabled: true,
      background: "rgb(15 23 42 / 0.65)",
      border: "1px solid rgb(6 182 212 / 0.22)",
      blur: "18px",
      saturate: "160%",
      notes: "Dark glass product panels",
    },
    animation: {
      motion: "subtle",
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      durationFast: "180ms",
      duration: "450ms",
      durationSlow: "750ms",
      entrances: ["fade-up", "glow-in", "stagger-cards"],
      hover: "glow-lift",
      pageTransition: "fade",
      notes: "Precise product motion — no decorative chaos",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "product-frame-cinematic",
      sectionLayout: "bento-capabilities",
      cardStyle: "dark-glass",
      navigationStyle: "compact-product",
      footerStyle: "dense-product",
      ctaStyle: "glow-pill",
      density: "balanced",
      rules: [
        "Show product reality early — UI frames over abstract blobs",
        "Bento feature grids with clear hierarchy",
        "High-contrast CTAs on dark surfaces",
      ],
    },
  },
  saas: {
    styleId: "saas",
    enginePreset: "tech",
    label: "SaaS",
    seed: {
      primary: "#4F46E5",
      secondary: "#0F172A",
      accent: "#22D3EE",
      background: "#FAFBFF",
      dark: false,
    },
    typography: {
      displayFont: "Sora",
      headingFont: "Sora",
      bodyFont: "Inter",
      monoFont: "IBM Plex Mono",
      weights: { display: 600, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.05", heading: "1.15", body: "1.65" },
      tracking: { display: "-0.03em", heading: "-0.02em", body: "0" },
      scale: {
        display: "clamp(2.5rem, 5.2vw, 3.85rem)",
        h1: "clamp(2.1rem, 3.8vw, 3.15rem)",
        h2: "clamp(1.55rem, 2.6vw, 2.05rem)",
        h3: "1.25rem",
        body: "1.05rem",
        small: "0.875rem",
      },
      notes: "Product-led SaaS type — geometric clarity, conversion-ready",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.25rem",
        "2xl": "3.5rem",
        "3xl": "5.25rem",
      },
      sectionY: "5rem",
      sectionYMobile: "3.25rem",
      containerMax: "72rem",
      gutter: "1.5rem",
      stack: "1.1rem",
      notes: "SaaS marketing density with clear feature scanning",
    },
    radius: {
      none: "0",
      sm: "0.4rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.35rem",
      full: "9999px",
      default: "0.75rem",
    },
    shadows: {
      none: "none",
      sm: "0 4px 16px rgb(79 70 229 / 0.08)",
      md: "0 16px 44px rgb(15 23 42 / 0.1)",
      lg: "0 28px 70px rgb(15 23 42 / 0.12)",
      xl: "0 40px 100px rgb(15 23 42 / 0.14)",
      glow: "0 0 32px rgb(79 70 229 / 0.28)",
      default: "0 16px 44px rgb(15 23 42 / 0.1)",
      notes: "Soft indigo elevation for product cards",
    },
    gradients: {
      hero: "linear-gradient(135deg, #FAFBFF 0%, #EEF2FF 55%, #ECFEFF 100%)",
      cta: "linear-gradient(135deg, #4F46E5, #6366F1)",
      surface: "linear-gradient(180deg, #FFFFFF, #F8FAFC)",
      accent: "radial-gradient(circle at 20% 15%, rgb(34 211 238 / 0.18), transparent 50%)",
      mesh: "radial-gradient(at 85% 10%, rgb(79 70 229 / 0.12), transparent 40%)",
      notes: "Light product washes — never dark-tech by default",
    },
    glass: {
      enabled: true,
      background: "rgb(255 255 255 / 0.72)",
      border: "1px solid rgb(79 70 229 / 0.12)",
      blur: "14px",
      saturate: "140%",
      notes: "Light product glass panels",
    },
    animation: {
      motion: "subtle",
      easing: "cubic-bezier(0.16, 1, 0.3, 1)",
      durationFast: "180ms",
      duration: "420ms",
      durationSlow: "700ms",
      entrances: ["fade-up", "stagger-cards", "scale-in"],
      hover: "lift-soft",
      pageTransition: "fade",
      notes: "Product marketing motion — crisp, never noisy",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "product-frame-cinematic",
      sectionLayout: "bento-capabilities",
      cardStyle: "elevated-soft",
      navigationStyle: "sticky-product-cta",
      footerStyle: "compact-product",
      ctaStyle: "trial-demo-pair",
      density: "balanced",
      rules: [
        "Show product UI early — trial/demo pair CTAs",
        "Bento feature grids with social proof before pricing",
        "Light surfaces — distinct from dark Technology system",
      ],
    },
  },
  "premium-brand": {
    styleId: "premium-brand",
    enginePreset: "premium-brand",
    label: "Premium Brand",
    seed: {
      primary: "#0B1220",
      secondary: "#5B6472",
      accent: "#9A3412",
      background: "#FAFAF8",
      dark: false,
    },
    typography: {
      displayFont: "Cormorant Garamond",
      headingFont: "Cormorant Garamond",
      bodyFont: "Manrope",
      monoFont: "IBM Plex Mono",
      weights: { display: 600, heading: 600, body: 400, medium: 500 },
      lineHeights: { display: "1.0", heading: "1.1", body: "1.68" },
      tracking: { display: "-0.03em", heading: "-0.02em", body: "0.005em" },
      scale: {
        display: "clamp(3rem, 6.5vw, 5.25rem)",
        h1: "clamp(2.5rem, 4.5vw, 3.85rem)",
        h2: "clamp(1.85rem, 3.2vw, 2.55rem)",
        h3: "1.4rem",
        body: "1.075rem",
        small: "0.875rem",
      },
      notes:
        "Flagship brand type — quiet luxury hierarchy competing with global agency work",
    },
    spacing: {
      unit: "4px",
      scale: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.75rem",
        xl: "3rem",
        "2xl": "5rem",
        "3xl": "8rem",
      },
      sectionY: "7.5rem",
      sectionYMobile: "4.25rem",
      containerMax: "76rem",
      gutter: "1.85rem",
      stack: "1.5rem",
      notes: "Flagship whitespace — museum calm, decisive stacks",
    },
    radius: {
      none: "0",
      sm: "0.25rem",
      md: "0.55rem",
      lg: "0.85rem",
      xl: "1.25rem",
      full: "9999px",
      default: "0.55rem",
    },
    shadows: {
      none: "none",
      sm: "0 4px 16px rgb(11 18 32 / 0.05)",
      md: "0 16px 44px rgb(11 18 32 / 0.07)",
      lg: "0 32px 80px rgb(11 18 32 / 0.09)",
      xl: "0 48px 110px rgb(11 18 32 / 0.11)",
      glow: "0 0 32px rgb(154 52 18 / 0.16)",
      default: "0 16px 44px rgb(11 18 32 / 0.07)",
      notes: "Soft brand elevation — never harsh template shadows",
    },
    gradients: {
      hero: "linear-gradient(125deg, #FAFAF8 0%, #F3F1EC 50%, #F5EDE4 100%)",
      cta: "linear-gradient(135deg, #0B1220, #1F2937)",
      surface: "linear-gradient(180deg, #FAFAF8, #F3F1EC)",
      accent: "radial-gradient(circle at 16% 18%, rgb(154 52 18 / 0.1), transparent 52%)",
      mesh: "radial-gradient(at 88% 12%, rgb(11 18 32 / 0.05), transparent 42%)",
      notes: "Warm flagship washes — never purple AI default",
    },
    glass: {
      enabled: true,
      background: "rgb(250 250 248 / 0.72)",
      border: "1px solid rgb(11 18 32 / 0.08)",
      blur: "16px",
      saturate: "125%",
      notes: "Soft glass for brand overlays",
    },
    animation: {
      motion: "subtle",
      easing: "cubic-bezier(0.22, 1, 0.36, 1)",
      durationFast: "220ms",
      duration: "700ms",
      durationSlow: "1100ms",
      entrances: ["fade-up", "slow-reveal", "scale-in"],
      hover: "lift-soft",
      pageTransition: "fade",
      notes: "Restrained flagship motion with smooth transitions",
    },
    responsive: SHARED_RESPONSIVE,
    layout: {
      heroStyle: "cinematic-hero",
      sectionLayout: "premium-storytelling",
      cardStyle: "borderless-editorial",
      navigationStyle: "logo-led-reserved",
      footerStyle: "multi-column-quiet",
      ctaStyle: "ink-pill",
      density: "airy",
      rules: [
        "Brand story before feature lists",
        "One decisive accent — never rainbow",
        "Cinematic or editorial hero — never generic centered stack",
        "Prefer storytelling bands, trust strips, case studies over card grids",
        "Image style: editorial brand photography, confident people, refined spaces",
      ],
    },
  },
};

export const PREMIUM_STYLE_IDS = Object.keys(
  PREMIUM_STYLE_BASES,
) as PremiumStyleId[];

export function premiumStyleToEnginePreset(
  styleId: PremiumStyleId,
): DesignPresetId {
  return PREMIUM_STYLE_BASES[styleId].enginePreset;
}

export function getPremiumStyleBase(styleId: PremiumStyleId): StyleBase {
  return PREMIUM_STYLE_BASES[styleId];
}

export function buildPremiumStylePackage(
  styleId: PremiumStyleId,
  colorOverrides?: Partial<{
    primary: string;
    secondary: string;
    accent: string;
    background: string;
  }>,
): PremiumDesignSystem {
  const base = PREMIUM_STYLE_BASES[styleId];
  const colors = generateColorHarmony({
    primary: colorOverrides?.primary || base.seed.primary,
    secondary: colorOverrides?.secondary || base.seed.secondary,
    accent: colorOverrides?.accent || base.seed.accent,
    background: colorOverrides?.background || base.seed.background,
    dark: base.seed.dark,
    mode:
      styleId === "minimal"
        ? "mono"
        : styleId === "creative"
          ? "triadic"
          : styleId === "technology" || styleId === "futuristic"
            ? "split"
            : styleId === "premium-brand"
              ? "analogous"
              : "complementary",
  });

  return {
    styleId: base.styleId,
    enginePreset: base.enginePreset,
    label: base.label,
    typography: base.typography,
    colors,
    spacing: base.spacing,
    radius: base.radius,
    shadows: base.shadows,
    gradients: base.gradients,
    glass: base.glass,
    animation: base.animation,
    responsive: base.responsive,
    layout: base.layout,
    brandSummary: `${base.label} visual identity — ${base.layout.heroStyle} hero, ${base.layout.cardStyle} cards, ${base.typography.displayFont} / ${base.typography.bodyFont}.`,
  };
}
