import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const CREATIVE_STUDIO_SECTOR_DNA = defineSectorDna({
  id: "creative-studio",
  name: "Creative Studio",
  experienceProfiles: ["creative", "editorial", "playful"],
  personality: {
    brand: "Bold, experimental, craft-obsessed",
    visual: "High-contrast palettes, kinetic typography, portfolio-forward",
    emotionalTone: "Inspiration, audacity, creative confidence",
    philosophy: "Show the work — design is the portfolio",
    targetAudience: "Brand managers, startups, cultural institutions",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.brand.accent",
      surfaceEmphasis: "semantic.surface.inverse",
      modePreference: "dark",
    },
    surfaceStrategy: "immersive",
    spacingBehavior: "editorial",
    gridPreference: "asymmetric",
    imageDirection: "Project case studies, process shots, bold color blocks",
    iconStyle: "duotone",
    illustrationStyle: "Abstract shapes, collage, custom motion graphics",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "portfolio-grid",
      "case-study-card",
      "carousel",
      "testimonial",
      "marquee",
      "video",
      "contact-form",
      "footer",
    ],
    heroStrategy: "Editorial reveal — kinetic headline with project reel",
    navigationStyle: "Minimal fixed nav — Work, Studio, Contact",
    ctaStrategy: "Primary: Start a project · Secondary: View reel",
    contentHierarchy: "Hero → Selected work → Capabilities → Process → Contact",
    cardStyle: "Case study cards — full-bleed image, project title, category tag",
  },
  experience: {
    experienceProfiles: ["creative", "editorial", "playful"],
    motionProfile: ["hero-headline", "grid-stagger", "scroll-reveal-up", "stagger-children"],
    interactionProfile: ["card-hover", "hero-enter", "feature-stagger", "carousel-swipe"],
    feedbackProfile: ["loading", "success"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "medium" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "desktop", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: true },
  },
  growth: {
    seoPresentation: "Creative work schema, case study pages, studio about",
    conversionStrategy: "Portfolio depth over volume, inquiry form after case studies",
    trustBuilding: "Client logos, awards, press features, team credentials",
  },
  ai: {
    layoutIds: ["editorial-reveal", "asymmetric-grid", "full-bleed"],
    heroComponents: ["hero-editorial", "hero-reel", "marquee"],
    navComponents: ["navbar", "drawer"],
    ctaComponents: ["primary-button", "contact-form"],
    motionPresets: ["hero-headline", "grid-stagger", "stagger-children"],
    typographyProfiles: ["latin-ltr", "latin-rtl"],
    spacingScale: "editorial",
    pageFlow: ["hero", "work", "capabilities", "process", "contact"],
    primaryButtonVariant: "primary",
    cardComponents: ["case-study-card", "portfolio-card"],
    feedbackStates: ["loading", "success"],
    confidence: 0.92,
  },
});
