import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const EDUCATION_SECTOR_DNA = defineSectorDna({
  id: "education",
  name: "Education",
  experienceProfiles: ["playful", "corporate", "editorial"],
  personality: {
    brand: "Inspiring, accessible, growth-oriented",
    visual: "Warm approachable palettes, clear information architecture",
    emotionalTone: "Curiosity, empowerment, belonging",
    philosophy: "Learning should feel achievable — reduce friction at every step",
    targetAudience: "Students, parents, educators, institutional buyers",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.brand.accent",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "elevated",
    spacingBehavior: "balanced",
    gridPreference: "standard",
    imageDirection: "Campus life, classroom engagement, diverse student body",
    iconStyle: "filled",
    illustrationStyle: "Friendly educational illustrations, achievement badges",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "course-card",
      "program-card",
      "accordion",
      "testimonial",
      "stats",
      "tabs",
      "enrollment-form",
      "footer",
    ],
    heroStrategy: "Aspirational hero — program headline with enrollment CTA",
    navigationStyle: "Clear top nav — Programs, Admissions, Campus, Apply",
    ctaStrategy: "Primary: Apply now · Secondary: Request info",
    contentHierarchy: "Programs → Admissions → Campus life → Outcomes → Apply",
    cardStyle: "Course cards — image, title, duration, enrollment status",
  },
  experience: {
    experienceProfiles: ["playful", "corporate", "editorial"],
    motionProfile: ["section-reveal", "stagger-children", "scroll-reveal-up", "success-pulse"],
    interactionProfile: ["card-hover", "accordion-expand", "tab-switch", "form-focus"],
    feedbackProfile: ["loading", "success", "validation", "progress"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "medium" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "mobile", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: true },
  },
  growth: {
    seoPresentation: "Educational organization schema, program pages, course catalog",
    conversionStrategy: "Application funnel clear, info request low-friction",
    trustBuilding: "Accreditation badges, graduate outcomes, faculty credentials",
  },
  ai: {
    layoutIds: ["single-column", "sidebar-left"],
    heroComponents: ["hero-centered", "hero-split", "stats"],
    navComponents: ["navbar", "tabs", "breadcrumb"],
    ctaComponents: ["primary-button", "enrollment-form"],
    motionPresets: ["section-reveal", "stagger-children", "success-pulse"],
    typographyProfiles: ["latin-ltr", "latin-rtl", "arabic-rtl"],
    spacingScale: "balanced",
    pageFlow: ["hero", "programs", "admissions", "campus", "outcomes", "apply"],
    primaryButtonVariant: "primary",
    cardComponents: ["course-card", "program-card", "faculty-card"],
    feedbackStates: ["loading", "success", "validation", "progress"],
    confidence: 0.93,
  },
});
