import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const FINANCE_SECTOR_DNA = defineSectorDna({
  id: "finance",
  name: "Finance",
  experienceProfiles: ["executive", "corporate", "technical"],
  personality: {
    brand: "Stable, data-driven, fiduciary responsibility",
    visual: "Conservative palettes, chart-forward, security-conscious UI",
    emotionalTone: "Security, growth, informed decision-making",
    philosophy: "Transparency builds trust — numbers and compliance visible",
    targetAudience: "Investors, business owners, high-net-worth individuals",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.feedback.success",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "layered",
    spacingBehavior: "balanced",
    gridPreference: "dense",
    imageDirection: "Professional team, market imagery, abstract financial graphics",
    iconStyle: "outline",
    illustrationStyle: "Data visualization, growth charts, minimal infographics",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "stats",
      "data-table",
      "chart",
      "service-card",
      "testimonial",
      "accordion",
      "contact-form",
      "alert",
    ],
    heroStrategy: "Trust-first hero — value proposition with performance metrics strip",
    navigationStyle: "Professional top nav — Services, Insights, About, Client login",
    ctaStrategy: "Primary: Open account · Secondary: Speak to advisor",
    contentHierarchy: "Value prop → Services → Performance → Team → Compliance → CTA",
    cardStyle: "Service cards with metric highlight, icon, compliance badge",
  },
  experience: {
    experienceProfiles: ["executive", "corporate", "technical"],
    motionProfile: ["page-enter", "grid-stagger", "focus-ring", "success-pulse"],
    interactionProfile: ["btn-hover", "table-sort", "form-focus", "tab-switch"],
    feedbackProfile: ["loading", "success", "error", "saving"],
    accessibilityProfile: { contrastLevel: "AAA", motionSensitivity: "high" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "desktop", touchPriority: false },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: false },
  },
  growth: {
    seoPresentation: "Financial service schema, regulatory disclosures, insight articles",
    conversionStrategy: "Advisor contact prominent, account opening simplified",
    trustBuilding: "SEC/FINRA badges, AUM figures, client testimonials, disclosures",
  },
  ai: {
    layoutIds: ["single-column", "dashboard-grid", "sidebar-left"],
    heroComponents: ["hero-split", "stats-hero"],
    navComponents: ["navbar", "sidebar", "tabs"],
    ctaComponents: ["primary-button", "contact-form"],
    motionPresets: ["page-enter", "grid-stagger", "focus-ring"],
    typographyProfiles: ["latin-ltr", "latin-rtl"],
    spacingScale: "balanced",
    pageFlow: ["hero", "services", "performance", "team", "compliance", "cta"],
    primaryButtonVariant: "primary",
    cardComponents: ["service-card", "stat-card", "insight-card"],
    feedbackStates: ["loading", "success", "error", "saving"],
    confidence: 0.95,
  },
});
