import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const HOTEL_RESORT_SECTOR_DNA = defineSectorDna({
  id: "hotel-resort",
  name: "Hotel & Resort",
  experienceProfiles: ["hospitality", "luxury", "minimal"],
  personality: {
    brand: "Indulgent, serene, destination-defining",
    visual: "Immersive imagery, elegant typography, reservation-centric UX",
    emotionalTone: "Escape, luxury, personalized welcome",
    philosophy: "Transport guests before arrival — every pixel evokes the stay",
    targetAudience: "Leisure travelers, honeymooners, corporate retreat planners",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.brand.accent",
      surfaceEmphasis: "semantic.surface.elevated",
      modePreference: "light",
    },
    surfaceStrategy: "immersive",
    spacingBehavior: "generous",
    gridPreference: "airy",
    imageDirection: "Resort panoramas, suite interiors, amenity lifestyle shots",
    iconStyle: "outline",
    illustrationStyle: "Watercolor landscapes, destination maps",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "room-card",
      "booking-form",
      "gallery",
      "amenity-grid",
      "testimonial",
      "map",
      "carousel",
      "footer",
    ],
    heroStrategy: "Cinematic full-screen hero with inline booking widget",
    navigationStyle: "Elegant top nav — Rooms, Dining, Spa, Experiences, Book",
    ctaStrategy: "Primary: Check availability · Secondary: Explore rooms",
    contentHierarchy: "Hero → Rooms → Amenities → Experiences → Reviews → Book",
    cardStyle: "Room cards — hero image, room type, rate, amenities icons",
  },
  experience: {
    experienceProfiles: ["hospitality", "luxury", "minimal"],
    motionProfile: ["hero-media", "scroll-reveal-up", "section-reveal", "card-lift"],
    interactionProfile: ["card-hover", "carousel-swipe", "date-picker", "cta-pulse"],
    feedbackProfile: ["loading", "success", "validation"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "low" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "mobile", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: true },
  },
  growth: {
    seoPresentation: "Hotel schema, room type pages, destination guides",
    conversionStrategy: "Booking widget persistent, rate transparency, package upsells",
    trustBuilding: "Star ratings, guest reviews, awards, cancellation policy clarity",
  },
  ai: {
    layoutIds: ["full-bleed", "sidebar-left", "single-column"],
    heroComponents: ["hero-cinematic", "booking-hero", "gallery"],
    navComponents: ["navbar", "drawer"],
    ctaComponents: ["primary-button", "booking-form"],
    motionPresets: ["hero-media", "scroll-reveal-up", "card-lift"],
    typographyProfiles: ["latin-ltr", "latin-rtl", "arabic-rtl"],
    spacingScale: "generous",
    pageFlow: ["hero", "rooms", "amenities", "experiences", "reviews", "book"],
    primaryButtonVariant: "primary",
    cardComponents: ["room-card", "amenity-card", "package-card"],
    feedbackStates: ["loading", "success", "validation"],
    confidence: 0.93,
  },
});
