import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const LAW_FIRM_SECTOR_DNA = defineSectorDna({
  id: "law-firm",
  name: "Law Firm",
  experienceProfiles: ["executive", "corporate", "luxury"],
  personality: {
    brand: "Authoritative, discreet, results-proven",
    visual: "Conservative elegance, serif headlines, structured content blocks",
    emotionalTone: "Confidence, gravitas, protection",
    philosophy: "Credibility before creativity — expertise must be immediately evident",
    targetAudience: "Corporate counsel, individuals seeking representation, referrals",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.brand.accent",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "layered",
    spacingBehavior: "balanced",
    gridPreference: "standard",
    imageDirection: "Professional attorney portraits, courthouse imagery, abstract authority",
    iconStyle: "outline",
    illustrationStyle: "Minimal legal iconography, scales of justice line art",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "practice-area-card",
      "attorney-card",
      "contact-form",
      "accordion",
      "testimonial",
      "breadcrumb",
      "alert",
      "footer",
    ],
    heroStrategy: "Authoritative hero — practice focus headline with consultation CTA",
    navigationStyle: "Traditional top nav — Practices, Attorneys, Insights, Contact",
    ctaStrategy: "Primary: Schedule consultation · Secondary: Call office",
    contentHierarchy: "Practice areas → Attorneys → Case results → Insights → Contact",
    cardStyle: "Practice area cards — icon, title, brief expertise summary",
  },
  experience: {
    experienceProfiles: ["executive", "corporate", "luxury"],
    motionProfile: ["page-enter", "section-reveal", "focus-ring", "modal-enter"],
    interactionProfile: ["btn-focus", "accordion-expand", "form-focus", "nav-item-active"],
    feedbackProfile: ["loading", "success", "validation"],
    accessibilityProfile: { contrastLevel: "AAA", motionSensitivity: "high" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "desktop", touchPriority: false },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: false },
  },
  growth: {
    seoPresentation: "Legal service schema, attorney profiles, practice area pages",
    conversionStrategy: "Consultation form above fold, phone number in header",
    trustBuilding: "Bar admissions, case outcomes, peer ratings, firm history",
  },
  ai: {
    layoutIds: ["single-column", "sidebar-left"],
    heroComponents: ["hero-centered", "hero-split"],
    navComponents: ["navbar", "breadcrumb"],
    ctaComponents: ["primary-button", "contact-form"],
    motionPresets: ["page-enter", "section-reveal", "focus-ring"],
    typographyProfiles: ["latin-ltr", "latin-rtl"],
    spacingScale: "balanced",
    pageFlow: ["hero", "practices", "attorneys", "results", "insights", "contact"],
    primaryButtonVariant: "primary",
    cardComponents: ["practice-area-card", "attorney-card", "insight-card"],
    feedbackStates: ["loading", "success", "validation"],
    confidence: 0.94,
  },
});
