import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const LOGISTICS_SECTOR_DNA = defineSectorDna({
  id: "logistics",
  name: "Logistics",
  experienceProfiles: ["technical", "corporate", "executive"],
  personality: {
    brand: "Reliable, efficient, globally connected",
    visual: "Operational clarity, map-forward, status-driven UI",
    emotionalTone: "Dependability, precision, scale",
    philosophy: "Show the network — visibility and tracking are the product",
    targetAudience: "Supply chain managers, e-commerce operators, enterprise shippers",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.feedback.info",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "flat",
    spacingBehavior: "compact",
    gridPreference: "dense",
    imageDirection: "Fleet photography, warehouse operations, global route maps",
    iconStyle: "outline",
    illustrationStyle: "Route diagrams, supply chain flowcharts, tracking UI mockups",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "tracking-form",
      "stats",
      "service-card",
      "map",
      "data-table",
      "timeline",
      "contact-form",
      "alert",
    ],
    heroStrategy: "Utility hero — tracking input with service overview",
    navigationStyle: "Functional top nav — Services, Tracking, Network, Contact",
    ctaStrategy: "Primary: Get a quote · Secondary: Track shipment",
    contentHierarchy: "Tracking → Services → Network → Technology → Quote",
    cardStyle: "Service cards — icon, capability, SLA metric, coverage badge",
  },
  experience: {
    experienceProfiles: ["technical", "corporate", "executive"],
    motionProfile: ["page-enter", "grid-stagger", "focus-ring", "toast-enter"],
    interactionProfile: ["form-focus", "table-sort", "btn-hover", "map-pin-hover"],
    feedbackProfile: ["loading", "success", "error", "progress"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "medium" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "desktop", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: false },
  },
  growth: {
    seoPresentation: "Logistics service schema, route pages, tracking landing",
    conversionStrategy: "Quote form accessible, tracking widget above fold",
    trustBuilding: "Delivery metrics, client logos, certifications, global coverage map",
  },
  ai: {
    layoutIds: ["single-column", "dashboard-grid", "sidebar-left"],
    heroComponents: ["tracking-hero", "hero-split", "stats"],
    navComponents: ["navbar", "sidebar"],
    ctaComponents: ["primary-button", "tracking-form", "contact-form"],
    motionPresets: ["page-enter", "grid-stagger", "toast-enter"],
    typographyProfiles: ["latin-ltr", "latin-rtl"],
    spacingScale: "compact",
    pageFlow: ["hero", "tracking", "services", "network", "technology", "quote"],
    primaryButtonVariant: "primary",
    cardComponents: ["service-card", "stat-card", "route-card"],
    feedbackStates: ["loading", "success", "error", "progress"],
    confidence: 0.94,
  },
});
