import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const MEDICAL_SECTOR_DNA = defineSectorDna({
  id: "medical",
  name: "Medical",
  experienceProfiles: ["healthcare", "corporate", "minimal"],
  personality: {
    brand: "Compassionate, clinical excellence, patient-first",
    visual: "Clean clinical aesthetics, calming colors, clear information hierarchy",
    emotionalTone: "Reassurance, competence, empathy",
    philosophy: "Reduce anxiety through clarity — every element earns trust",
    targetAudience: "Patients, caregivers, referring physicians",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.feedback.info",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "flat",
    spacingBehavior: "generous",
    gridPreference: "standard",
    imageDirection: "Caring staff portraits, clean facility photos, patient-friendly imagery",
    iconStyle: "outline",
    illustrationStyle: "Medical iconography, anatomical line art (accessible)",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "service-card",
      "doctor-card",
      "appointment-form",
      "accordion",
      "alert",
      "breadcrumb",
      "tabs",
      "contact-form",
    ],
    heroStrategy: "Calm hero with appointment booking CTA and credentials strip",
    navigationStyle: "Clear top nav — Services, Doctors, Locations, Book",
    ctaStrategy: "Primary: Book appointment · Secondary: Call now",
    contentHierarchy: "Services → Doctors → Locations → Insurance → Book",
    cardStyle: "Service cards with icon, plain-language description, CTA",
  },
  experience: {
    experienceProfiles: ["healthcare", "corporate", "minimal"],
    motionProfile: ["section-reveal", "focus-ring", "success-pulse"],
    interactionProfile: ["form-focus", "form-success", "accordion-expand", "btn-focus"],
    feedbackProfile: ["loading", "success", "error", "validation"],
    accessibilityProfile: { contrastLevel: "AAA", motionSensitivity: "high" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "mobile", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: false },
  },
  growth: {
    seoPresentation: "Medical organization schema, service pages, doctor profiles",
    conversionStrategy: "Appointment booking above fold, phone number visible",
    trustBuilding: "Board certifications, accreditations, patient testimonials, HIPAA notice",
  },
  ai: {
    layoutIds: ["full-bleed", "single-column", "overlay-before-main"],
    heroComponents: ["hero-centered", "appointment-hero"],
    navComponents: ["navbar", "breadcrumb"],
    ctaComponents: ["primary-button", "appointment-form"],
    motionPresets: ["section-reveal", "focus-ring", "success-pulse"],
    typographyProfiles: ["latin-ltr", "arabic-rtl"],
    spacingScale: "generous",
    pageFlow: ["hero", "services", "doctors", "locations", "insurance", "book"],
    primaryButtonVariant: "primary",
    cardComponents: ["service-card", "doctor-card", "location-card"],
    feedbackStates: ["loading", "success", "validation"],
    confidence: 0.95,
  },
});
