import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const REAL_ESTATE_SECTOR_DNA = defineSectorDna({
  id: "real-estate",
  name: "Real Estate",
  experienceProfiles: ["luxury", "executive", "corporate"],
  personality: {
    brand: "Prestigious, aspirational, location-authoritative",
    visual: "Architectural photography, spacious grids, premium typography",
    emotionalTone: "Aspiration, security, lifestyle elevation",
    philosophy: "Properties are protagonists — design frames, never competes",
    targetAudience: "High-net-worth buyers, investors, relocating families",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.brand.accent",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "elevated",
    spacingBehavior: "generous",
    gridPreference: "airy",
    imageDirection: "Architectural exteriors, interior staging, aerial views",
    iconStyle: "outline",
    illustrationStyle: "Minimal floor-plan line art, location maps",
  },
  components: {
    preferredComponents: [
      "navbar",
      "property-card",
      "search-bar",
      "filter",
      "gallery",
      "map",
      "agent-card",
      "testimonial",
      "contact-form",
      "stats",
    ],
    heroStrategy: "Cinematic property hero with search/filter bar",
    navigationStyle: "Right sidebar or top nav — Buy, Rent, Sell, Agents",
    ctaStrategy: "Primary: Schedule viewing · Secondary: Download brochure",
    contentHierarchy: "Featured listings → Search → Neighborhoods → Agents → Contact",
    cardStyle: "Property cards — image, price, beds/baths, location badge",
  },
  experience: {
    experienceProfiles: ["luxury", "executive", "corporate"],
    motionProfile: ["hero-media", "section-reveal", "card-lift", "scroll-reveal-up"],
    interactionProfile: ["card-hover", "filter-toggle", "map-pin-hover"],
    feedbackProfile: ["loading", "success", "empty"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "low" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "desktop", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: true },
  },
  growth: {
    seoPresentation: "Listing schema, neighborhood guides, agent profile pages",
    conversionStrategy: "Lead capture on listing detail, virtual tour CTAs",
    trustBuilding: "Agent credentials, sold portfolio, market data, testimonials",
  },
  ai: {
    layoutIds: ["sidebar-right", "single-column", "property-grid"],
    heroComponents: ["hero-cinematic", "search-hero", "gallery"],
    navComponents: ["navbar", "sidebar", "breadcrumb"],
    ctaComponents: ["primary-button", "contact-form"],
    motionPresets: ["hero-media", "section-reveal", "card-lift"],
    typographyProfiles: ["latin-ltr", "latin-rtl"],
    spacingScale: "generous",
    pageFlow: ["hero", "featured", "search", "neighborhoods", "agents", "contact"],
    primaryButtonVariant: "primary",
    cardComponents: ["property-card", "agent-card", "neighborhood-card"],
    feedbackStates: ["loading", "success", "empty"],
    confidence: 0.94,
  },
});
