import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const RESTAURANT_SECTOR_DNA = defineSectorDna({
  id: "restaurant",
  name: "Restaurant",
  experienceProfiles: ["hospitality", "luxury", "editorial"],
  personality: {
    brand: "Sensory, authentic, locally rooted",
    visual: "Rich photography, warm palettes, menu-centric layouts",
    emotionalTone: "Appetite, warmth, celebration",
    philosophy: "Let food and atmosphere lead — copy supports, never competes",
    targetAudience: "Diners, event planners, local food enthusiasts",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.feedback.warning",
      surfaceEmphasis: "semantic.surface.elevated",
      modePreference: "dark",
    },
    surfaceStrategy: "immersive",
    spacingBehavior: "generous",
    gridPreference: "airy",
    imageDirection: "Full-bleed dish photography, ambient interior shots",
    iconStyle: "minimal",
    illustrationStyle: "Hand-drawn culinary accents, botanical motifs",
  },
  components: {
    preferredComponents: [
      "navbar",
      "hero",
      "gallery",
      "menu-card",
      "testimonial",
      "reservation-form",
      "map",
      "footer",
      "carousel",
      "image",
    ],
    heroStrategy: "Full-bleed hero with reservation CTA overlay",
    navigationStyle: "Minimal overlay nav — Menu, Story, Reserve, Contact",
    ctaStrategy: "Primary: Reserve a table · Secondary: View menu",
    contentHierarchy: "Atmosphere → Menu highlights → Story → Reviews → Reserve",
    cardStyle: "Menu cards with dish image, name, description, price",
  },
  experience: {
    experienceProfiles: ["hospitality", "luxury", "editorial"],
    motionProfile: ["hero-media", "scroll-reveal-up", "card-lift", "section-reveal"],
    interactionProfile: ["card-hover", "carousel-swipe", "cta-pulse"],
    feedbackProfile: ["loading", "success", "validation"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "low" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "mobile", touchPriority: true },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: true },
  },
  growth: {
    seoPresentation: "Local business schema, menu structured data, location pages",
    conversionStrategy: "Reservation widget prominent, hours/location visible",
    trustBuilding: "Chef credentials, press mentions, guest reviews, awards",
  },
  ai: {
    layoutIds: ["full-bleed", "sidebar-left", "editorial-reveal"],
    heroComponents: ["hero-full-bleed", "hero-split", "gallery"],
    navComponents: ["navbar", "drawer"],
    ctaComponents: ["primary-button", "reservation-form"],
    motionPresets: ["hero-media", "scroll-reveal-up", "card-lift"],
    typographyProfiles: ["latin-ltr", "latin-rtl"],
    spacingScale: "generous",
    pageFlow: ["hero", "menu", "story", "gallery", "reviews", "reserve"],
    primaryButtonVariant: "primary",
    cardComponents: ["menu-card", "gallery-card", "testimonial"],
    feedbackStates: ["loading", "success", "validation"],
    confidence: 0.93,
  },
});
