import { defineSectorDna } from "@/lib/design-platform/sector-dna/sectors/define";

export const SAAS_SECTOR_DNA = defineSectorDna({
  id: "saas",
  name: "SaaS",
  experienceProfiles: ["technical", "corporate", "executive"],
  personality: {
    brand: "Innovative, scalable, outcome-driven",
    visual: "Clean dashboards, data clarity, product-forward UI",
    emotionalTone: "Confident optimism with operational trust",
    philosophy: "Show value fast — reduce time-to-understanding",
    targetAudience: "Decision-makers, product teams, IT buyers",
  },
  visual: {
    typographyProfile: "latin-ltr",
    colorStrategy: {
      primaryEmphasis: "semantic.brand.primary",
      accentEmphasis: "semantic.brand.accent",
      surfaceEmphasis: "semantic.surface.base",
      modePreference: "light",
    },
    surfaceStrategy: "layered",
    spacingBehavior: "balanced",
    gridPreference: "standard",
    imageDirection: "Product UI screenshots, abstract gradients, team collaboration",
    iconStyle: "outline",
    illustrationStyle: "Isometric product diagrams, minimal line art",
  },
  components: {
    preferredComponents: [
      "navbar",
      "sidebar",
      "primary-button",
      "feature-grid",
      "pricing-table",
      "testimonial",
      "stats",
      "tabs",
      "data-table",
      "modal",
    ],
    heroStrategy: "Split hero — headline + product screenshot with social proof strip",
    navigationStyle: "Sticky top nav with product/features/pricing/docs CTAs",
    ctaStrategy: "Primary: Start free trial · Secondary: Book demo",
    contentHierarchy: "Problem → Solution → Features → Proof → Pricing → CTA",
    cardStyle: "Elevated feature cards with icon, title, benefit copy",
  },
  experience: {
    experienceProfiles: ["technical", "corporate", "executive"],
    motionProfile: ["page-enter", "grid-stagger", "modal-enter", "focus-ring"],
    interactionProfile: ["btn-hover", "form-focus", "table-sort", "tab-switch"],
    feedbackProfile: ["loading", "success", "error", "saving"],
    accessibilityProfile: { contrastLevel: "AA", motionSensitivity: "medium" },
    responsiveProfile: { mobileFirst: true, primaryViewport: "desktop", touchPriority: false },
    directionProfile: { rtlOptimized: true, mirrorNavigation: true, mirrorCarousel: true },
  },
  growth: {
    seoPresentation: "Structured product pages, feature schema, comparison tables",
    conversionStrategy: "Free trial above fold, pricing transparency, case studies",
    trustBuilding: "SOC2 badges, customer logos, G2 ratings, uptime stats",
  },
  ai: {
    layoutIds: ["single-column", "sidebar-left", "dashboard-grid"],
    heroComponents: ["hero-split", "hero-centered", "feature-grid"],
    navComponents: ["navbar", "sidebar", "tabs"],
    ctaComponents: ["primary-button", "split-button", "cta-banner"],
    motionPresets: ["page-enter", "grid-stagger", "modal-enter"],
    typographyProfiles: ["latin-ltr"],
    spacingScale: "balanced",
    pageFlow: ["hero", "logos", "features", "testimonials", "pricing", "cta"],
    primaryButtonVariant: "primary",
    cardComponents: ["feature-card", "pricing-card", "stat-card"],
    feedbackStates: ["loading", "success", "error"],
    confidence: 0.94,
  },
});
