import type {
  PremiumTemplateDefinition,
  PremiumTemplateId,
  PremiumTemplateSection,
} from "@/lib/ai-core/premium-templates/types";
import type { DesignRendererComponentId } from "@/lib/ai-core/design-renderer/types";

function section(
  key: string,
  label: string,
  sortOrder: number,
  componentId: DesignRendererComponentId,
  contentGoal: string,
  assetRole?: PremiumTemplateSection["assetRole"],
): PremiumTemplateSection {
  return { key, label, sortOrder, componentId, contentGoal, assetRole };
}

/**
 * Premium Templates System — world-class industry packs.
 * Configurable via AI (goal / audience / brand style), not static-only.
 */
export const PREMIUM_TEMPLATE_CATALOG: Record<
  PremiumTemplateId,
  PremiumTemplateDefinition
> = {
  "luxury-business": {
    id: "luxury-business",
    name: "Luxury Business",
    description:
      "Editorial luxury corporate template for premium firms, consultancies, and high-end brands.",
    industryId: "business",
    smartTemplateId: "agency",
    designStyle: "Luxury editorial",
    designPreset: "luxury",
    layoutStyle: "corporate-trust",
    brandStyles: ["luxury", "editorial", "premium", "corporate"],
    defaultWebsiteGoal: "lead-gen",
    pageStructure: [
      {
        name: "Home",
        path: "/",
        purpose: "Establish prestige and capture qualified inquiries",
        keySections: ["Hero", "Services", "Features", "Testimonials", "Contact"],
      },
      {
        name: "Services",
        path: "/services",
        purpose: "Detail premium offerings",
        keySections: ["Services", "Process", "CTA"],
      },
      {
        name: "About",
        path: "/about",
        purpose: "Build trust through people and story",
        keySections: ["Team", "Story", "Proof"],
      },
      {
        name: "Insights",
        path: "/insights",
        purpose: "Thought leadership",
        keySections: ["Blog"],
      },
      {
        name: "Contact",
        path: "/contact",
        purpose: "Convert high-intent leads",
        keySections: ["Contact", "FAQ"],
      },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroLuxury", "Open with refined brand presence", "hero"),
      section("services", "Services", 20, "ServicesModern", "Present premium offerings", "service"),
      section("features", "Features", 30, "FeaturesModern", "Clarify differentiators", "section"),
      section("gallery", "Showcase", 40, "PortfolioGallery", "Visual proof of craft", "section"),
      section("testimonials", "Testimonials", 50, "TestimonialsModern", "Build executive trust"),
      section("team", "Team", 60, "TeamSection", "Humanize expertise"),
      section("faq", "FAQ", 70, "FaqAccordion", "Handle objections"),
      section("contact", "Contact", 80, "ContactSection", "Capture qualified leads"),
      section("cta", "CTA", 90, "CtaSplit", "Close with decisive next step"),
    ],
    recommendedComponents: [
      "SiteHeaderTransparent",
      "HeroLuxury",
      "ServicesModern",
      "FeaturesModern",
      "PortfolioGallery",
      "TestimonialsModern",
      "TeamSection",
      "FaqAccordion",
      "ContactSection",
      "CtaSplit",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Cinematic luxury brand atmosphere, refined materials, no text" },
      { role: "service", brief: "Premium service lifestyle photography" },
      { role: "section", brief: "Editorial detail shots for features" },
      { role: "gallery", brief: "Portfolio-quality brand moments" },
    ],
    contentStrategy: {
      brandVoice: "refined, confident, concise, exclusive without arrogance",
      messagingPillars: ["Prestige", "Expertise", "Discretion", "Results"],
      proofPoints: ["Select clients", "Outcomes", "Credentials"],
      seoTopics: ["luxury consulting", "premium business services", "executive advisory"],
      ctaHierarchy: ["Request consultation", "View services", "Read insights"],
      audienceNotes: "Affluent decision-makers and discerning clients",
    },
    keywords: ["luxury", "premium", "executive", "consultancy", "private", "high-end", "business"],
    colorHints: {
      primary: "#1A1A1A",
      secondary: "#C6A75E",
      accent: "#8B7355",
      background: "#F8F5F0",
    },
    typographyHints: { display: "Playfair Display", body: "Source Sans 3" },
    conversionPath: [
      "Attract",
      "Prestige story",
      "Services",
      "Proof",
      "Consultation",
    ],
  },

  saas: {
    id: "saas",
    name: "SaaS",
    description:
      "Product-led SaaS template with features, pricing, social proof, and trial CTAs.",
    industryId: "saas",
    smartTemplateId: "saas-startup",
    designStyle: "Modern product",
    designPreset: "tech",
    layoutStyle: "product-saas",
    brandStyles: ["modern", "tech", "minimal", "futuristic"],
    defaultWebsiteGoal: "conversion",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Explain value and drive trial", keySections: ["Hero", "Features", "Pricing", "FAQ"] },
      { name: "Product", path: "/product", purpose: "Deep-dive capabilities", keySections: ["Features", "Showcase"] },
      { name: "Pricing", path: "/pricing", purpose: "Convert plans", keySections: ["Pricing", "FAQ"] },
      { name: "Customers", path: "/customers", purpose: "Social proof", keySections: ["Testimonials"] },
      { name: "Contact", path: "/contact", purpose: "Sales / demo", keySections: ["Contact"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroProduct", "Communicate product value fast", "product"),
      section("features", "Features", 20, "FeaturesModern", "Show capabilities", "section"),
      section("showcase", "Product showcase", 30, "ProductShowcase", "Highlight flagship workflow", "product"),
      section("testimonials", "Testimonials", 40, "TestimonialsModern", "Prove adoption"),
      section("pricing", "Pricing", 50, "PricingModern", "Clarify plans"),
      section("faq", "FAQ", 60, "FaqAccordion", "Reduce friction"),
      section("blog", "Insights", 70, "BlogSection", "Support SEO and education"),
      section("cta", "CTA", 80, "CtaSplit", "Drive trial or demo"),
      section("contact", "Contact", 90, "ContactCta", "Capture sales leads"),
    ],
    recommendedComponents: [
      "NavModern",
      "HeroProduct",
      "FeaturesModern",
      "ProductShowcase",
      "TestimonialsModern",
      "PricingModern",
      "FaqAccordion",
      "BlogSection",
      "CtaSplit",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Clean product UI mock in modern workspace" },
      { role: "product", brief: "SaaS dashboard / workflow visuals" },
      { role: "section", brief: "Feature illustration photography" },
    ],
    contentStrategy: {
      brandVoice: "clear, energetic, benefit-led, credible",
      messagingPillars: ["Speed", "Clarity", "Scale", "Trust"],
      proofPoints: ["Customer logos", "Metrics", "Integrations"],
      seoTopics: ["saas platform", "productivity software", "workflow automation"],
      ctaHierarchy: ["Start free trial", "Book a demo", "See pricing"],
      audienceNotes: "Startup and mid-market operators evaluating tools",
    },
    keywords: ["saas", "software", "platform", "startup", "product", "subscription"],
    colorHints: {
      primary: "#4F46E5",
      secondary: "#0EA5E9",
      accent: "#22C55E",
      background: "#F8FAFC",
    },
    typographyHints: { display: "Sora", body: "Inter" },
  },

  "real-estate": {
    id: "real-estate",
    name: "Real Estate",
    description:
      "Property-led template with listings, locations, trust, and inquiry paths.",
    industryId: "real-estate",
    smartTemplateId: "real-estate",
    designStyle: "Property showcase",
    designPreset: "luxury",
    layoutStyle: "property-showcase",
    brandStyles: ["luxury", "corporate", "modern"],
    defaultWebsiteGoal: "lead-gen",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Feature properties and capture inquiries", keySections: ["Hero", "Listings", "Locations", "Contact"] },
      { name: "Listings", path: "/listings", purpose: "Browse properties", keySections: ["Listings", "Filters"] },
      { name: "Neighborhoods", path: "/neighborhoods", purpose: "Sell location value", keySections: ["Locations"] },
      { name: "About", path: "/about", purpose: "Agent credibility", keySections: ["Team"] },
      { name: "Contact", path: "/contact", purpose: "Inquiry conversion", keySections: ["Contact"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroProperty", "Drive listing discovery", "hero"),
      section("listings", "Featured listings", 20, "PropertyListings", "Surface best properties", "product"),
      section("features", "Why us", 30, "FeatureHighlights", "Differentiate brokerage", "section"),
      section("locations", "Locations", 40, "MapsSection", "Sell location value"),
      section("testimonials", "Testimonials", 50, "TestimonialsModern", "Buyer/seller proof"),
      section("team", "Agents", 60, "TeamSection", "Build agent trust"),
      section("faq", "FAQ", 70, "FaqAccordion", "Buying process clarity"),
      section("contact", "Contact", 80, "ContactSection", "Capture inquiries"),
      section("cta", "CTA", 90, "CtaBand", "Push valuation or tour request"),
    ],
    recommendedComponents: [
      "SiteHeader",
      "HeroProperty",
      "PropertyListings",
      "FeatureHighlights",
      "MapsSection",
      "TestimonialsModern",
      "TeamSection",
      "ContactSection",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Stunning property exterior or interior hero" },
      { role: "product", brief: "Featured listing photography" },
      { role: "section", brief: "Neighborhood lifestyle imagery" },
    ],
    contentStrategy: {
      brandVoice: "trustworthy, aspirational, local-expert",
      messagingPillars: ["Inventory", "Expertise", "Neighborhoods", "Results"],
      proofPoints: ["Closed deals", "Market knowledge", "Client stories"],
      seoTopics: ["homes for sale", "real estate agency", "property listings"],
      ctaHierarchy: ["Schedule a tour", "Get a valuation", "Contact an agent"],
      audienceNotes: "Home buyers, sellers, and investors",
    },
    keywords: ["real estate", "property", "homes", "listing", "realtor", "apartment"],
    colorHints: {
      primary: "#1B4332",
      secondary: "#D4A373",
      accent: "#40916C",
      background: "#F7F7F2",
    },
    typographyHints: { display: "Libre Baskerville", body: "DM Sans" },
  },

  automotive: {
    id: "automotive",
    name: "Automotive",
    description:
      "Luxury vehicle showroom template with models, inventory, and booking CTAs.",
    industryId: "automotive",
    smartTemplateId: "automotive-luxury",
    designStyle: "Dark luxury showroom",
    designPreset: "luxury",
    layoutStyle: "vehicle-showroom",
    brandStyles: ["luxury", "premium", "modern", "cinematic"],
    defaultWebsiteGoal: "lead-gen",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Showcase flagship models", keySections: ["Hero", "Vehicles", "Compare", "Inventory", "Finance", "Booking"] },
      { name: "Models", path: "/models", purpose: "Browse vehicles", keySections: ["Vehicles", "Detail", "Compare"] },
      { name: "Model detail", path: "/models/[slug]", purpose: "Vehicle detail page", keySections: ["Detail", "Finance", "Appointment"] },
      { name: "Inventory", path: "/inventory", purpose: "Available stock", keySections: ["Inventory", "Finance"] },
      { name: "Services", path: "/services", purpose: "Service & finance", keySections: ["Services", "Appointment"] },
      { name: "Contact", path: "/contact", purpose: "Test drive / inquiry", keySections: ["Branches", "Appointment"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroLuxuryShowcase", "Establish premium brand presence", "hero"),
      section("vehicles", "Vehicle showcase", 20, "VehicleShowcase", "Highlight flagship models", "product"),
      section("compare", "Compare", 30, "VehicleComparison", "Help buyers choose a model"),
      section("inventory", "Inventory", 40, "InventoryGrid", "Browse available stock", "product"),
      section("finance", "Finance", 50, "FinanceCalculator", "Estimate monthly payments"),
      section("testimonials", "Testimonials", 60, "TestimonialsSlider", "Owner stories", "section"),
      section("maps", "Locations", 70, "BranchesMap", "Find a showroom"),
      section("appointment", "Appointments", 80, "AppointmentCalendar", "Book a test drive"),
      section("cta", "CTA", 90, "BookingCta", "Drive appointment conversions"),
      section("contact", "Contact", 100, "ContactCta", "Capture inquiries"),
    ],
    recommendedComponents: [
      "SiteHeaderTransparent",
      "HeroLuxuryShowcase",
      "VehicleShowcase",
      "VehicleDetail",
      "VehicleComparison",
      "InventoryGrid",
      "FinanceCalculator",
      "TestimonialsSlider",
      "BranchesMap",
      "AppointmentCalendar",
      "BookingCta",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Cinematic flagship vehicle on premium set" },
      { role: "product", brief: "Model detail and trim photography" },
      { role: "service", brief: "Service bay or concierge experience" },
    ],
    contentStrategy: {
      brandVoice: "powerful, precise, performance-minded",
      messagingPillars: ["Performance", "Craft", "Selection", "Ownership"],
      proofPoints: ["Model range", "Awards", "Owner reviews"],
      seoTopics: ["luxury cars", "vehicle showroom", "test drive"],
      ctaHierarchy: ["Book a test drive", "View inventory", "Contact sales"],
      audienceNotes: "Enthusiasts and premium buyers",
    },
    keywords: ["automotive", "car", "dealership", "vehicle", "showroom", "luxury car"],
    colorHints: {
      primary: "#0B0B0F",
      secondary: "#E11D48",
      accent: "#A1A1AA",
      background: "#111113",
    },
    typographyHints: { display: "Oswald", body: "IBM Plex Sans" },
  },

  tourism: {
    id: "tourism",
    name: "Tourism",
    description:
      "Travel premium template with destinations, tours, packages, and booking.",
    industryId: "tourism",
    smartTemplateId: "tourism-premium",
    designStyle: "Travel premium",
    designPreset: "luxury",
    layoutStyle: "travel-premium",
    brandStyles: ["luxury", "cinematic", "editorial", "premium"],
    defaultWebsiteGoal: "booking",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Inspire travel and drive booking", keySections: ["Hero", "Destinations", "Tours", "Booking"] },
      { name: "Destinations", path: "/destinations", purpose: "Explore places", keySections: ["Gallery"] },
      { name: "Tours", path: "/tours", purpose: "Package selection", keySections: ["Packages"] },
      { name: "About", path: "/about", purpose: "Trust and expertise", keySections: ["Why", "Stories"] },
      { name: "Booking", path: "/booking", purpose: "Conversion", keySections: ["Booking", "FAQ"] },
    ],
    sections: [
      section("hero", "Hero destination", 10, "HeroFullBleed", "Create destination desire", "hero"),
      section("destinations", "Featured destinations", 20, "DestinationsGallery", "Showcase variety", "section"),
      section("tours", "Popular tours", 30, "TourPackagesGrid", "Convert to packages", "product"),
      section("features", "Why travel with us", 40, "FeatureHighlights", "Trust and differentiators", "section"),
      section("stories", "Traveler stories", 50, "TestimonialsCarousel", "Social proof"),
      section("booking", "Booking", 60, "BookingSection", "Capture booking intent"),
      section("faq", "FAQ", 70, "FaqAccordion", "Trip logistics"),
      section("contact", "Contact", 80, "ContactSection", "Expert inquiry"),
      section("cta", "CTA", 90, "TravelCtaBand", "Final booking push"),
    ],
    recommendedComponents: [
      "SiteHeaderTransparent",
      "HeroFullBleed",
      "DestinationsGallery",
      "TourPackagesGrid",
      "FeatureHighlights",
      "TestimonialsCarousel",
      "BookingSection",
      "TravelCtaBand",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Cinematic destination landscape hero" },
      { role: "gallery", brief: "Destination and experience lifestyle shots" },
      { role: "product", brief: "Tour and package mood imagery" },
    ],
    contentStrategy: {
      brandVoice: "inspirational, wanderlust-driven, clear and trustworthy",
      messagingPillars: ["Destinations", "Experiences", "Ease", "Trust"],
      proofPoints: ["Traveler stories", "Licensed operator", "Curated itineraries"],
      seoTopics: ["travel packages", "tour destinations", "vacation booking"],
      ctaHierarchy: ["Book a trip", "Explore destinations", "Request itinerary"],
      audienceNotes: "Leisure travelers seeking curated experiences",
    },
    keywords: ["tourism", "travel", "tour", "destination", "vacation", "holiday"],
    colorHints: {
      primary: "#0C2D48",
      secondary: "#D4A373",
      accent: "#E9C46A",
      background: "#F7F3EE",
    },
    typographyHints: { display: "Cormorant Garamond", body: "Nunito Sans" },
  },

  restaurant: {
    id: "restaurant",
    name: "Restaurant",
    description:
      "Hospitality template with menu highlights, atmosphere, and reservations.",
    industryId: "restaurant",
    smartTemplateId: "restaurant-premium",
    designStyle: "Culinary editorial",
    designPreset: "luxury",
    layoutStyle: "editorial-hero",
    brandStyles: ["luxury", "editorial", "modern", "warm"],
    defaultWebsiteGoal: "booking",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Appetite + reservation", keySections: ["Hero", "Menu", "Reservations"] },
      { name: "Menu", path: "/menu", purpose: "Signature dishes", keySections: ["Menu"] },
      { name: "About", path: "/about", purpose: "Chef / story", keySections: ["Story", "Team"] },
      { name: "Reservations", path: "/reservations", purpose: "Book a table", keySections: ["Booking", "Map"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroImage", "Set culinary atmosphere", "hero"),
      section("menu", "Menu highlights", 20, "MenuHighlights", "Showcase signature dishes", "product"),
      section("gallery", "Atmosphere", 30, "GalleryGrid", "Dining room mood", "section"),
      section("features", "Our craft", 40, "FeatureHighlights", "Ingredients and philosophy", "section"),
      section("testimonials", "Guest stories", 50, "TestimonialsCarousel", "Social proof"),
      section("booking", "Reservations", 60, "ReservationSection", "Book a table"),
      section("maps", "Find us", 70, "MapsSection", "Location and hours"),
      section("contact", "Contact", 80, "ContactSection", "Private dining / events"),
      section("cta", "CTA", 90, "CtaBand", "Reserve tonight"),
    ],
    recommendedComponents: [
      "SiteHeaderTransparent",
      "HeroImage",
      "MenuHighlights",
      "GalleryGrid",
      "ReservationSection",
      "MapsSection",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Editorial plated dish or dining atmosphere" },
      { role: "product", brief: "Signature menu item photography" },
      { role: "gallery", brief: "Interior and hospitality moments" },
    ],
    contentStrategy: {
      brandVoice: "warm, sensory, inviting, refined",
      messagingPillars: ["Craft", "Atmosphere", "Seasonality", "Hospitality"],
      proofPoints: ["Chef credentials", "Guest reviews", "Signature dishes"],
      seoTopics: ["restaurant reservations", "fine dining", "menu"],
      ctaHierarchy: ["Reserve a table", "View menu", "Private events"],
      audienceNotes: "Diners seeking memorable hospitality",
    },
    keywords: ["restaurant", "dining", "menu", "chef", "reservation", "cafe"],
    colorHints: {
      primary: "#3D1F14",
      secondary: "#C45C26",
      accent: "#E8D5B7",
      background: "#FBF7F2",
    },
    typographyHints: { display: "Fraunces", body: "Karla" },
  },

  healthcare: {
    id: "healthcare",
    name: "Healthcare",
    description:
      "Calm clinical template with services, doctors, and appointment booking.",
    industryId: "clinic",
    smartTemplateId: "clinic",
    designStyle: "Clinical trust",
    designPreset: "corporate",
    layoutStyle: "corporate-trust",
    brandStyles: ["corporate", "minimal", "trust", "calm"],
    defaultWebsiteGoal: "booking",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Care overview + book", keySections: ["Hero", "Services", "Doctors", "Booking"] },
      { name: "Services", path: "/services", purpose: "Care offerings", keySections: ["Services"] },
      { name: "Doctors", path: "/doctors", purpose: "Clinician trust", keySections: ["Team"] },
      { name: "Appointments", path: "/appointments", purpose: "Booking", keySections: ["Booking", "FAQ"] },
      { name: "Contact", path: "/contact", purpose: "Location + inquiry", keySections: ["Map", "Contact"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroSplit", "Communicate care and trust", "hero"),
      section("services", "Care services", 20, "CareServices", "Explain offerings", "service"),
      section("features", "Why patients choose us", 30, "FeaturesModern", "Safety and outcomes", "section"),
      section("team", "Doctors", 40, "DoctorProfiles", "Build clinician trust"),
      section("testimonials", "Patient stories", 50, "TestimonialsModern", "Empathy and proof"),
      section("booking", "Appointments", 60, "BookingForm", "Book care"),
      section("faq", "FAQ", 70, "FaqAccordion", "Insurance and process"),
      section("maps", "Locations", 80, "MapsSection", "Find the clinic"),
      section("contact", "Contact", 90, "ContactSection", "Patient intake"),
    ],
    recommendedComponents: [
      "SiteHeader",
      "HeroSplit",
      "CareServices",
      "DoctorProfiles",
      "BookingForm",
      "FaqAccordion",
      "MapsSection",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Calm modern clinic environment, welcoming light" },
      { role: "service", brief: "Care service photography without clinical fear" },
      { role: "section", brief: "Doctor-patient trust moments" },
    ],
    contentStrategy: {
      brandVoice: "calm, clear, compassionate, professional",
      messagingPillars: ["Care", "Expertise", "Access", "Trust"],
      proofPoints: ["Credentials", "Patient outcomes", "Accreditations"],
      seoTopics: ["clinic appointments", "healthcare services", "specialists"],
      ctaHierarchy: ["Book appointment", "Meet our doctors", "Contact clinic"],
      audienceNotes: "Patients and families seeking trusted care",
    },
    keywords: ["healthcare", "clinic", "medical", "doctor", "hospital", "patient"],
    colorHints: {
      primary: "#0F766E",
      secondary: "#155E75",
      accent: "#67E8F9",
      background: "#F8FAFC",
    },
    typographyHints: { display: "Manrope", body: "Source Sans 3" },
  },

  ecommerce: {
    id: "ecommerce",
    name: "E-commerce",
    description:
      "Commerce template with product grids, collections, and purchase CTAs.",
    industryId: "ecommerce",
    smartTemplateId: "ecommerce-store",
    designStyle: "Modern commerce",
    designPreset: "modern",
    layoutStyle: "commerce-grid",
    brandStyles: ["modern", "minimal", "commercial", "creative"],
    defaultWebsiteGoal: "ecommerce",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Discover and shop", keySections: ["Hero", "Collections", "Products", "CTA"] },
      { name: "Shop", path: "/shop", purpose: "Product catalog", keySections: ["Products"] },
      { name: "Collections", path: "/collections", purpose: "Category browse", keySections: ["Collections"] },
      { name: "About", path: "/about", purpose: "Brand story", keySections: ["Story"] },
      { name: "Contact", path: "/contact", purpose: "Support", keySections: ["Contact", "FAQ"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroSplit", "Lead with product story", "hero"),
      section("collections", "Collections", 20, "CollectionsGrid", "Organize browsing", "section"),
      section("products", "Featured products", 30, "ProductGrid", "Drive discovery", "product"),
      section("showcase", "Product showcase", 40, "ProductShowcase", "Hero SKU moment", "product"),
      section("features", "Why shop with us", 50, "FeaturesModern", "Shipping trust and quality", "section"),
      section("testimonials", "Reviews", 60, "TestimonialsModern", "Purchase confidence"),
      section("faq", "FAQ", 70, "FaqAccordion", "Shipping and returns"),
      section("cta", "CTA", 80, "CtaSplit", "Push to shop"),
      section("contact", "Contact", 90, "ContactCta", "Support"),
    ],
    recommendedComponents: [
      "NavModern",
      "HeroSplit",
      "CollectionsGrid",
      "ProductGrid",
      "ProductShowcase",
      "FeaturesModern",
      "TestimonialsModern",
      "CtaSplit",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Premium product lifestyle hero" },
      { role: "product", brief: "Clean product packshots and lifestyle" },
      { role: "gallery", brief: "Collection mood boards" },
    ],
    contentStrategy: {
      brandVoice: "crisp, desirable, benefit-led",
      messagingPillars: ["Quality", "Selection", "Ease", "Trust"],
      proofPoints: ["Reviews", "Shipping policy", "Materials"],
      seoTopics: ["online store", "shop products", "collections"],
      ctaHierarchy: ["Shop now", "View collection", "Add to cart"],
      audienceNotes: "Online shoppers evaluating brand and product fit",
    },
    keywords: ["ecommerce", "shop", "store", "retail", "product", "cart"],
    colorHints: {
      primary: "#111827",
      secondary: "#F59E0B",
      accent: "#2563EB",
      background: "#FFFFFF",
    },
    typographyHints: { display: "Space Grotesk", body: "Inter" },
  },

  agency: {
    id: "agency",
    name: "Agency",
    description:
      "Creative agency template with portfolio, process, and lead capture.",
    industryId: "agency",
    smartTemplateId: "agency",
    designStyle: "Studio portfolio",
    designPreset: "creative",
    layoutStyle: "studio-portfolio",
    brandStyles: ["creative", "modern", "minimal", "bold"],
    defaultWebsiteGoal: "lead-gen",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Prove craft and win briefs", keySections: ["Hero", "Portfolio", "Services", "Contact"] },
      { name: "Work", path: "/work", purpose: "Case studies", keySections: ["Portfolio"] },
      { name: "Services", path: "/services", purpose: "Capabilities", keySections: ["Services", "Process"] },
      { name: "About", path: "/about", purpose: "Team and culture", keySections: ["Team"] },
      { name: "Contact", path: "/contact", purpose: "Start a project", keySections: ["Contact"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroVideo", "Immersive first impression", "hero"),
      section("portfolio", "Selected work", 20, "PortfolioGallery", "Prove craft", "section"),
      section("services", "Services", 30, "ServicesModern", "Capabilities", "service"),
      section("process", "Process", 40, "ProcessSteps", "How engagement works", "section"),
      section("features", "Capabilities", 50, "FeaturesBento", "Skill breadth", "section"),
      section("testimonials", "Client love", 60, "TestimonialsModern", "Proof"),
      section("team", "Team", 70, "TeamSection", "People behind the work"),
      section("blog", "Insights", 80, "BlogSection", "Thought leadership"),
      section("contact", "Contact", 90, "ContactSection", "Start a project"),
    ],
    recommendedComponents: [
      "SiteHeaderTransparent",
      "HeroVideo",
      "PortfolioGallery",
      "ServicesModern",
      "ProcessSteps",
      "TestimonialsModern",
      "TeamSection",
      "ContactSection",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Creative studio or campaign atmosphere" },
      { role: "gallery", brief: "Portfolio case study stills" },
      { role: "section", brief: "Process and teamwork moments" },
    ],
    contentStrategy: {
      brandVoice: "sharp, creative, confident, collaborative",
      messagingPillars: ["Craft", "Strategy", "Impact", "Partnership"],
      proofPoints: ["Case studies", "Client logos", "Awards"],
      seoTopics: ["creative agency", "brand design", "digital studio"],
      ctaHierarchy: ["Start a project", "View work", "Book a call"],
      audienceNotes: "Brand and marketing leaders hiring agencies",
    },
    keywords: ["agency", "studio", "creative", "branding", "design", "marketing"],
    colorHints: {
      primary: "#111111",
      secondary: "#7C3AED",
      accent: "#F43F5E",
      background: "#FAFAFA",
    },
    typographyHints: { display: "Syne", body: "IBM Plex Sans" },
  },

  education: {
    id: "education",
    name: "Education",
    description:
      "Campus/education template with programs, admissions, and inquiry CTAs.",
    industryId: "education",
    smartTemplateId: "education-campus",
    designStyle: "Campus modern",
    designPreset: "corporate",
    layoutStyle: "campus-education",
    brandStyles: ["corporate", "modern", "trust", "friendly"],
    defaultWebsiteGoal: "content",
    pageStructure: [
      { name: "Home", path: "/", purpose: "Programs + admissions interest", keySections: ["Hero", "Programs", "Admissions"] },
      { name: "Programs", path: "/programs", purpose: "Course catalog", keySections: ["Programs"] },
      { name: "Admissions", path: "/admissions", purpose: "Apply / inquire", keySections: ["Admissions", "FAQ"] },
      { name: "Campus", path: "/campus", purpose: "Life on campus", keySections: ["Gallery", "Team"] },
      { name: "Contact", path: "/contact", purpose: "Counselor contact", keySections: ["Contact", "Map"] },
    ],
    sections: [
      section("hero", "Hero", 10, "HeroSplit", "Welcome prospective students", "hero"),
      section("programs", "Programs", 20, "ProgramsGrid", "Promote courses", "product"),
      section("features", "Why learn here", 30, "FeaturesModern", "Outcomes and support", "section"),
      section("gallery", "Campus life", 40, "GalleryGrid", "Atmosphere", "section"),
      section("team", "Faculty", 50, "TeamSection", "Educator trust"),
      section("testimonials", "Student stories", 60, "TestimonialsCarousel", "Outcomes proof"),
      section("blog", "Resources", 70, "BlogSection", "Education content"),
      section("admissions", "Admissions", 80, "AdmissionsCta", "Drive enrollment"),
      section("contact", "Contact", 90, "ContactSection", "Counselor inquiry"),
    ],
    recommendedComponents: [
      "SiteHeader",
      "HeroSplit",
      "ProgramsGrid",
      "FeaturesModern",
      "GalleryGrid",
      "TeamSection",
      "AdmissionsCta",
      "ContactSection",
      "SiteFooter",
    ],
    imageRequirements: [
      { role: "hero", brief: "Bright campus or learning environment" },
      { role: "product", brief: "Program and classroom moments" },
      { role: "section", brief: "Student success lifestyle imagery" },
    ],
    contentStrategy: {
      brandVoice: "encouraging, clear, credible, future-focused",
      messagingPillars: ["Programs", "Outcomes", "Community", "Support"],
      proofPoints: ["Graduate outcomes", "Faculty", "Accreditation"],
      seoTopics: ["education programs", "admissions", "campus life"],
      ctaHierarchy: ["Apply now", "Explore programs", "Talk to admissions"],
      audienceNotes: "Students and parents evaluating programs",
    },
    keywords: ["education", "school", "university", "campus", "course", "admissions"],
    colorHints: {
      primary: "#1D4ED8",
      secondary: "#0F766E",
      accent: "#F59E0B",
      background: "#F8FAFC",
    },
    typographyHints: { display: "Literata", body: "Nunito Sans" },
  },
};

export const PREMIUM_TEMPLATE_IDS = Object.keys(
  PREMIUM_TEMPLATE_CATALOG,
) as PremiumTemplateId[];

export function isPremiumTemplateId(value: unknown): value is PremiumTemplateId {
  return (
    typeof value === "string" &&
    Object.prototype.hasOwnProperty.call(PREMIUM_TEMPLATE_CATALOG, value)
  );
}

export function getPremiumTemplate(
  id: PremiumTemplateId,
): PremiumTemplateDefinition {
  return PREMIUM_TEMPLATE_CATALOG[id];
}

export function listPremiumTemplates(): PremiumTemplateDefinition[] {
  return PREMIUM_TEMPLATE_IDS.map((id) => PREMIUM_TEMPLATE_CATALOG[id]);
}

export function premiumTemplateForIndustry(
  industryId: string,
): PremiumTemplateDefinition {
  const map: Record<string, PremiumTemplateId> = {
    tourism: "tourism",
    restaurant: "restaurant",
    ecommerce: "ecommerce",
    saas: "saas",
    "real-estate": "real-estate",
    automotive: "automotive",
    agency: "agency",
    clinic: "healthcare",
    healthcare: "healthcare",
    education: "education",
    business: "luxury-business",
  };
  const id = map[industryId] ?? "luxury-business";
  return PREMIUM_TEMPLATE_CATALOG[id];
}
