import type { IndustryId, IndustryProfile } from "@/lib/ai-core/templates/types";

/**
 * Industry Intelligence profiles — foundation for AI Template Engine (Phase 6).
 */
export const INDUSTRY_PROFILES: Record<IndustryId, IndustryProfile> = {
  restaurant: {
    id: "restaurant",
    label: "Restaurant",
    description:
      "Hospitality sites with menus, reservations, ambiance, and location trust.",
    keywords: [
      "restaurant",
      "cafe",
      "coffee",
      "bistro",
      "dining",
      "menu",
      "food",
      "chef",
      "hospitality",
      "bar",
      "bakery",
    ],
    layoutStyle: "editorial-hero",
    sections: [
      "Hero",
      "Signature dishes",
      "Menu highlights",
      "Reservations",
      "Atmosphere",
      "Location",
      "Reviews",
      "Contact",
    ],
    designPreset: "luxury",
    requiredFeatures: ["menu", "reservations", "gallery", "location-map", "reviews"],
    suggestedPages: ["Home", "Menu", "Reservations", "About", "Contact"],
    contentTone: "warm and appetizing",
    industryPattern: "hospitality-dining",
  },
  ecommerce: {
    id: "ecommerce",
    label: "Ecommerce",
    description:
      "Product-led storefronts with catalog, cart signals, and conversion sections.",
    keywords: [
      "ecommerce",
      "e-commerce",
      "shop",
      "store",
      "product",
      "cart",
      "checkout",
      "retail",
      "marketplace",
      "sku",
    ],
    layoutStyle: "commerce-grid",
    sections: [
      "Hero offer",
      "Featured products",
      "Collections",
      "Benefits",
      "Social proof",
      "Shipping & returns",
      "FAQ",
      "CTA",
    ],
    designPreset: "modern",
    requiredFeatures: [
      "product-catalog",
      "featured-products",
      "cart-cta",
      "trust-badges",
      "faq",
    ],
    suggestedPages: ["Home", "Shop", "Product", "Cart", "About", "Contact"],
    contentTone: "clear and conversion-focused",
    industryPattern: "retail-commerce",
  },
  saas: {
    id: "saas",
    label: "SaaS",
    description:
      "Software product marketing with features, pricing, and onboarding CTAs.",
    keywords: [
      "saas",
      "software",
      "platform",
      "subscription",
      "dashboard",
      "api",
      "b2b",
      "startup",
      "product",
      "cloud",
    ],
    layoutStyle: "product-saas",
    sections: [
      "Hero",
      "Problem",
      "Solution",
      "Features",
      "How it works",
      "Pricing",
      "Testimonials",
      "CTA",
    ],
    designPreset: "modern",
    requiredFeatures: [
      "pricing",
      "feature-grid",
      "integrations",
      "auth-cta",
      "demo-request",
    ],
    suggestedPages: ["Home", "Features", "Pricing", "Docs", "Login", "Contact"],
    contentTone: "confident and product-led",
    industryPattern: "product-saas",
  },
  "real-estate": {
    id: "real-estate",
    label: "Real Estate",
    description:
      "Property marketing with listings, neighborhoods, and inquiry flows.",
    keywords: [
      "real estate",
      "real-estate",
      "property",
      "homes",
      "realtor",
      "listings",
      "apartment",
      "housing",
      "broker",
      "mortgage",
    ],
    layoutStyle: "property-showcase",
    sections: [
      "Hero search",
      "Featured listings",
      "Neighborhoods",
      "Buying process",
      "Agent trust",
      "Testimonials",
      "Inquiry form",
      "Contact",
    ],
    designPreset: "corporate",
    requiredFeatures: [
      "listings",
      "property-search",
      "inquiry-form",
      "neighborhoods",
      "agent-profiles",
    ],
    suggestedPages: ["Home", "Listings", "Neighborhoods", "About", "Contact"],
    contentTone: "trustworthy and aspirational",
    industryPattern: "property-real-estate",
  },
  automotive: {
    id: "automotive",
    label: "Automotive",
    description:
      "Dealership and auto brand experiences with inventory and service CTAs.",
    keywords: [
      "automotive",
      "car",
      "dealer",
      "dealership",
      "vehicle",
      "auto",
      "motors",
      "garage",
      "ev",
      "showroom",
    ],
    layoutStyle: "vehicle-showroom",
    sections: [
      "Hero models",
      "Inventory",
      "Finance offers",
      "Service & parts",
      "Test drive CTA",
      "Why us",
      "Reviews",
      "Contact",
    ],
    designPreset: "modern",
    requiredFeatures: [
      "inventory",
      "model-showcase",
      "finance-cta",
      "service-booking",
      "test-drive",
    ],
    suggestedPages: ["Home", "Inventory", "Services", "Finance", "Contact"],
    contentTone: "bold and performance-driven",
    industryPattern: "auto-mobility",
  },
  agency: {
    id: "agency",
    label: "Agency",
    description:
      "Creative and consulting agency sites with services, work, and lead capture.",
    keywords: [
      "agency",
      "studio",
      "creative",
      "marketing agency",
      "design agency",
      "consultancy",
      "portfolio",
      "clients",
      "campaign",
    ],
    layoutStyle: "studio-portfolio",
    sections: [
      "Hero",
      "Services",
      "Selected work",
      "Process",
      "Clients",
      "Capabilities",
      "Testimonials",
      "Contact",
    ],
    designPreset: "creative",
    requiredFeatures: [
      "portfolio",
      "services",
      "case-studies",
      "lead-form",
      "process",
    ],
    suggestedPages: ["Home", "Work", "Services", "About", "Contact"],
    contentTone: "sharp and creative",
    industryPattern: "creative-agency",
  },
  business: {
    id: "business",
    label: "Business",
    description:
      "General business and professional services with trust and conversion basics.",
    keywords: [
      "business",
      "company",
      "services",
      "consulting",
      "professional",
      "corporate",
      "office",
      "enterprise",
      "smb",
    ],
    layoutStyle: "corporate-trust",
    sections: [
      "Hero",
      "Services",
      "About",
      "Benefits",
      "Process",
      "Testimonials",
      "CTA",
      "Contact",
    ],
    designPreset: "corporate",
    requiredFeatures: [
      "services",
      "about",
      "testimonials",
      "contact-form",
      "trust-signals",
    ],
    suggestedPages: ["Home", "Services", "About", "Contact"],
    contentTone: "professional and clear",
    industryPattern: "professional-services",
  },
};

export const INDUSTRY_IDS = Object.keys(INDUSTRY_PROFILES) as IndustryId[];

export function getIndustryProfile(id: IndustryId): IndustryProfile {
  return INDUSTRY_PROFILES[id];
}

export function listIndustryProfiles(): IndustryProfile[] {
  return INDUSTRY_IDS.map((id) => INDUSTRY_PROFILES[id]);
}

export function isIndustryId(value: string): value is IndustryId {
  return value in INDUSTRY_PROFILES;
}
