import type {
  SmartTemplateDefinition,
  SmartTemplateId,
} from "@/lib/website/smart-templates/types";

/**
 * Professional Website Builder template library (Webflow/Wix/Framer-style).
 * Mirrors migration 034 seed; used as runtime source of truth + DB fallback.
 */
export const SMART_TEMPLATE_CATALOG: Record<
  SmartTemplateId,
  SmartTemplateDefinition
> = {
  "tourism-premium": {
    id: "tourism-premium",
    name: "Tourism Premium",
    slug: "tourism-premium",
    category: "Travel",
    description:
      "Travel premium experience with destinations, tours, packages, and booking CTAs.",
    industryId: "tourism",
    layoutStyle: "travel-premium",
    designPreset: "luxury",
    sections: [
      { key: "hero", label: "Hero destination", sortOrder: 10 },
      { key: "destinations", label: "Featured destinations", sortOrder: 20 },
      { key: "tours", label: "Popular tours", sortOrder: 30 },
      { key: "packages", label: "Travel packages", sortOrder: 40 },
      { key: "why", label: "Why travel with us", sortOrder: 50 },
      { key: "stories", label: "Traveler stories", sortOrder: 60 },
      { key: "booking", label: "Booking CTA", sortOrder: 70 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#0C2D48",
      secondary: "#D4A373",
      accent: "#E9C46A",
      background: "#F7F3EE",
      surface: "#FFFFFF",
      text: "#1B263B",
      muted: "#6D6875",
    },
    typography: {
      display: "Cormorant Garamond",
      body: "Nunito Sans",
      scale: "travel",
    },
    ctaStyle: {
      primaryLabel: "Book a trip",
      secondaryLabel: "Explore destinations",
      style: "solid-travel",
    },
    navigation: [
      "Destinations",
      "Tours",
      "Packages",
      "About",
      "Testimonials",
      "Booking",
      "Contact",
    ],
    footer: {
      columns: ["Explore", "Trips", "Company", "Support"],
      newsletter: true,
      trustBadges: ["Licensed operator", "Secure booking"],
    },
    requiredPages: [
      "Home",
      "Destinations",
      "Tours",
      "Packages",
      "About",
      "Testimonials",
      "Contact",
      "Booking",
    ],
    requiredFeatures: [
      "destinations",
      "tours",
      "packages",
      "booking-cta",
      "testimonials",
      "itinerary-inquiry",
    ],
    contentTone:
      "inspirational, wanderlust-driven, clear trip details and trust signals",
    keywords: [
      "tourism",
      "travel",
      "tour",
      "destination",
      "vacation",
      "holiday",
      "resort",
      "adventure",
    ],
    spacing: { sectionY: "5.5rem", container: "74rem", radius: "0.75rem" },
  },
  "automotive-luxury": {
    id: "automotive-luxury",
    name: "Automotive Luxury",
    slug: "automotive-luxury",
    category: "Automotive",
    description:
      "Premium dealership and auto brand experience with inventory and concierge CTAs.",
    industryId: "automotive",
    layoutStyle: "vehicle-showroom",
    designPreset: "luxury",
    sections: [
      { key: "hero", label: "Hero models", sortOrder: 10 },
      { key: "inventory", label: "Inventory", sortOrder: 20 },
      { key: "finance", label: "Finance offers", sortOrder: 30 },
      { key: "service", label: "Service & parts", sortOrder: 40 },
      { key: "test-drive", label: "Test drive CTA", sortOrder: 50 },
      { key: "why-us", label: "Why us", sortOrder: 60 },
      { key: "reviews", label: "Reviews", sortOrder: 70 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#0B0B0F",
      secondary: "#C6A75E",
      accent: "#E8E2D6",
      background: "#111114",
      surface: "#1A1A1F",
      text: "#F5F2EA",
      muted: "#9A958A",
    },
    typography: {
      display: "Playfair Display",
      body: "DM Sans",
      scale: "editorial",
    },
    ctaStyle: {
      primaryLabel: "Book a test drive",
      secondaryLabel: "View inventory",
      style: "solid-dark",
    },
    navigation: ["Models", "Inventory", "Services", "Finance", "Contact"],
    footer: {
      columns: ["Brand", "Inventory", "Services", "Legal"],
      newsletter: false,
      trustBadges: ["Certified", "Warranty"],
    },
    requiredPages: ["Home", "Inventory", "Services", "Finance", "About", "Contact"],
    requiredFeatures: [
      "inventory",
      "model-showcase",
      "finance-cta",
      "service-booking",
      "test-drive",
    ],
    contentTone: "bold, refined, performance-driven",
    keywords: [
      "automotive",
      "luxury",
      "car",
      "dealership",
      "showroom",
      "vehicle",
      "ev",
      "motors",
    ],
    spacing: { sectionY: "6rem", container: "72rem", radius: "0.5rem" },
  },
  "restaurant-premium": {
    id: "restaurant-premium",
    name: "Elegance",
    slug: "restaurant-premium",
    category: "Hospitality",
    description:
      "Fine-dining hospitality site with menu, reservations, and atmosphere.",
    industryId: "restaurant",
    layoutStyle: "editorial-hero",
    designPreset: "luxury",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "signature", label: "Signature dishes", sortOrder: 20 },
      { key: "menu", label: "Menu highlights", sortOrder: 30 },
      { key: "reservations", label: "Reservations", sortOrder: 40 },
      { key: "atmosphere", label: "Atmosphere", sortOrder: 50 },
      { key: "location", label: "Location", sortOrder: 60 },
      { key: "reviews", label: "Reviews", sortOrder: 70 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#1C1410",
      secondary: "#B08D57",
      accent: "#8B1E1E",
      background: "#FAF6F1",
      surface: "#FFFFFF",
      text: "#1C1410",
      muted: "#6E6258",
    },
    typography: {
      display: "Cormorant Garamond",
      body: "Source Sans 3",
      scale: "hospitality",
    },
    ctaStyle: {
      primaryLabel: "Reserve a table",
      secondaryLabel: "View menu",
      style: "outline-gold",
    },
    navigation: ["Menu", "Reservations", "About", "Private Dining", "Contact"],
    footer: {
      columns: ["Visit", "Menu", "Events", "Press"],
      newsletter: true,
      trustBadges: ["Reservations", "Private events"],
    },
    requiredPages: [
      "Home",
      "Menu",
      "Reservations",
      "About",
      "Private Dining",
      "Contact",
    ],
    requiredFeatures: ["menu", "reservations", "gallery", "location-map", "reviews"],
    contentTone: "warm, appetizing, elegant",
    keywords: [
      "restaurant",
      "dining",
      "chef",
      "menu",
      "bistro",
      "hospitality",
      "cafe",
      "food",
    ],
    spacing: { sectionY: "5.5rem", container: "70rem", radius: "0.375rem" },
  },
  "real-estate": {
    id: "real-estate",
    name: "Real Estate",
    slug: "real-estate",
    category: "Property",
    description:
      "Property marketing with listings, neighborhoods, and inquiry flows.",
    industryId: "real-estate",
    layoutStyle: "property-showcase",
    designPreset: "corporate",
    sections: [
      { key: "hero", label: "Hero search", sortOrder: 10 },
      { key: "listings", label: "Featured listings", sortOrder: 20 },
      { key: "neighborhoods", label: "Neighborhoods", sortOrder: 30 },
      { key: "process", label: "Buying process", sortOrder: 40 },
      { key: "agents", label: "Agent trust", sortOrder: 50 },
      { key: "testimonials", label: "Testimonials", sortOrder: 60 },
      { key: "inquiry", label: "Inquiry form", sortOrder: 70 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#0F2744",
      secondary: "#2F6FED",
      accent: "#D4A373",
      background: "#F7F9FC",
      surface: "#FFFFFF",
      text: "#142033",
      muted: "#5B677A",
    },
    typography: {
      display: "Libre Baskerville",
      body: "IBM Plex Sans",
      scale: "property",
    },
    ctaStyle: {
      primaryLabel: "Schedule a viewing",
      secondaryLabel: "Browse listings",
      style: "solid-brand",
    },
    navigation: ["Listings", "Neighborhoods", "Buy", "Sell", "Agents", "Contact"],
    footer: {
      columns: ["Explore", "Company", "Resources", "Legal"],
      newsletter: true,
      trustBadges: ["Licensed", "Local experts"],
    },
    requiredPages: [
      "Home",
      "Listings",
      "Neighborhoods",
      "Agents",
      "About",
      "Contact",
    ],
    requiredFeatures: [
      "listings",
      "property-search",
      "inquiry-form",
      "neighborhoods",
      "agent-profiles",
    ],
    contentTone: "trustworthy and aspirational",
    keywords: [
      "real estate",
      "property",
      "homes",
      "listings",
      "realtor",
      "apartment",
      "broker",
    ],
    spacing: { sectionY: "5rem", container: "74rem", radius: "0.5rem" },
  },
  "saas-startup": {
    id: "saas-startup",
    name: "SaaS Startup",
    slug: "saas-startup",
    category: "Software",
    description:
      "Product-led SaaS marketing with features, pricing, and onboarding CTAs.",
    industryId: "saas",
    layoutStyle: "product-saas",
    designPreset: "tech",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "problem", label: "Problem", sortOrder: 20 },
      { key: "solution", label: "Solution", sortOrder: 30 },
      { key: "features", label: "Features", sortOrder: 40 },
      { key: "how", label: "How it works", sortOrder: 50 },
      { key: "pricing", label: "Pricing", sortOrder: 60 },
      { key: "testimonials", label: "Testimonials", sortOrder: 70 },
      { key: "cta", label: "CTA", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#111827",
      secondary: "#4F46E5",
      accent: "#22D3EE",
      background: "#FAFAFB",
      surface: "#FFFFFF",
      text: "#111827",
      muted: "#6B7280",
    },
    typography: {
      display: "Sora",
      body: "Inter",
      scale: "product",
    },
    ctaStyle: {
      primaryLabel: "Start free trial",
      secondaryLabel: "Book a demo",
      style: "gradient",
    },
    navigation: ["Product", "Features", "Pricing", "Customers", "Docs", "Login"],
    footer: {
      columns: ["Product", "Company", "Resources", "Legal"],
      newsletter: true,
      trustBadges: ["SOC2", "GDPR"],
    },
    requiredPages: ["Home", "Features", "Pricing", "Customers", "Docs", "Contact"],
    requiredFeatures: [
      "pricing",
      "feature-grid",
      "integrations",
      "auth-cta",
      "demo-request",
    ],
    contentTone: "confident and product-led",
    keywords: [
      "saas",
      "software",
      "startup",
      "platform",
      "subscription",
      "b2b",
      "product",
      "cloud",
    ],
    spacing: { sectionY: "5rem", container: "72rem", radius: "0.75rem" },
  },
  agency: {
    id: "agency",
    name: "Agency",
    slug: "agency",
    category: "Creative",
    description:
      "Creative and consulting agency with services, work, and lead capture.",
    industryId: "agency",
    layoutStyle: "studio-portfolio",
    designPreset: "creative",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "services", label: "Services", sortOrder: 20 },
      { key: "work", label: "Selected work", sortOrder: 30 },
      { key: "process", label: "Process", sortOrder: 40 },
      { key: "clients", label: "Clients", sortOrder: 50 },
      { key: "capabilities", label: "Capabilities", sortOrder: 60 },
      { key: "testimonials", label: "Testimonials", sortOrder: 70 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#0A0A0A",
      secondary: "#FF4D6D",
      accent: "#F4F1EA",
      background: "#FFFFFF",
      surface: "#F7F7F5",
      text: "#0A0A0A",
      muted: "#6B6B6B",
    },
    typography: {
      display: "Space Grotesk",
      body: "Manrope",
      scale: "studio",
    },
    ctaStyle: {
      primaryLabel: "Start a project",
      secondaryLabel: "View work",
      style: "solid-accent",
    },
    navigation: ["Work", "Services", "About", "Process", "Contact"],
    footer: {
      columns: ["Studio", "Work", "Services", "Contact"],
      newsletter: false,
      trustBadges: ["Featured work"],
    },
    requiredPages: ["Home", "Work", "Services", "About", "Process", "Contact"],
    requiredFeatures: [
      "portfolio",
      "services",
      "case-studies",
      "lead-form",
      "process",
    ],
    contentTone: "sharp and creative",
    keywords: [
      "agency",
      "studio",
      "creative",
      "portfolio",
      "marketing agency",
      "design",
      "consultancy",
    ],
    spacing: { sectionY: "6rem", container: "76rem", radius: "0.25rem" },
  },
  clinic: {
    id: "clinic",
    name: "Medical Center",
    slug: "clinic",
    category: "Medical",
    description:
      "Medical and healthcare sites with departments, doctors, appointments, and emergency CTAs.",
    industryId: "clinic",
    layoutStyle: "corporate-trust",
    designPreset: "minimal",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "about", label: "About", sortOrder: 15 },
      { key: "services", label: "Care services", sortOrder: 20 },
      { key: "departments", label: "Departments", sortOrder: 25 },
      { key: "doctors", label: "Doctors", sortOrder: 30 },
      { key: "appointments", label: "Appointments", sortOrder: 40 },
      { key: "emergency", label: "Emergency", sortOrder: 45 },
      { key: "insurance", label: "Insurance", sortOrder: 50 },
      { key: "testimonials", label: "Testimonials", sortOrder: 55 },
      { key: "faq", label: "FAQ", sortOrder: 60 },
      { key: "location", label: "Location", sortOrder: 70 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#0E3B3A",
      secondary: "#2A9D8F",
      accent: "#E9C46A",
      background: "#F8FBFA",
      surface: "#FFFFFF",
      text: "#12302F",
      muted: "#5C7371",
    },
    typography: {
      display: "Fraunces",
      body: "Nunito Sans",
      scale: "care",
    },
    ctaStyle: {
      primaryLabel: "Book appointment",
      secondaryLabel: "Our services",
      style: "solid-calm",
    },
    navigation: ["Services", "Doctors", "Departments", "Emergency", "About", "Contact"],
    footer: {
      columns: ["Care", "Patients", "About", "Legal"],
      newsletter: false,
      trustBadges: ["Licensed clinicians", "HIPAA-aware"],
    },
    requiredPages: ["Home", "Services", "Doctors", "Patients", "About", "Contact"],
    requiredFeatures: [
      "services",
      "appointments",
      "doctor-profiles",
      "insurance",
      "contact-form",
    ],
    contentTone: "calm, caring, trustworthy",
    keywords: [
      "clinic",
      "medical",
      "doctor",
      "healthcare",
      "dental",
      "wellness",
      "hospital",
      "patient",
    ],
    spacing: { sectionY: "5rem", container: "70rem", radius: "0.75rem" },
  },
  "education-campus": {
    id: "education-campus",
    name: "Education Campus",
    slug: "education-campus",
    category: "Education",
    description:
      "Modern education site with programs, faculty, admissions, and enrollment CTAs.",
    industryId: "education",
    layoutStyle: "campus-education",
    designPreset: "modern",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "programs", label: "Programs", sortOrder: 20 },
      { key: "courses", label: "Courses", sortOrder: 25 },
      { key: "teachers", label: "Teachers", sortOrder: 30 },
      { key: "admissions", label: "Admissions", sortOrder: 40 },
      { key: "events", label: "Events", sortOrder: 45 },
      { key: "certificates", label: "Certificates", sortOrder: 50 },
      { key: "testimonials", label: "Testimonials", sortOrder: 55 },
      { key: "faq", label: "FAQ", sortOrder: 60 },
      { key: "news", label: "News", sortOrder: 65 },
      { key: "contact", label: "Contact", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#1D3557",
      secondary: "#457B9D",
      accent: "#E63946",
      background: "#F1FAEE",
      surface: "#FFFFFF",
      text: "#1D3557",
      muted: "#6C757D",
    },
    typography: {
      display: "Source Serif 4",
      body: "Source Sans 3",
      scale: "campus",
    },
    ctaStyle: {
      primaryLabel: "Apply now",
      secondaryLabel: "Explore programs",
      style: "solid-campus",
    },
    navigation: [
      "Programs",
      "Courses",
      "Teachers",
      "Admissions",
      "Events",
      "Certificates",
      "News",
      "Contact",
    ],
    footer: {
      columns: ["Learn", "Admissions", "Campus", "Legal"],
      newsletter: true,
      trustBadges: ["Accredited programs", "Career outcomes"],
    },
    requiredPages: [
      "Home",
      "Programs",
      "Courses",
      "Admissions",
      "Faculty",
      "Campus life",
      "About",
      "Contact",
    ],
    requiredFeatures: [
      "programs",
      "courses",
      "admissions",
      "faculty",
      "enrollment-cta",
    ],
    contentTone:
      "inspiring, clear outcomes, credibility-led academic tone",
    keywords: [
      "education",
      "school",
      "university",
      "course",
      "learning",
      "academy",
      "training",
      "campus",
    ],
    spacing: { sectionY: "5rem", container: "72rem", radius: "0.65rem" },
  },
  "law-firm": {
    id: "law-firm",
    name: "Law Firm",
    slug: "law-firm",
    category: "Legal",
    description:
      "Professional law firm with practice areas, attorneys, cases, and consultation CTAs.",
    industryId: "law",
    layoutStyle: "legal-trust",
    designPreset: "luxury",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "practice", label: "Practice areas", sortOrder: 20 },
      { key: "lawyers", label: "Lawyers", sortOrder: 30 },
      { key: "cases", label: "Cases", sortOrder: 40 },
      { key: "consultation", label: "Consultation", sortOrder: 50 },
      { key: "testimonials", label: "Testimonials", sortOrder: 60 },
      { key: "faq", label: "FAQ", sortOrder: 70 },
      { key: "office", label: "Office", sortOrder: 80 },
      { key: "contact", label: "Contact", sortOrder: 90 },
    ],
    colorPalette: {
      primary: "#0F172A",
      secondary: "#1E293B",
      accent: "#C9A227",
      background: "#020617",
      surface: "#0F172A",
      text: "#F8FAFC",
      muted: "#94A3B8",
    },
    typography: {
      display: "Cormorant Garamond",
      body: "Source Sans 3",
      scale: "legal",
    },
    ctaStyle: {
      primaryLabel: "Book consultation",
      secondaryLabel: "Practice areas",
      style: "solid-luxury",
    },
    navigation: ["Practice Areas", "Attorneys", "Cases", "About", "Contact"],
    footer: {
      columns: ["Practice", "Attorneys", "Resources", "Legal"],
      newsletter: false,
      trustBadges: ["Licensed attorneys", "Confidential consult"],
    },
    requiredPages: ["Home", "Practice Areas", "Attorneys", "Cases", "Contact"],
    requiredFeatures: [
      "practice-areas",
      "attorney-profiles",
      "case-studies",
      "consultation-booking",
      "contact-form",
    ],
    contentTone: "authoritative, precise, reassuring",
    keywords: ["law", "lawyer", "attorney", "legal", "law firm", "litigation"],
    spacing: { sectionY: "6rem", container: "76rem", radius: "0.5rem" },
  },
  "blog-editorial": {
    id: "blog-editorial",
    name: "Blog Editorial",
    slug: "blog-editorial",
    category: "Blog",
    description:
      "Editorial blog with featured articles, categories, authors, and newsletter CTAs.",
    industryId: "blog",
    layoutStyle: "editorial-blog",
    designPreset: "creative",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "featured", label: "Featured articles", sortOrder: 20 },
      { key: "categories", label: "Categories", sortOrder: 30 },
      { key: "popular", label: "Popular posts", sortOrder: 40 },
      { key: "latest", label: "Latest posts", sortOrder: 50 },
      { key: "author", label: "Author", sortOrder: 55 },
      { key: "newsletter", label: "Newsletter", sortOrder: 60 },
      { key: "cta", label: "CTA", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#18181B",
      secondary: "#52525B",
      accent: "#E11D48",
      background: "#FAFAFA",
      surface: "#FFFFFF",
      text: "#18181B",
      muted: "#71717A",
    },
    typography: {
      display: "Fraunces",
      body: "Inter",
      scale: "editorial",
    },
    ctaStyle: {
      primaryLabel: "Subscribe",
      secondaryLabel: "Read latest",
      style: "outline-editorial",
    },
    navigation: ["Articles", "Categories", "Authors", "About", "Newsletter"],
    footer: {
      columns: ["Topics", "Authors", "Archive", "Legal"],
      newsletter: true,
      trustBadges: ["Editorial quality", "Weekly digest"],
    },
    requiredPages: ["Home", "Articles", "Categories", "About", "Contact"],
    requiredFeatures: ["blog", "categories", "newsletter", "author-profiles"],
    contentTone: "editorial, engaging, readable",
    keywords: ["blog", "article", "news", "magazine", "editorial", "writer"],
    spacing: { sectionY: "4.5rem", container: "68rem", radius: "0.35rem" },
  },
  "landing-conversion": {
    id: "landing-conversion",
    name: "Landing Conversion",
    slug: "landing-conversion",
    category: "Landing Page",
    description:
      "Single-page conversion layout for startups, SaaS, and marketing campaigns.",
    industryId: "landing-page",
    layoutStyle: "conversion-landing",
    designPreset: "modern",
    sections: [
      { key: "hero", label: "Hero", sortOrder: 10 },
      { key: "benefits", label: "Benefits", sortOrder: 20 },
      { key: "features", label: "Features", sortOrder: 30 },
      { key: "stats", label: "Statistics", sortOrder: 40 },
      { key: "testimonials", label: "Testimonials", sortOrder: 50 },
      { key: "pricing", label: "Pricing", sortOrder: 60 },
      { key: "faq", label: "FAQ", sortOrder: 70 },
      { key: "cta", label: "Sticky CTA", sortOrder: 80 },
      { key: "contact", label: "Contact", sortOrder: 90 },
    ],
    colorPalette: {
      primary: "#2563EB",
      secondary: "#0F172A",
      accent: "#22D3EE",
      background: "#FFFFFF",
      surface: "#F8FAFC",
      text: "#0F172A",
      muted: "#64748B",
    },
    typography: {
      display: "Space Grotesk",
      body: "Inter",
      scale: "product",
    },
    ctaStyle: {
      primaryLabel: "Get started",
      secondaryLabel: "Book a demo",
      style: "solid-conversion",
    },
    navigation: ["Benefits", "Features", "Pricing", "FAQ", "Contact"],
    footer: {
      columns: ["Product", "Company", "Legal"],
      newsletter: false,
      trustBadges: ["No credit card", "Cancel anytime"],
    },
    requiredPages: ["Home"],
    requiredFeatures: [
      "hero-cta",
      "benefits",
      "features",
      "pricing",
      "sticky-cta",
      "lead-form",
    ],
    contentTone: "direct, benefit-led, conversion-focused",
    keywords: ["landing page", "startup", "saas", "launch", "marketing", "lead gen"],
    spacing: { sectionY: "5rem", container: "72rem", radius: "1rem" },
  },
  "ecommerce-store": {
    id: "ecommerce-store",
    name: "E-commerce Store",
    slug: "ecommerce-store",
    category: "Retail",
    description:
      "Conversion-focused storefront with catalog, collections, and trust badges.",
    industryId: "ecommerce",
    layoutStyle: "commerce-grid",
    designPreset: "modern",
    sections: [
      { key: "hero", label: "Hero offer", sortOrder: 10 },
      { key: "featured", label: "Featured products", sortOrder: 20 },
      { key: "collections", label: "Collections", sortOrder: 30 },
      { key: "benefits", label: "Benefits", sortOrder: 40 },
      { key: "social", label: "Social proof", sortOrder: 50 },
      { key: "shipping", label: "Shipping & returns", sortOrder: 60 },
      { key: "faq", label: "FAQ", sortOrder: 70 },
      { key: "cta", label: "CTA", sortOrder: 80 },
    ],
    colorPalette: {
      primary: "#111111",
      secondary: "#E11D48",
      accent: "#F59E0B",
      background: "#FFFFFF",
      surface: "#F4F4F5",
      text: "#18181B",
      muted: "#71717A",
    },
    typography: {
      display: "Outfit",
      body: "Inter",
      scale: "commerce",
    },
    ctaStyle: {
      primaryLabel: "Shop now",
      secondaryLabel: "View collections",
      style: "solid-conversion",
    },
    navigation: ["Shop", "Collections", "About", "Support", "Cart"],
    footer: {
      columns: ["Shop", "Help", "Company", "Legal"],
      newsletter: true,
      trustBadges: ["Free shipping", "Secure checkout"],
    },
    requiredPages: ["Home", "Shop", "Collections", "About", "FAQ", "Contact"],
    requiredFeatures: [
      "product-catalog",
      "featured-products",
      "cart-cta",
      "trust-badges",
      "faq",
    ],
    contentTone: "clear and conversion-focused",
    keywords: [
      "ecommerce",
      "shop",
      "store",
      "retail",
      "product",
      "cart",
      "checkout",
      "marketplace",
    ],
    spacing: { sectionY: "4.5rem", container: "72rem", radius: "0.5rem" },
  },
};

export const SMART_TEMPLATE_IDS = Object.keys(
  SMART_TEMPLATE_CATALOG,
) as SmartTemplateId[];

export function isSmartTemplateId(value: string): value is SmartTemplateId {
  return value in SMART_TEMPLATE_CATALOG;
}

export function getSmartTemplate(id: SmartTemplateId): SmartTemplateDefinition {
  return SMART_TEMPLATE_CATALOG[id];
}

export function listSmartTemplates(): SmartTemplateDefinition[] {
  return SMART_TEMPLATE_IDS.map((id) => SMART_TEMPLATE_CATALOG[id]);
}
