import { DESIGN_RENDERER_COMPONENTS } from "@/lib/ai-core/design-renderer/components";
import type { DesignRendererComponentId } from "@/lib/ai-core/design-renderer/types";
import type { ProfessionalComponentDefinition } from "@/lib/ai-core/components/types";

function def(
  id: DesignRendererComponentId,
  partial: Omit<
    ProfessionalComponentDefinition,
    | "id"
    | "exportName"
    | "path"
    | "pattern"
    | "description"
    | "defaultGoal"
    | "websiteGoals"
  > &
    Partial<
      Pick<
        ProfessionalComponentDefinition,
        "pattern" | "description" | "defaultGoal" | "websiteGoals"
      >
    >,
): ProfessionalComponentDefinition {
  const base = DESIGN_RENDERER_COMPONENTS[id];
  return {
    id,
    exportName: base.exportName,
    path: base.path,
    pattern: partial.pattern ?? base.pattern,
    description: partial.description ?? base.description,
    defaultGoal: partial.defaultGoal ?? base.defaultGoal,
    kind: partial.kind,
    variant: partial.variant,
    industries: partial.industries,
    designStyles: partial.designStyles,
    audiences: partial.audiences,
    websiteGoals: partial.websiteGoals ?? ["*"],
    tags: partial.tags,
    assetRole: partial.assetRole,
    sectionKeywords: partial.sectionKeywords,
  };
}

/**
 * Professional Components Library catalog.
 * Selection intelligence scores these against industry / audience / design style.
 */
export const PROFESSIONAL_COMPONENT_CATALOG: ProfessionalComponentDefinition[] =
  [
    // —— Heroes ——
    def("HeroLuxury", {
      kind: "hero",
      variant: "luxury",
      industries: ["tourism", "automotive", "real-estate", "restaurant", "agency", "*"],
      designStyles: ["luxury", "editorial", "premium", "travel premium"],
      audiences: ["affluent", "luxury", "premium", "executive", "discerning"],
      tags: ["hero", "luxury", "cinematic"],
      assetRole: "hero",
      sectionKeywords: ["hero", "luxury"],
    }),
    def("HeroLuxuryShowcase", {
      kind: "hero",
      variant: "luxury",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "dark"],
      audiences: ["luxury", "enthusiast", "premium"],
      tags: ["hero", "vehicle"],
      assetRole: "hero",
      sectionKeywords: ["hero", "showcase"],
    }),
    def("HeroVideo", {
      kind: "hero",
      variant: "video",
      industries: ["tourism", "agency", "restaurant", "education", "*"],
      designStyles: ["cinematic", "creative", "modern", "travel premium"],
      audiences: ["young", "creative", "experience", "traveler"],
      tags: ["hero", "video", "immersive"],
      assetRole: "hero",
      sectionKeywords: ["hero", "video"],
    }),
    def("HeroSplit", {
      kind: "hero",
      variant: "split",
      industries: ["saas", "clinic", "education", "agency", "ecommerce", "*"],
      designStyles: ["corporate", "modern", "minimal", "trust"],
      audiences: ["business", "b2b", "professional", "enterprise", "parents"],
      tags: ["hero", "split", "corporate"],
      assetRole: "hero",
      sectionKeywords: ["hero", "split"],
    }),
    def("HeroImage", {
      kind: "hero",
      variant: "image",
      industries: ["*", "tourism", "restaurant", "real-estate", "ecommerce"],
      designStyles: ["modern", "cinematic", "premium commercial", "image"],
      audiences: ["consumer", "shopper", "traveler", "general"],
      tags: ["hero", "image"],
      assetRole: "hero",
      sectionKeywords: ["hero", "image"],
    }),
    def("HeroProduct", {
      kind: "hero",
      variant: "product",
      industries: ["saas", "ecommerce", "*"],
      designStyles: ["modern", "tech", "product", "futuristic"],
      audiences: ["startup", "builder", "developer", "saas", "shopper"],
      tags: ["hero", "product"],
      assetRole: "product",
      sectionKeywords: ["hero", "product"],
    }),
    def("HeroFullBleed", {
      kind: "hero",
      variant: "image",
      industries: ["tourism", "restaurant", "agency", "*"],
      designStyles: ["cinematic", "travel", "modern"],
      audiences: ["traveler", "experience", "general"],
      tags: ["hero", "full-bleed"],
      assetRole: "hero",
      sectionKeywords: ["hero"],
    }),
    def("HeroCinematic", {
      kind: "hero",
      variant: "cinematic",
      industries: ["tourism", "agency", "automotive", "restaurant", "business", "*"],
      designStyles: ["cinematic", "luxury", "premium-brand", "creative", "editorial"],
      audiences: ["affluent", "luxury", "creative", "executive", "premium"],
      websiteGoals: ["brand", "booking", "lead-gen"],
      tags: ["hero", "cinematic", "film"],
      assetRole: "hero",
      sectionKeywords: ["hero", "cinematic", "film"],
    }),
    def("HeroFullImage", {
      kind: "hero",
      variant: "full-image",
      industries: ["restaurant", "tourism", "ecommerce", "real-estate", "*"],
      designStyles: ["luxury", "editorial", "image", "cinematic"],
      audiences: ["consumer", "traveler", "shopper", "luxury"],
      websiteGoals: ["brand", "booking", "ecommerce"],
      tags: ["hero", "full-image"],
      assetRole: "hero",
      sectionKeywords: ["hero", "image", "full"],
    }),
    def("HeroInteractive", {
      kind: "hero",
      variant: "interactive",
      industries: ["saas", "ecommerce", "automotive", "business", "*"],
      designStyles: ["saas", "technology", "modern", "tech", "product"],
      audiences: ["startup", "builder", "developer", "saas", "product"],
      websiteGoals: ["conversion", "ecommerce", "lead-gen"],
      tags: ["hero", "interactive", "product"],
      assetRole: "product",
      sectionKeywords: ["hero", "interactive", "product"],
    }),
    def("HeroProperty", {
      kind: "hero",
      variant: "image",
      industries: ["real-estate"],
      designStyles: ["luxury", "corporate", "modern"],
      audiences: ["buyer", "investor", "homeowner"],
      tags: ["hero", "property"],
      assetRole: "hero",
      sectionKeywords: ["hero", "property", "listing"],
    }),

    // —— Sections ——
    def("ServicesGrid", {
      kind: "services",
      industries: ["*", "agency", "clinic", "automotive", "education"],
      designStyles: ["corporate", "modern", "trust", "minimal"],
      audiences: ["business", "patient", "client", "professional"],
      tags: ["services"],
      assetRole: "service",
      sectionKeywords: ["service", "offer", "what we"],
    }),
    def("CareServices", {
      kind: "services",
      industries: ["clinic"],
      designStyles: ["trust", "calm", "corporate", "minimal"],
      audiences: ["patient", "family", "healthcare"],
      tags: ["services", "care"],
      assetRole: "service",
      sectionKeywords: ["care", "service", "treatment"],
    }),
    def("FeatureHighlights", {
      kind: "features",
      industries: ["*", "saas", "real-estate", "education"],
      designStyles: ["modern", "corporate", "minimal"],
      audiences: ["business", "buyer", "professional"],
      tags: ["features"],
      assetRole: "section",
      sectionKeywords: ["feature", "why", "benefit", "highlight"],
    }),
    def("FeaturesBento", {
      kind: "features",
      industries: ["saas", "ecommerce", "agency"],
      designStyles: ["modern", "tech", "creative", "futuristic"],
      audiences: ["startup", "builder", "tech", "creative"],
      tags: ["features", "bento"],
      assetRole: "section",
      sectionKeywords: ["feature", "capability", "benefit"],
    }),
    def("ProductShowcase", {
      kind: "product-showcase",
      industries: ["*", "ecommerce", "saas", "automotive"],
      designStyles: ["modern", "premium", "product", "luxury"],
      audiences: ["shopper", "buyer", "enthusiast"],
      tags: ["product", "showcase"],
      assetRole: "product",
      sectionKeywords: ["product", "showcase", "flagship", "offer"],
    }),
    def("VehicleShowcase", {
      kind: "product-showcase",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "modern"],
      audiences: ["enthusiast", "buyer", "luxury"],
      tags: ["vehicle", "showcase", "cards"],
      assetRole: "product",
      sectionKeywords: ["vehicle", "model", "inventory", "showcase", "car"],
    }),
    def("VehicleDetail", {
      kind: "product-showcase",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "modern"],
      audiences: ["enthusiast", "buyer", "luxury"],
      tags: ["vehicle", "detail"],
      assetRole: "product",
      sectionKeywords: ["vehicle", "detail", "specs", "model", "trim"],
    }),
    def("InventoryGrid", {
      kind: "product-showcase",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "modern", "commercial"],
      audiences: ["buyer", "enthusiast"],
      tags: ["inventory", "filter", "stock"],
      assetRole: "product",
      sectionKeywords: ["inventory", "stock", "filter", "browse", "available"],
    }),
    def("FinanceCalculator", {
      kind: "pricing",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "modern", "corporate"],
      audiences: ["buyer", "enthusiast"],
      websiteGoals: ["lead-gen", "conversion"],
      tags: ["finance", "calculator", "payment"],
      sectionKeywords: ["finance", "payment", "loan", "lease", "apr"],
    }),
    def("AppointmentCalendar", {
      kind: "booking",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "modern"],
      audiences: ["buyer", "enthusiast"],
      websiteGoals: ["lead-gen", "booking", "conversion"],
      tags: ["appointment", "calendar", "test-drive"],
      sectionKeywords: ["appointment", "calendar", "test drive", "booking", "schedule"],
    }),
    def("VehicleComparison", {
      kind: "comparison",
      industries: ["automotive"],
      designStyles: ["luxury", "premium", "modern"],
      audiences: ["buyer", "enthusiast"],
      tags: ["compare", "table", "specs"],
      sectionKeywords: ["compare", "comparison", "specs", "models"],
    }),
    def("TestimonialsSlider", {
      kind: "testimonials",
      industries: ["automotive", "*", "saas", "agency"],
      designStyles: ["luxury", "premium", "modern", "*"],
      audiences: ["*", "buyer", "business"],
      tags: ["testimonials", "slider", "proof"],
      assetRole: "section",
      sectionKeywords: ["testimonial", "review", "slider", "owner", "story"],
    }),
    def("ProductGrid", {
      kind: "product-showcase",
      industries: ["ecommerce"],
      designStyles: ["modern", "minimal", "commercial"],
      audiences: ["shopper", "consumer"],
      tags: ["product", "grid"],
      assetRole: "product",
      sectionKeywords: ["product", "shop", "catalog"],
    }),
    def("GalleryGrid", {
      kind: "gallery",
      industries: ["*", "agency", "restaurant", "tourism", "real-estate"],
      designStyles: ["creative", "luxury", "cinematic", "modern"],
      audiences: ["creative", "traveler", "diner", "buyer"],
      tags: ["gallery"],
      assetRole: "section",
      sectionKeywords: ["gallery", "photo", "portfolio", "visual"],
    }),
    def("DestinationsGallery", {
      kind: "gallery",
      industries: ["tourism"],
      designStyles: ["travel premium", "cinematic", "luxury"],
      audiences: ["traveler", "tourist"],
      tags: ["gallery", "destination"],
      assetRole: "section",
      sectionKeywords: ["destination", "gallery", "tour"],
    }),
    def("PortfolioGrid", {
      kind: "gallery",
      industries: ["agency"],
      designStyles: ["creative", "modern", "minimal"],
      audiences: ["client", "creative", "brand"],
      tags: ["portfolio"],
      assetRole: "section",
      sectionKeywords: ["portfolio", "work", "case", "project"],
    }),
    def("TestimonialsCarousel", {
      kind: "testimonials",
      industries: ["*"],
      designStyles: ["*", "corporate", "modern", "trust"],
      audiences: ["*", "business", "consumer"],
      tags: ["testimonials", "proof"],
      sectionKeywords: ["testimonial", "review", "story", "client"],
    }),
    def("SocialProof", {
      kind: "testimonials",
      industries: ["saas", "agency", "ecommerce"],
      designStyles: ["modern", "tech", "corporate"],
      audiences: ["b2b", "startup", "enterprise"],
      tags: ["proof", "logos"],
      sectionKeywords: ["proof", "trusted", "logo", "metric"],
    }),
    def("PricingTable", {
      kind: "pricing",
      industries: ["saas", "agency", "education", "clinic", "*"],
      designStyles: ["modern", "corporate", "minimal", "tech"],
      audiences: ["buyer", "business", "parent", "patient"],
      websiteGoals: ["conversion", "ecommerce", "lead-gen"],
      tags: ["pricing"],
      sectionKeywords: ["pricing", "plan", "package", "tier"],
    }),
    def("PricingModern", {
      kind: "pricing",
      industries: ["saas", "agency", "ecommerce", "*"],
      designStyles: ["modern", "tech", "premium", "minimal"],
      audiences: ["buyer", "startup", "business"],
      websiteGoals: ["conversion", "ecommerce"],
      tags: ["pricing", "modern"],
      sectionKeywords: ["pricing", "plan", "tier", "subscribe"],
    }),
    def("FaqAccordion", {
      kind: "faq",
      industries: ["*"],
      designStyles: ["*", "corporate", "minimal", "modern"],
      audiences: ["*"],
      tags: ["faq"],
      sectionKeywords: ["faq", "question", "help"],
    }),
    def("BookingForm", {
      kind: "booking",
      industries: ["*", "clinic", "education", "agency"],
      designStyles: ["corporate", "modern", "trust"],
      audiences: ["patient", "client", "parent"],
      websiteGoals: ["booking", "lead-gen"],
      tags: ["booking", "form"],
      sectionKeywords: ["booking", "appointment", "schedule", "book"],
    }),
    def("BookingSection", {
      kind: "booking",
      industries: ["tourism"],
      designStyles: ["travel premium", "luxury", "cinematic"],
      audiences: ["traveler"],
      websiteGoals: ["booking"],
      tags: ["booking"],
      sectionKeywords: ["booking", "trip", "reserve"],
    }),
    def("ReservationSection", {
      kind: "booking",
      industries: ["restaurant"],
      designStyles: ["luxury", "modern", "editorial"],
      audiences: ["diner", "guest"],
      websiteGoals: ["booking"],
      tags: ["reservation"],
      sectionKeywords: ["reservation", "table", "book"],
    }),
    def("ContactSection", {
      kind: "contact",
      industries: ["*"],
      designStyles: ["*", "corporate", "modern", "trust"],
      audiences: ["*"],
      websiteGoals: ["lead-gen", "brand", "content", "*"],
      tags: ["contact"],
      sectionKeywords: ["contact", "inquiry", "get in touch", "reach"],
    }),
    def("ContactCta", {
      kind: "contact",
      industries: ["*", "real-estate", "agency"],
      designStyles: ["modern", "corporate"],
      audiences: ["buyer", "client"],
      websiteGoals: ["lead-gen", "conversion"],
      tags: ["contact", "cta"],
      sectionKeywords: ["contact", "cta", "inquiry"],
    }),
    def("MapsSection", {
      kind: "maps",
      industries: ["*", "restaurant", "clinic", "automotive", "education"],
      designStyles: ["corporate", "modern", "trust"],
      audiences: ["local", "patient", "diner", "visitor"],
      tags: ["maps", "location"],
      sectionKeywords: ["map", "location", "branch", "find us", "address"],
    }),
    def("BranchesMap", {
      kind: "maps",
      industries: ["automotive", "clinic"],
      designStyles: ["corporate", "trust"],
      audiences: ["local", "buyer"],
      tags: ["branches"],
      sectionKeywords: ["branch", "location", "dealer"],
    }),
    def("TeamSection", {
      kind: "team",
      industries: ["*", "agency", "clinic", "education"],
      designStyles: ["corporate", "modern", "trust", "creative"],
      audiences: ["client", "patient", "parent", "professional"],
      tags: ["team"],
      sectionKeywords: ["team", "doctor", "staff", "expert", "people"],
    }),
    def("DoctorProfiles", {
      kind: "team",
      industries: ["clinic"],
      designStyles: ["trust", "corporate", "calm"],
      audiences: ["patient", "family"],
      tags: ["team", "doctors"],
      sectionKeywords: ["doctor", "clinician", "specialist", "team"],
    }),
    def("BlogSection", {
      kind: "blog",
      industries: ["*", "saas", "agency", "education", "clinic"],
      designStyles: ["modern", "corporate", "minimal", "creative"],
      audiences: ["professional", "learner", "client"],
      tags: ["blog", "insights"],
      sectionKeywords: ["blog", "insight", "article", "news", "resource"],
    }),
    def("CtaBand", {
      kind: "cta",
      industries: ["*"],
      designStyles: ["*"],
      audiences: ["*"],
      websiteGoals: ["conversion", "lead-gen", "ecommerce", "*"],
      tags: ["cta"],
      sectionKeywords: ["cta", "get started", "start"],
    }),
    def("CtaSplit", {
      kind: "cta",
      industries: ["*", "saas", "agency", "ecommerce"],
      designStyles: ["modern", "corporate", "tech"],
      audiences: ["business", "startup", "buyer"],
      websiteGoals: ["conversion", "lead-gen"],
      tags: ["cta", "split"],
      sectionKeywords: ["cta", "get started", "demo", "trial"],
    }),
    def("FeaturesModern", {
      kind: "features",
      industries: ["*", "saas", "agency", "ecommerce"],
      designStyles: ["modern", "tech", "minimal", "corporate"],
      audiences: ["business", "startup", "professional"],
      websiteGoals: ["conversion", "brand", "content", "*"],
      tags: ["features", "modern"],
      assetRole: "section",
      sectionKeywords: ["feature", "benefit", "capability"],
    }),
    def("ServicesModern", {
      kind: "services",
      industries: ["*", "agency", "clinic", "education"],
      designStyles: ["modern", "corporate", "trust", "premium"],
      audiences: ["client", "patient", "professional"],
      websiteGoals: ["lead-gen", "booking", "brand", "*"],
      tags: ["services", "modern"],
      assetRole: "service",
      sectionKeywords: ["service", "offer", "solution"],
    }),
    def("TestimonialsModern", {
      kind: "testimonials",
      industries: ["*"],
      designStyles: ["modern", "corporate", "trust", "premium"],
      audiences: ["*"],
      websiteGoals: ["lead-gen", "conversion", "brand", "*"],
      tags: ["testimonials", "modern"],
      sectionKeywords: ["testimonial", "review", "proof"],
    }),
    def("PortfolioGallery", {
      kind: "gallery",
      industries: ["agency", "tourism", "restaurant", "real-estate", "*"],
      designStyles: ["creative", "luxury", "cinematic", "modern"],
      audiences: ["creative", "client", "traveler", "buyer"],
      websiteGoals: ["brand", "lead-gen", "ecommerce"],
      tags: ["portfolio", "gallery"],
      assetRole: "section",
      sectionKeywords: ["portfolio", "gallery", "work", "showcase"],
    }),
    def("FeatureStorytelling", {
      kind: "feature-story",
      industries: ["*", "agency", "saas", "education", "tourism", "business"],
      designStyles: ["editorial", "story", "premium-brand", "luxury", "creative"],
      audiences: ["executive", "creative", "premium", "business"],
      websiteGoals: ["brand", "lead-gen", "conversion", "content"],
      tags: ["storytelling", "features", "editorial"],
      assetRole: "section",
      sectionKeywords: ["feature storytelling", "story", "chapter", "narrative"],
    }),
    def("ProductInteractive", {
      kind: "interactive-product",
      industries: ["saas", "ecommerce", "automotive", "real-estate", "business", "*"],
      designStyles: ["product", "saas", "technology", "modern", "luxury"],
      audiences: ["startup", "builder", "shopper", "enthusiast"],
      websiteGoals: ["conversion", "ecommerce", "lead-gen"],
      tags: ["interactive", "product", "showcase"],
      assetRole: "product",
      sectionKeywords: ["interactive product", "showcase", "product stage"],
    }),
    def("CaseStudies", {
      kind: "case-studies",
      industries: ["agency", "saas", "business", "*"],
      designStyles: ["editorial", "corporate", "premium-brand", "creative"],
      audiences: ["b2b", "enterprise", "client", "executive"],
      websiteGoals: ["lead-gen", "brand", "conversion"],
      tags: ["case-studies", "proof", "editorial"],
      assetRole: "section",
      sectionKeywords: ["case study", "case studies", "engagement", "results"],
    }),
    def("BrandTrust", {
      kind: "brand-trust",
      industries: ["*"],
      designStyles: ["*", "corporate", "premium-brand", "luxury", "minimal"],
      audiences: ["*", "enterprise", "professional", "premium"],
      websiteGoals: ["*", "brand", "lead-gen", "conversion"],
      tags: ["trust", "logos", "metrics"],
      assetRole: "section",
      sectionKeywords: ["brand trust", "trust", "logo", "credibility"],
    }),
    def("TimelineSection", {
      kind: "timeline",
      industries: ["agency", "education", "clinic", "business", "*"],
      designStyles: ["editorial", "corporate", "minimal", "premium-brand"],
      audiences: ["professional", "client", "student", "patient"],
      websiteGoals: ["lead-gen", "brand", "content", "booking"],
      tags: ["timeline", "process"],
      assetRole: "section",
      sectionKeywords: ["timeline", "process", "journey", "steps"],
    }),
    def("ComparisonSection", {
      kind: "comparison",
      industries: ["saas", "ecommerce", "automotive", "business", "*"],
      designStyles: ["saas", "corporate", "modern", "technology"],
      audiences: ["buyer", "enterprise", "b2b", "shopper"],
      websiteGoals: ["conversion", "ecommerce", "lead-gen"],
      tags: ["comparison", "table"],
      assetRole: "section",
      sectionKeywords: ["comparison", "compare", "versus", "vs"],
    }),
    def("VideoSection", {
      kind: "video",
      industries: ["tourism", "agency", "automotive", "restaurant", "education", "*"],
      designStyles: ["cinematic", "creative", "luxury", "premium-brand"],
      audiences: ["creative", "traveler", "experience", "luxury"],
      websiteGoals: ["brand", "booking", "content"],
      tags: ["video", "cinematic"],
      assetRole: "section",
      sectionKeywords: ["video", "film", "watch", "motion"],
    }),
    def("GalleryExperience", {
      kind: "gallery-experience",
      industries: ["tourism", "restaurant", "agency", "ecommerce", "real-estate", "*"],
      designStyles: ["editorial", "luxury", "creative", "cinematic"],
      audiences: ["creative", "traveler", "luxury", "shopper"],
      websiteGoals: ["brand", "ecommerce", "booking"],
      tags: ["gallery", "mosaic", "experience"],
      assetRole: "section",
      sectionKeywords: ["gallery experience", "gallery", "atmosphere", "visual"],
    }),
    def("SiteHeader", {
      kind: "header",
      variant: "sticky",
      industries: ["*"],
      designStyles: ["*", "corporate", "modern", "minimal"],
      audiences: ["*"],
      websiteGoals: ["*"],
      tags: ["nav", "sticky"],
      sectionKeywords: ["header", "nav"],
    }),
    def("SiteHeaderTransparent", {
      kind: "header",
      variant: "transparent",
      industries: ["tourism", "restaurant", "agency", "automotive", "*"],
      designStyles: ["luxury", "cinematic", "creative", "travel premium"],
      audiences: ["luxury", "traveler", "creative"],
      websiteGoals: ["brand", "booking"],
      tags: ["nav", "transparent"],
      sectionKeywords: ["header", "nav", "transparent"],
    }),
    def("NavModern", {
      kind: "header",
      variant: "modern",
      industries: ["saas", "ecommerce", "agency", "*"],
      designStyles: ["modern", "tech", "minimal", "futuristic"],
      audiences: ["startup", "business", "shopper"],
      websiteGoals: ["conversion", "ecommerce", "lead-gen"],
      tags: ["nav", "modern"],
      sectionKeywords: ["header", "nav", "menu"],
    }),
    def("SiteFooter", {
      kind: "footer",
      industries: ["*"],
      designStyles: ["*"],
      audiences: ["*"],
      websiteGoals: ["*"],
      tags: ["footer"],
      sectionKeywords: ["footer"],
    }),
  ];

export function getCatalogEntry(
  id: DesignRendererComponentId,
): ProfessionalComponentDefinition | undefined {
  return PROFESSIONAL_COMPONENT_CATALOG.find((c) => c.id === id);
}

export function listCatalogByKind(
  kind: ProfessionalComponentDefinition["kind"],
): ProfessionalComponentDefinition[] {
  return PROFESSIONAL_COMPONENT_CATALOG.filter((c) => c.kind === kind);
}
