export {
  WB_TEMPLATE_PACKAGE_SPEC_VERSION,
  WB_TEMPLATE_MANIFEST_FILENAME,
  WB_TEMPLATE_PACKAGE_DIRS,
  WB_TEMPLATE_MEDIA_EXTENSIONS,
  WB_TEMPLATE_CATEGORIES,
  WB_TEMPLATE_UPDATE_CHANNELS,
  WB_TEMPLATE_LAYOUT_KINDS,
  WB_TEMPLATE_REGION_ROLES,
  WB_TEMPLATE_COMPONENT_ORDERING,
  WB_TEMPLATE_REGION_WIDTH,
  WB_TEMPLATE_REGION_ALIGNMENT,
  WB_TEMPLATE_KNOWN_COMPONENT_TYPES,
  WB_TEMPLATE_COMPONENT_CATEGORIES,
} from "@/lib/website/template-engine/spec/constants";

export {
  parseSemver,
  compareSemver,
  satisfiesSemverRange,
} from "@/lib/website/template-engine/spec/semver";
export type { SemverParts } from "@/lib/website/template-engine/spec/semver";

export {
  wbTemplatePackageManifestSchema,
  wbTemplatePackageEntrySchema,
  wbTemplateCanvasDocumentSchema,
  wbTemplatePlacementRulesDocumentSchema,
  wbTemplateComponentTypesDocumentSchema,
  wbTemplateLayoutDocumentSchema,
  wbTemplateRegionDocumentSchema,
  wbTemplatePageBlueprintSchema,
  wbTemplateAssetsManifestSchema,
  parseWbTemplatePackageManifest,
  safeParseWbTemplatePackageManifest,
} from "@/lib/website/template-engine/spec/schema";
export type { WbTemplatePackageManifestInput } from "@/lib/website/template-engine/spec/schema";

export { resolvePackageBlueprint } from "@/lib/website/template-engine/spec/resolve-blueprint";

export type {
  WbTemplateCategory,
  WbTemplateUpdateChannel,
  WbTemplateLayoutKind,
  WbTemplateRegionRole,
  WbTemplateComponentOrdering,
  WbTemplateRegionWidth,
  WbTemplateRegionAlignment,
  WbTemplateKnownComponentType,
  WbTemplateComponentCategory,
  WbTemplateAuthor,
  WbTemplateMetadata,
  WbTemplateMedia,
  WbTemplateCompatibility,
  WbTemplatePackageDependency,
  WbTemplateDependencies,
  WbTemplateUpdateInfo,
  WbTemplateResponsiveBreakpoint,
  WbTemplateResponsiveConfig,
  WbTemplateFileRef,
  WbTemplateLayoutRef,
  WbTemplateRegionRef,
  WbTemplatePageRef,
  WbTemplateAssetsConfig,
  WbTemplatePackageManifest,
  WbTemplatePackageEntry,
  WbTemplateCanvasDocument,
  WbTemplateRegionLayout,
  WbTemplateRegionPlacementRules,
  WbTemplateRegionResponsiveRules,
  WbTemplateRegionDocument,
  WbTemplateLayoutRules,
  WbTemplateLayoutDocument,
  WbTemplatePageBlueprint,
  WbTemplatePlacementConstraint,
  WbTemplatePlacementRulesDocument,
  WbTemplateComponentTypeDefinition,
  WbTemplateComponentTypesDocument,
  WbTemplateAssetFile,
  WbTemplateAssetsManifest,
  WbTemplateValidationIssue,
  WbTemplatePackageValidationResult,
  WbTemplateResolvedPackage,
  WbTemplatePageCanvasBlueprint,
} from "@/lib/website/template-engine/spec/types";
