// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import type { WbTemplateMarketplaceListing } from "@/lib/website/template-marketplace/types";

export const PREMIUM_REMOTE_TEMPLATE_SEEDS: WbTemplateMarketplaceListing[] = [
  {
    id: "modern-business",
    version: "2.0.0",
    name: "Corporate Command",
    description:
      "Executive-grade corporate presence with trust-first hierarchy, boardroom typography, and measured conversion paths.",
    category: "corporate",
    tags: ["corporate", "enterprise", "trust", "b2b"],
    layout: "single-column",
    regionCount: 3,
    pageCount: 4,
    thumbnail: "remote/modern-business/thumbnail.png",
    preview: "remote/modern-business/preview.png",
    source: "remote",
    availability: "remote",
    featured: true,
    featuredRank: 1,
    metadata: {
      author: {
        name: "Trend Business AI",
        organization: "Premium Template Studio",
      },
      license: "MIT",
      keywords: ["corporate", "executive", "boardroom", "trust"],
      updateChannel: "stable",
      releasedAt: "2026-07-30T17:52:40.193Z",
      templateIntelligenceId: "ti-corporate-trust",
      premium: true,
      compatibility: {
        engineVersion: ">=1.0.0",
        specVersion: "2.0.0",
        features: [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas",
        ],
      },
    },
    remote: {
      registryId: "modern-business",
      publisher: "trend-business-ai",
      publishedAt: "2026-07-30T17:52:40.193Z",
    },
  },
  {
    id: "ai-startup-signal",
    version: "2.0.0",
    name: "AI Signal",
    description:
      "Futuristic AI startup with cinematic full-bleed hero, glass bento panels, and signal-grade dark mode aesthetics.",
    category: "ai-startup",
    tags: ["ai", "startup", "ml", "futuristic"],
    layout: "full-bleed",
    regionCount: 4,
    pageCount: 4,
    thumbnail: "remote/ai-startup-signal/thumbnail.png",
    preview: "remote/ai-startup-signal/preview.png",
    source: "remote",
    availability: "remote",
    featured: true,
    featuredRank: 2,
    metadata: {
      author: {
        name: "Trend Business AI",
        organization: "Premium Template Studio",
      },
      license: "MIT",
      keywords: ["ai", "machine learning", "startup", "signal"],
      updateChannel: "stable",
      releasedAt: "2026-07-30T17:52:40.193Z",
      templateIntelligenceId: "ti-ai-company-signal",
      premium: true,
      compatibility: {
        engineVersion: ">=1.0.0",
        specVersion: "2.0.0",
        features: [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas",
        ],
      },
    },
    remote: {
      registryId: "ai-startup-signal",
      publisher: "trend-business-ai",
      publishedAt: "2026-07-30T17:52:40.193Z",
    },
  },
];
