// AUTO-GENERATED by scripts/generate-premium-template-library.mjs — do not edit manually.
import type { WbTemplateMarketplaceListing } from "@/lib/website/template-marketplace/types";

export const PREMIUM_REMOTE_TEMPLATE_SEEDS: WbTemplateMarketplaceListing[] = [
  {
    "id": "modern-business",
    "version": "2.0.0",
    "name": "Corporate Command",
    "description": "Executive-grade corporate presence with trust-first hierarchy, boardroom typography, and measured conversion paths.",
    "category": "corporate",
    "tags": [
      "corporate",
      "enterprise",
      "trust",
      "b2b"
    ],
    "layout": "single-column",
    "regionCount": 3,
    "pageCount": 4,
    "thumbnail": "remote/modern-business/thumbnail.png",
    "preview": "remote/modern-business/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 1,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "corporate",
        "executive",
        "boardroom",
        "trust"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-corporate-trust",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "modern-business",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "enterprise-scale",
    "version": "2.0.0",
    "name": "Enterprise Scale",
    "description": "Global enterprise platform with sidebar intelligence rail, capability matrix, and stakeholder-grade information design.",
    "category": "enterprise",
    "tags": [
      "enterprise",
      "global",
      "scale",
      "b2b"
    ],
    "layout": "sidebar-left",
    "regionCount": 4,
    "pageCount": 5,
    "thumbnail": "remote/enterprise-scale/thumbnail.png",
    "preview": "remote/enterprise-scale/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 2,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "enterprise",
        "global",
        "platform",
        "scale"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-consulting-clarity",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "enterprise-scale",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "saas-starter",
    "version": "2.0.0",
    "name": "SaaS Velocity",
    "description": "Product-led growth architecture with bento features, pricing bands, and conversion-optimized component rhythm.",
    "category": "saas",
    "tags": [
      "saas",
      "product-led",
      "growth",
      "pricing"
    ],
    "layout": "single-column",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/saas-starter/thumbnail.png",
    "preview": "remote/saas-starter/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 3,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "saas",
        "product",
        "growth",
        "pricing"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-saas-growth",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "saas-starter",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "ai-startup-signal",
    "version": "2.0.0",
    "name": "AI Signal",
    "description": "Futuristic AI startup with cinematic full-bleed hero, glass bento panels, and signal-grade dark mode aesthetics.",
    "category": "ai-startup",
    "tags": [
      "ai",
      "startup",
      "ml",
      "futuristic"
    ],
    "layout": "full-bleed",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/ai-startup-signal/thumbnail.png",
    "preview": "remote/ai-startup-signal/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 4,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "ai",
        "machine learning",
        "startup",
        "signal"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-ai-company-signal",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "ai-startup-signal",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "agency-portfolio",
    "version": "2.0.0",
    "name": "Creative Agency Studio",
    "description": "Award-winning creative studio layout with asymmetric case studies, editorial typography, and portfolio-first navigation.",
    "category": "creative-agency",
    "tags": [
      "agency",
      "creative",
      "portfolio",
      "studio"
    ],
    "layout": "sidebar-left",
    "regionCount": 4,
    "pageCount": 5,
    "thumbnail": "remote/agency-portfolio/thumbnail.png",
    "preview": "remote/agency-portfolio/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 5,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "creative agency",
        "studio",
        "case study",
        "design"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-creative-studio",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "agency-portfolio",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "marketing-agency-growth",
    "version": "2.0.0",
    "name": "Marketing Agency Growth",
    "description": "Performance marketing agency with bold conversion bands, client proof rails, and campaign showcase architecture.",
    "category": "marketing-agency",
    "tags": [
      "marketing",
      "agency",
      "growth",
      "performance"
    ],
    "layout": "sidebar-right",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/marketing-agency-growth/thumbnail.png",
    "preview": "remote/marketing-agency-growth/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 6,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "marketing agency",
        "growth",
        "campaigns",
        "performance"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-agency-portfolio",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "marketing-agency-growth",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "portfolio-showcase",
    "version": "2.0.0",
    "name": "Portfolio Showcase",
    "description": "Editorial portfolio for designers and photographers with magazine columns, overlay galleries, and minimal chrome.",
    "category": "portfolio",
    "tags": [
      "portfolio",
      "designer",
      "photographer",
      "editorial"
    ],
    "layout": "full-bleed",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/portfolio-showcase/thumbnail.png",
    "preview": "remote/portfolio-showcase/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 7,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "portfolio",
        "showcase",
        "editorial",
        "creative"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-blog-editorial",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "portfolio-showcase",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "restaurant-bistro",
    "version": "2.0.0",
    "name": "Restaurant Fine Dining",
    "description": "Michelin-caliber dining experience with cinematic food hero, tasting menu flow, and reservation-first hospitality.",
    "category": "restaurant",
    "tags": [
      "restaurant",
      "fine-dining",
      "chef",
      "reservations"
    ],
    "layout": "full-bleed",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/restaurant-bistro/thumbnail.png",
    "preview": "remote/restaurant-bistro/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 8,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "restaurant",
        "fine dining",
        "chef",
        "tasting menu"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-restaurant-dining",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "restaurant-bistro",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "cafe-artisan",
    "version": "2.0.0",
    "name": "Cafe Artisan",
    "description": "Neighborhood craft coffee with morning-light warmth, roast storytelling, and community reservation flows.",
    "category": "cafe",
    "tags": [
      "cafe",
      "coffee",
      "artisan",
      "brunch"
    ],
    "layout": "full-bleed",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/cafe-artisan/thumbnail.png",
    "preview": "remote/cafe-artisan/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 9,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "cafe",
        "coffee",
        "artisan",
        "brunch"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-cafe-artisan",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "cafe-artisan",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "hotel-sanctuary",
    "version": "2.0.0",
    "name": "Hotel Sanctuary",
    "description": "Five-star sanctuary hospitality with immersive room galleries, spa rituals, and concierge booking architecture.",
    "category": "hotel",
    "tags": [
      "hotel",
      "luxury",
      "hospitality",
      "spa"
    ],
    "layout": "full-bleed",
    "regionCount": 5,
    "pageCount": 5,
    "thumbnail": "remote/hotel-sanctuary/thumbnail.png",
    "preview": "remote/hotel-sanctuary/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 10,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "hotel",
        "luxury",
        "resort",
        "spa"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-hotel-sanctuary",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "hotel-sanctuary",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "travel-horizon",
    "version": "2.0.0",
    "name": "Travel Horizon",
    "description": "Wanderlust travel brand with destination cinematics, package grids, and expedition booking experiences.",
    "category": "travel",
    "tags": [
      "travel",
      "tourism",
      "adventure",
      "destinations"
    ],
    "layout": "single-column",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/travel-horizon/thumbnail.png",
    "preview": "remote/travel-horizon/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 11,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "travel",
        "tourism",
        "destinations",
        "adventure"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-travel-horizon",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "travel-horizon",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "real-estate-listings",
    "version": "2.0.0",
    "name": "Real Estate Listings",
    "description": "Premium property showcase with listing intelligence, neighborhood proof, and agent-led inquiry flows.",
    "category": "real-estate",
    "tags": [
      "real-estate",
      "property",
      "listings",
      "luxury"
    ],
    "layout": "sidebar-left",
    "regionCount": 5,
    "pageCount": 5,
    "thumbnail": "remote/real-estate-listings/thumbnail.png",
    "preview": "remote/real-estate-listings/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 12,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "real estate",
        "property",
        "listings",
        "luxury homes"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-real-estate-listings",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "real-estate-listings",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "architecture-monograph",
    "version": "2.0.0",
    "name": "Architecture Monograph",
    "description": "Architectural studio monograph with project folios, process essays, and inquiry-led studio contact.",
    "category": "architecture",
    "tags": [
      "architecture",
      "studio",
      "monograph",
      "design"
    ],
    "layout": "sidebar-right",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/architecture-monograph/thumbnail.png",
    "preview": "remote/architecture-monograph/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 13,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "architecture",
        "studio",
        "blueprint",
        "urban"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-architecture-monograph",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "architecture-monograph",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "construction-build",
    "version": "2.0.0",
    "name": "Construction Build",
    "description": "Industrial construction authority with capability matrix, safety credentials, and project bid architecture.",
    "category": "construction",
    "tags": [
      "construction",
      "contractor",
      "industrial",
      "infrastructure"
    ],
    "layout": "sidebar-left",
    "regionCount": 5,
    "pageCount": 5,
    "thumbnail": "remote/construction-build/thumbnail.png",
    "preview": "remote/construction-build/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 14,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "construction",
        "contractor",
        "building",
        "infrastructure"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-construction-industrial",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "construction-build",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "medical-care-plus",
    "version": "2.0.0",
    "name": "Medical Care Plus",
    "description": "Premium healthcare with clinical calm, physician profiles, appointment flows, and patient trust architecture.",
    "category": "medical",
    "tags": [
      "medical",
      "healthcare",
      "clinic",
      "hospital"
    ],
    "layout": "single-column",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/medical-care-plus/thumbnail.png",
    "preview": "remote/medical-care-plus/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 15,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "medical",
        "healthcare",
        "clinic",
        "hospital"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-medical-care",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "medical-care-plus",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "dental-smile",
    "version": "2.0.0",
    "name": "Dental Smile",
    "description": "Bright dental practice with smile-forward hero, treatment clarity, and reassuring patient booking flows.",
    "category": "dental",
    "tags": [
      "dental",
      "dentist",
      "smile",
      "orthodontics"
    ],
    "layout": "full-bleed",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/dental-smile/thumbnail.png",
    "preview": "remote/dental-smile/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "dental",
        "dentist",
        "smile",
        "clinic"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-dental-smile",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "dental-smile",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "pharmacy-wellness",
    "version": "2.0.0",
    "name": "Pharmacy Wellness",
    "description": "Community pharmacy with wellness lanes, pharmacist trust signals, and accessible refill booking.",
    "category": "pharmacy",
    "tags": [
      "pharmacy",
      "wellness",
      "health",
      "prescription"
    ],
    "layout": "sidebar-right",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/pharmacy-wellness/thumbnail.png",
    "preview": "remote/pharmacy-wellness/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 17,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "pharmacy",
        "wellness",
        "prescription",
        "health"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-pharmacy-wellness",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "pharmacy-wellness",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "law-firm-authority",
    "version": "2.0.0",
    "name": "Law Firm Authority",
    "description": "Authoritative legal practice with dark luxury hero, practice area depth, and consultation-first conversion.",
    "category": "law-firm",
    "tags": [
      "law",
      "legal",
      "attorney",
      "firm"
    ],
    "layout": "full-bleed",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/law-firm-authority/thumbnail.png",
    "preview": "remote/law-firm-authority/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "law firm",
        "attorney",
        "legal",
        "litigation"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-law-firm",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "law-firm-authority",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "finance-ledger-pro",
    "version": "2.0.0",
    "name": "Finance Ledger Pro",
    "description": "Institutional finance with data-forward trust, advisory profiles, and secure client portal architecture.",
    "category": "finance",
    "tags": [
      "finance",
      "wealth",
      "investment",
      "advisory"
    ],
    "layout": "sidebar-left",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/finance-ledger-pro/thumbnail.png",
    "preview": "remote/finance-ledger-pro/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "finance",
        "wealth management",
        "investment",
        "advisory"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-finance-ledger",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "finance-ledger-pro",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "insurance-shield",
    "version": "2.0.0",
    "name": "Insurance Shield",
    "description": "Coverage clarity with plan comparison, advisor trust, and quote-first protection architecture.",
    "category": "insurance",
    "tags": [
      "insurance",
      "coverage",
      "protection",
      "claims"
    ],
    "layout": "sidebar-right",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/insurance-shield/thumbnail.png",
    "preview": "remote/insurance-shield/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 20,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "insurance",
        "coverage",
        "policy",
        "claims"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-insurance-shield",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "insurance-shield",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "education-academy",
    "version": "2.0.0",
    "name": "Education Academy",
    "description": "Modern learning academy with program grids, faculty showcases, and enrollment-optimized admissions flows.",
    "category": "education",
    "tags": [
      "education",
      "academy",
      "learning",
      "courses"
    ],
    "layout": "single-column",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/education-academy/thumbnail.png",
    "preview": "remote/education-academy/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 21,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "education",
        "academy",
        "courses",
        "learning"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-education-campus",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "education-academy",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "university-heritage",
    "version": "2.0.0",
    "name": "University Heritage",
    "description": "Scholarly university brand with heritage typography, research highlights, and admissions grandeur.",
    "category": "university",
    "tags": [
      "university",
      "college",
      "campus",
      "research"
    ],
    "layout": "sidebar-right",
    "regionCount": 5,
    "pageCount": 5,
    "thumbnail": "remote/university-heritage/thumbnail.png",
    "preview": "remote/university-heritage/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 22,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "university",
        "college",
        "campus",
        "research"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-university-heritage",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "university-heritage",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "ecommerce-atelier",
    "version": "2.0.0",
    "name": "E-commerce Atelier",
    "description": "Luxury e-commerce with editorial product storytelling, curated collections, and seamless checkout architecture.",
    "category": "ecommerce",
    "tags": [
      "ecommerce",
      "retail",
      "shop",
      "luxury"
    ],
    "layout": "full-bleed",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/ecommerce-atelier/thumbnail.png",
    "preview": "remote/ecommerce-atelier/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": true,
    "featuredRank": 23,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "ecommerce",
        "retail",
        "shop",
        "luxury"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-ecommerce-atelier",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "ecommerce-atelier",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "fashion-runway",
    "version": "2.0.0",
    "name": "Fashion Runway",
    "description": "Haute couture editorial with runway cinematics, lookbook galleries, and luxury brand storytelling.",
    "category": "fashion",
    "tags": [
      "fashion",
      "luxury",
      "runway",
      "couture"
    ],
    "layout": "full-bleed",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/fashion-runway/thumbnail.png",
    "preview": "remote/fashion-runway/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "fashion",
        "luxury",
        "runway",
        "couture"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-luxury-brands-atelier",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "fashion-runway",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "beauty-glow",
    "version": "2.0.0",
    "name": "Beauty Glow",
    "description": "Luminous beauty and spa brand with ritual storytelling, treatment menus, and booking-first luxury flows.",
    "category": "beauty",
    "tags": [
      "beauty",
      "spa",
      "skincare",
      "salon"
    ],
    "layout": "full-bleed",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/beauty-glow/thumbnail.png",
    "preview": "remote/beauty-glow/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "beauty",
        "spa",
        "skincare",
        "salon"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-beauty-glow",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "beauty-glow",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "fitness-pulse",
    "version": "2.0.0",
    "name": "Fitness Pulse",
    "description": "High-energy fitness brand with dynamic hero, program intensity grids, and membership conversion architecture.",
    "category": "fitness",
    "tags": [
      "fitness",
      "gym",
      "training",
      "wellness"
    ],
    "layout": "single-column",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/fitness-pulse/thumbnail.png",
    "preview": "remote/fitness-pulse/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "fitness",
        "gym",
        "training",
        "crossfit"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-fitness-pulse",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "fitness-pulse",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "automotive-showroom",
    "version": "2.0.0",
    "name": "Automotive Showroom",
    "description": "Premium automotive showroom with vehicle stage hero, inventory intelligence, and test-drive booking flows.",
    "category": "automotive",
    "tags": [
      "automotive",
      "showroom",
      "luxury",
      "vehicles"
    ],
    "layout": "full-bleed",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/automotive-showroom/thumbnail.png",
    "preview": "remote/automotive-showroom/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "automotive",
        "showroom",
        "luxury cars",
        "dealership"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-automotive-showroom",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "automotive-showroom",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "logistics-freight",
    "version": "2.0.0",
    "name": "Logistics Freight",
    "description": "Global freight operations with route intelligence, fleet proof, and enterprise quote request architecture.",
    "category": "logistics",
    "tags": [
      "logistics",
      "freight",
      "shipping",
      "supply-chain"
    ],
    "layout": "sidebar-left",
    "regionCount": 5,
    "pageCount": 4,
    "thumbnail": "remote/logistics-freight/thumbnail.png",
    "preview": "remote/logistics-freight/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 28,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "logistics",
        "freight",
        "shipping",
        "supply chain"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-logistics-freight",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "logistics-freight",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "manufacturing-precision",
    "version": "2.0.0",
    "name": "Manufacturing Precision",
    "description": "Precision engineering manufacturer with capability matrix, quality certifications, and RFQ conversion flows.",
    "category": "manufacturing",
    "tags": [
      "manufacturing",
      "industrial",
      "engineering",
      "oem"
    ],
    "layout": "sidebar-right",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/manufacturing-precision/thumbnail.png",
    "preview": "remote/manufacturing-precision/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 29,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "manufacturing",
        "industrial",
        "engineering",
        "oem"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-manufacturing-precision",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "manufacturing-precision",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  },
  {
    "id": "nonprofit-impact",
    "version": "2.0.0",
    "name": "Nonprofit Impact",
    "description": "Humanitarian nonprofit with mission storytelling, impact metrics, volunteer paths, and donation architecture.",
    "category": "nonprofit",
    "tags": [
      "nonprofit",
      "charity",
      "impact",
      "donate"
    ],
    "layout": "single-column",
    "regionCount": 4,
    "pageCount": 4,
    "thumbnail": "remote/nonprofit-impact/thumbnail.png",
    "preview": "remote/nonprofit-impact/preview.png",
    "source": "remote",
    "availability": "remote",
    "featured": false,
    "featuredRank": 100,
    "metadata": {
      "author": {
        "name": "Trend Business AI",
        "organization": "Premium Template Studio"
      },
      "license": "MIT",
      "keywords": [
        "nonprofit",
        "charity",
        "foundation",
        "volunteer"
      ],
      "updateChannel": "stable",
      "releasedAt": "2026-07-30T17:52:40.193Z",
      "templateIntelligenceId": "ti-nonprofit-impact",
      "premium": true,
      "compatibility": {
        "engineVersion": ">=1.0.0",
        "specVersion": "2.0.0",
        "features": [
          "regions",
          "placement-rules",
          "responsive",
          "premium-canvas"
        ]
      }
    },
    "remote": {
      "registryId": "nonprofit-impact",
      "publisher": "trend-business-ai",
      "publishedAt": "2026-07-30T17:52:40.193Z"
    }
  }
] as WbTemplateMarketplaceListing[];
